// Code generated by tools/data_sync; DO NOT EDIT.

package observability

const SchemaVersion = 1

type Level string

const (
	LevelDebug Level = "debug"
	LevelInfo Level = "info"
	LevelWarn Level = "warn"
	LevelError Level = "error"
	LevelCritical Level = "critical"
)

type RetentionTier string

const (
	RetentionTierAuditGrade RetentionTier = "audit_grade"
	RetentionTierDiagnosticReport RetentionTier = "diagnostic_report"
	RetentionTierEphemeralDev RetentionTier = "ephemeral_dev"
	RetentionTierOperational RetentionTier = "operational"
)

type FieldName string

const (
	FieldNameAccountId FieldName = "account_id"
	FieldNameAction FieldName = "action"
	FieldNameActorId FieldName = "actor_id"
	FieldNameActorType FieldName = "actor_type"
	FieldNameAuditEventId FieldName = "audit_event_id"
	FieldNameAuditRequired FieldName = "audit_required"
	FieldNameAuditType FieldName = "audit_type"
	FieldNameBuildVersion FieldName = "build_version"
	FieldNameCaseId FieldName = "case_id"
	FieldNameCategory FieldName = "category"
	FieldNameDegradedState FieldName = "degraded_state"
	FieldNameDiagnosticReportId FieldName = "diagnostic_report_id"
	FieldNameDurationMs FieldName = "duration_ms"
	FieldNameEnvironment FieldName = "environment"
	FieldNameErrorCode FieldName = "error_code"
	FieldNameEvent FieldName = "event"
	FieldNameEventId FieldName = "event_id"
	FieldNameFailureMode FieldName = "failure_mode"
	FieldNameFields FieldName = "fields"
	FieldNameIdempotencyKey FieldName = "idempotency_key"
	FieldNameIngestedAt FieldName = "ingested_at"
	FieldNameIngestionAttempt FieldName = "ingestion_attempt"
	FieldNameIngestionId FieldName = "ingestion_id"
	FieldNameIngestionSource FieldName = "ingestion_source"
	FieldNameLevel FieldName = "level"
	FieldNameMatchId FieldName = "match_id"
	FieldNameMessage FieldName = "message"
	FieldNamePacketType FieldName = "packet_type"
	FieldNamePid FieldName = "pid"
	FieldNamePlayerId FieldName = "player_id"
	FieldNameReasonCode FieldName = "reason_code"
	FieldNameRedactionApplied FieldName = "redaction_applied"
	FieldNameRequestId FieldName = "request_id"
	FieldNameResultId FieldName = "result_id"
	FieldNameRetentionTier FieldName = "retention_tier"
	FieldNameRoomId FieldName = "room_id"
	FieldNameRoute FieldName = "route"
	FieldNameSchemaVersion FieldName = "schema_version"
	FieldNameService FieldName = "service"
	FieldNameServiceInstanceId FieldName = "service_instance_id"
	FieldNameSessionId FieldName = "session_id"
	FieldNameTargetId FieldName = "target_id"
	FieldNameTargetType FieldName = "target_type"
	FieldNameTimestamp FieldName = "timestamp"
	FieldNameTraceId FieldName = "trace_id"
	FieldNameTransactionId FieldName = "transaction_id"
	FieldNameWorkerId FieldName = "worker_id"
)

type EventName string

const (
	EventNameAccountRestrictionBlocked EventName = "account_restriction_blocked"
	EventNameAdminActionApplied EventName = "admin_action_applied"
	EventNameAdminActionFailed EventName = "admin_action_failed"
	EventNameAdminActionRequested EventName = "admin_action_requested"
	EventNameAdmissionFailed EventName = "admission_failed"
	EventNameAggregatorDuplicateSuppressed EventName = "aggregator_duplicate_suppressed"
	EventNameAggregatorEventAccepted EventName = "aggregator_event_accepted"
	EventNameAggregatorEventRedacted EventName = "aggregator_event_redacted"
	EventNameAggregatorEventRejected EventName = "aggregator_event_rejected"
	EventNameAggregatorQueryFailed EventName = "aggregator_query_failed"
	EventNameAggregatorStorageFailed EventName = "aggregator_storage_failed"
	EventNameAggregatorUnavailable EventName = "aggregator_unavailable"
	EventNameApiRateLimitTriggered EventName = "api_rate_limit_triggered"
	EventNameApiRequestCompleted EventName = "api_request_completed"
	EventNameApiRequestFailed EventName = "api_request_failed"
	EventNameApiRequestStarted EventName = "api_request_started"
	EventNameApiRequestTimeout EventName = "api_request_timeout"
	EventNameApiUnauthorized EventName = "api_unauthorized"
	EventNameApiUpstreamUnavailable EventName = "api_upstream_unavailable"
	EventNameApiValidationFailed EventName = "api_validation_failed"
	EventNameAuditRecordCreated EventName = "audit_record_created"
	EventNameAuditRecordCreationFailed EventName = "audit_record_creation_failed"
	EventNameAuthCallbackReceived EventName = "auth_callback_received"
	EventNameAuthFailed EventName = "auth_failed"
	EventNameAuthFlowStarted EventName = "auth_flow_started"
	EventNameAuthProviderUnavailable EventName = "auth_provider_unavailable"
	EventNameAuthSucceeded EventName = "auth_succeeded"
	EventNameBotTasFlagApplied EventName = "bot_tas_flag_applied"
	EventNameBugReportCreated EventName = "bug_report_created"
	EventNameBugReportUploadFailed EventName = "bug_report_upload_failed"
	EventNameBugReportUploadStarted EventName = "bug_report_upload_started"
	EventNameBugReportUploadSucceeded EventName = "bug_report_upload_succeeded"
	EventNameBuildVersionLoaded EventName = "build_version_loaded"
	EventNameClientConfigLoadFailed EventName = "client_config_load_failed"
	EventNameClientConnected EventName = "client_connected"
	EventNameClientConnectionFailed EventName = "client_connection_failed"
	EventNameClientDisconnected EventName = "client_disconnected"
	EventNameClientRuntimeMismatch EventName = "client_runtime_mismatch"
	EventNameClientStarting EventName = "client_starting"
	EventNameClientStartupFailed EventName = "client_startup_failed"
	EventNameCollisionShapeMissing EventName = "collision_shape_missing"
	EventNameCompatibilityBlocked EventName = "compatibility_blocked"
	EventNameConfigurationInvalid EventName = "configuration_invalid"
	EventNameConfigurationUnsafe EventName = "configuration_unsafe"
	EventNameConnectionAttemptStarted EventName = "connection_attempt_started"
	EventNameContractVersionLoaded EventName = "contract_version_loaded"
	EventNameCopyDiagnosticsGenerated EventName = "copy_diagnostics_generated"
	EventNameDatabaseMigrationFailed EventName = "database_migration_failed"
	EventNameDatabaseUnavailable EventName = "database_unavailable"
	EventNameDependencyHealthFailed EventName = "dependency_health_failed"
	EventNameDependencyInitializationFailed EventName = "dependency_initialization_failed"
	EventNameDevtoolsCommandApplied EventName = "devtools_command_applied"
	EventNameDevtoolsCommandRejected EventName = "devtools_command_rejected"
	EventNameDevtoolsEnabled EventName = "devtools_enabled"
	EventNameDiagnosticBundleCreated EventName = "diagnostic_bundle_created"
	EventNameDiagnosticChainGrouped EventName = "diagnostic_chain_grouped"
	EventNameDiagnosticRedactionFailed EventName = "diagnostic_redaction_failed"
	EventNameDiagnosticReportRejected EventName = "diagnostic_report_rejected"
	EventNameEntityCountThresholdCrossed EventName = "entity_count_threshold_crossed"
	EventNameEnvironmentDegraded EventName = "environment_degraded"
	EventNameEnvironmentRecovered EventName = "environment_recovered"
	EventNameEnvironmentSelected EventName = "environment_selected"
	EventNameFeatureModeLoaded EventName = "feature_mode_loaded"
	EventNameFramePressureThresholdCrossed EventName = "frame_pressure_threshold_crossed"
	EventNameGameOverDetected EventName = "game_over_detected"
	EventNameGameServerClientConnected EventName = "game_server_client_connected"
	EventNameGameServerClientDisconnected EventName = "game_server_client_disconnected"
	EventNameGameServerConnectionUpgradeFailed EventName = "game_server_connection_upgrade_failed"
	EventNameGameServerReadFailed EventName = "game_server_read_failed"
	EventNameGameServerWriteFailed EventName = "game_server_write_failed"
	EventNameGameServerWriteSlow EventName = "game_server_write_slow"
	EventNameIdempotencyConflict EventName = "idempotency_conflict"
	EventNameImpossibleStateDetected EventName = "impossible_state_detected"
	EventNameIntegrityCheckFailed EventName = "integrity_check_failed"
	EventNameIntegrityEligibilityChanged EventName = "integrity_eligibility_changed"
	EventNameInvalidEntityStateDetected EventName = "invalid_entity_state_detected"
	EventNameLivenessCheckFailed EventName = "liveness_check_failed"
	EventNameLoadScenarioCompleted EventName = "load_scenario_completed"
	EventNameLoadScenarioFailed EventName = "load_scenario_failed"
	EventNameLoadScenarioStarted EventName = "load_scenario_started"
	EventNameLocalServerConnected EventName = "local_server_connected"
	EventNameLocalServerExitedUnexpectedly EventName = "local_server_exited_unexpectedly"
	EventNameLocalServerLaunchFailed EventName = "local_server_launch_failed"
	EventNameLocalServerLaunchRequested EventName = "local_server_launch_requested"
	EventNameMaintenanceModeEntered EventName = "maintenance_mode_entered"
	EventNameMaintenanceModeExited EventName = "maintenance_mode_exited"
	EventNameMatchEnded EventName = "match_ended"
	EventNameMatchResultDuplicateSuppressed EventName = "match_result_duplicate_suppressed"
	EventNameMatchResultMarkedPending EventName = "match_result_marked_pending"
	EventNameMatchResultReportFailed EventName = "match_result_report_failed"
	EventNameMatchResultReportStarted EventName = "match_result_report_started"
	EventNameMatchResultReportSucceeded EventName = "match_result_report_succeeded"
	EventNameMatchResultRetryExhausted EventName = "match_result_retry_exhausted"
	EventNameMatchResultRetryScheduled EventName = "match_result_retry_scheduled"
	EventNameMatchResultRetrySucceeded EventName = "match_result_retry_succeeded"
	EventNameMatchStarted EventName = "match_started"
	EventNameMemoryGrowthThresholdCrossed EventName = "memory_growth_threshold_crossed"
	EventNameModerationActionApplied EventName = "moderation_action_applied"
	EventNameObservabilityUnavailable EventName = "observability_unavailable"
	EventNameOutboundPacketEncodeFailed EventName = "outbound_packet_encode_failed"
	EventNamePacketDecodeFailed EventName = "packet_decode_failed"
	EventNamePacketEnvelopeDecodeFailed EventName = "packet_envelope_decode_failed"
	EventNamePacketRouteFailed EventName = "packet_route_failed"
	EventNamePacketRouteUnknown EventName = "packet_route_unknown"
	EventNamePacketSizeThresholdCrossed EventName = "packet_size_threshold_crossed"
	EventNamePlayerDataReadFailed EventName = "player_data_read_failed"
	EventNamePlayerDataStoreInitializationFailed EventName = "player_data_store_initialization_failed"
	EventNamePlayerDataStoreInitialized EventName = "player_data_store_initialized"
	EventNamePlayerDataWriteFailed EventName = "player_data_write_failed"
	EventNamePlayerDied EventName = "player_died"
	EventNameProductionCapabilityViolation EventName = "production_capability_violation"
	EventNameProfileBackupFailed EventName = "profile_backup_failed"
	EventNameProfileMigrationFailed EventName = "profile_migration_failed"
	EventNameProfileMigrationStarted EventName = "profile_migration_started"
	EventNameProfileMigrationSucceeded EventName = "profile_migration_succeeded"
	EventNameReadinessCheckFailed EventName = "readiness_check_failed"
	EventNameReconnectAttemptScheduled EventName = "reconnect_attempt_scheduled"
	EventNameReconnectFailed EventName = "reconnect_failed"
	EventNameReconnectSucceeded EventName = "reconnect_succeeded"
	EventNameRespawnBlocked EventName = "respawn_blocked"
	EventNameRetentionPolicyApplied EventName = "retention_policy_applied"
	EventNameRewardCalculationFailed EventName = "reward_calculation_failed"
	EventNameRewardGrantFailed EventName = "reward_grant_failed"
	EventNameRewardGrantSucceeded EventName = "reward_grant_succeeded"
	EventNameRoomCleanedUp EventName = "room_cleaned_up"
	EventNameRoomCountdownCanceled EventName = "room_countdown_canceled"
	EventNameRoomCountdownStarted EventName = "room_countdown_started"
	EventNameRoomCreated EventName = "room_created"
	EventNameRoomCreationFailed EventName = "room_creation_failed"
	EventNameRoomJoinFailed EventName = "room_join_failed"
	EventNameRoomMatchEnded EventName = "room_match_ended"
	EventNameRoomMatchStarted EventName = "room_match_started"
	EventNameRoomPlayerRemoved EventName = "room_player_removed"
	EventNameRoomReadyStateChanged EventName = "room_ready_state_changed"
	EventNameServiceEnteredAdmissionBlockedState EventName = "service_entered_admission_blocked_state"
	EventNameServiceEnteredDegradedState EventName = "service_entered_degraded_state"
	EventNameServiceRecovered EventName = "service_recovered"
	EventNameServiceStarted EventName = "service_started"
	EventNameServiceStarting EventName = "service_starting"
	EventNameServiceStartupFailed EventName = "service_startup_failed"
	EventNameServiceStopped EventName = "service_stopped"
	EventNameServiceStopping EventName = "service_stopping"
	EventNameSimulationPanicRecovered EventName = "simulation_panic_recovered"
	EventNameSlowTickThresholdCrossed EventName = "slow_tick_threshold_crossed"
	EventNameSoakDegradationDetected EventName = "soak_degradation_detected"
	EventNameStorageBackendInvalid EventName = "storage_backend_invalid"
	EventNameStorageBackendSelected EventName = "storage_backend_selected"
	EventNameSuspiciousPacketRejected EventName = "suspicious_packet_rejected"
)

// RequiredFields and CanonicalLevels are immutable by convention.
var RequiredFields = []FieldName{
	FieldNameTimestamp,
	FieldNameLevel,
	FieldNameEvent,
	FieldNameEventId,
	FieldNameService,
	FieldNameEnvironment,
	FieldNameBuildVersion,
	FieldNameSchemaVersion,
	FieldNameServiceInstanceId,
}

var CanonicalLevels = []Level{
	LevelDebug,
	LevelInfo,
	LevelWarn,
	LevelError,
	LevelCritical,
}

type FieldDefinition struct {
	Name FieldName
	Type string
	Required bool
	Description string
	Sensitivity string
}

type EventDefinition struct {
	Name EventName
	Category string
	DefaultLevel Level
	Description string
	Services []string
	TraceRequired bool
	AuditEligible bool
	RetentionTier RetentionTier
}

// FieldDefinitions and EventDefinitions are immutable by convention.
var FieldDefinitions = map[FieldName]FieldDefinition{
	FieldNameAccountId: {Name: FieldNameAccountId, Type: "string", Required: false, Description: "Existing domain-owned identifier for an account when account context is relevant.", Sensitivity: "personal"},
	FieldNameAction: {Name: FieldNameAction, Type: "string", Required: false, Description: "Stable action name for an audit-worthy state change.", Sensitivity: "confidential"},
	FieldNameActorId: {Name: FieldNameActorId, Type: "string", Required: false, Description: "Existing domain-owned identifier for the actor responsible for an audit-worthy action.", Sensitivity: "confidential"},
	FieldNameActorType: {Name: FieldNameActorType, Type: "string", Required: false, Description: "Category of actor, such as player, service, admin, or system.", Sensitivity: "confidential"},
	FieldNameAuditEventId: {Name: FieldNameAuditEventId, Type: "uuid", Required: false, Description: "UUID reference for an audit-grade record, when one is created.", Sensitivity: "confidential"},
	FieldNameAuditRequired: {Name: FieldNameAuditRequired, Type: "boolean", Required: false, Description: "When true, the aggregator validates, preserves, and promotes the event into an audit-grade record.", Sensitivity: "confidential"},
	FieldNameAuditType: {Name: FieldNameAuditType, Type: "string", Required: false, Description: "Domain-defined audit classification used when audit_required is true.", Sensitivity: "confidential"},
	FieldNameBuildVersion: {Name: FieldNameBuildVersion, Type: "string", Required: true, Description: "Build or release version of the emitting component.", Sensitivity: "internal"},
	FieldNameCaseId: {Name: FieldNameCaseId, Type: "uuid", Required: false, Description: "UUID identifying a support, moderation, dispute, or administrative case.", Sensitivity: "confidential"},
	FieldNameCategory: {Name: FieldNameCategory, Type: "string", Required: false, Description: "Stable subsystem category used for filtering and category-level log controls.", Sensitivity: "internal"},
	FieldNameDegradedState: {Name: FieldNameDegradedState, Type: "string", Required: false, Description: "Named degraded, offline, maintenance, or admission-blocked state.", Sensitivity: "internal"},
	FieldNameDiagnosticReportId: {Name: FieldNameDiagnosticReportId, Type: "uuid", Required: false, Description: "UUID identifying a diagnostic report or bundle.", Sensitivity: "internal"},
	FieldNameDurationMs: {Name: FieldNameDurationMs, Type: "number", Required: false, Description: "Bounded duration measurement in milliseconds for the operation summarized by the event.", Sensitivity: "internal"},
	FieldNameEnvironment: {Name: FieldNameEnvironment, Type: "string", Required: true, Description: "Runtime environment in which the event was emitted.", Sensitivity: "internal"},
	FieldNameErrorCode: {Name: FieldNameErrorCode, Type: "string", Required: false, Description: "Stable machine-readable error code.", Sensitivity: "internal"},
	FieldNameEvent: {Name: FieldNameEvent, Type: "string", Required: true, Description: "Stable snake_case event name used for grouping, search, and automation.", Sensitivity: "internal"},
	FieldNameEventId: {Name: FieldNameEventId, Type: "uuid", Required: true, Description: "Unique identifier for this event; newly created values must use UUID format.", Sensitivity: "internal"},
	FieldNameFailureMode: {Name: FieldNameFailureMode, Type: "string", Required: false, Description: "Categorized reason or mode for an observed failure.", Sensitivity: "internal"},
	FieldNameFields: {Name: FieldNameFields, Type: "object", Required: false, Description: "Bounded event-specific key/value data; keys and scalar values must obey schema limits and redaction rules.", Sensitivity: "restricted"},
	FieldNameIdempotencyKey: {Name: FieldNameIdempotencyKey, Type: "string", Required: false, Description: "Bounded opaque key used to correlate retries and suppress duplicate effects; never include secrets.", Sensitivity: "internal"},
	FieldNameIngestedAt: {Name: FieldNameIngestedAt, Type: "string", Required: false, Description: "RFC3339-nanosecond UTC time at which the aggregator accepted the event.", Sensitivity: "internal"},
	FieldNameIngestionAttempt: {Name: FieldNameIngestionAttempt, Type: "integer", Required: false, Description: "Positive bounded attempt number for delivery or retry ingestion.", Sensitivity: "internal"},
	FieldNameIngestionId: {Name: FieldNameIngestionId, Type: "uuid", Required: false, Description: "UUID assigned to an ingestion request or batch by the receiving aggregator.", Sensitivity: "internal"},
	FieldNameIngestionSource: {Name: FieldNameIngestionSource, Type: "string", Required: false, Description: "Named source or transport from which the aggregator received the event.", Sensitivity: "internal"},
	FieldNameLevel: {Name: FieldNameLevel, Type: "string", Required: true, Description: "Operational severity; one of debug, info, warn, error, or critical.", Sensitivity: "internal"},
	FieldNameMatchId: {Name: FieldNameMatchId, Type: "string", Required: false, Description: "Existing domain-owned identifier for a match or match-result flow.", Sensitivity: "internal"},
	FieldNameMessage: {Name: FieldNameMessage, Type: "string", Required: false, Description: "Human-readable context; tooling must use event rather than parsing this text.", Sensitivity: "internal"},
	FieldNamePacketType: {Name: FieldNamePacketType, Type: "string", Required: false, Description: "Packet type associated with a network event, without including the packet payload.", Sensitivity: "internal"},
	FieldNamePid: {Name: FieldNamePid, Type: "integer", Required: false, Description: "Operating-system process identifier for local diagnostics.", Sensitivity: "internal"},
	FieldNamePlayerId: {Name: FieldNamePlayerId, Type: "string", Required: false, Description: "Readable player-facing identifier, such as Player-1; do not replace it with a UUID for observability.", Sensitivity: "personal"},
	FieldNameReasonCode: {Name: FieldNameReasonCode, Type: "string", Required: false, Description: "Stable non-sensitive reason code for an action or decision.", Sensitivity: "confidential"},
	FieldNameRedactionApplied: {Name: FieldNameRedactionApplied, Type: "boolean", Required: false, Description: "Indicates that one or more unsafe or sensitive values were removed or transformed before storage or export.", Sensitivity: "internal"},
	FieldNameRequestId: {Name: FieldNameRequestId, Type: "string", Required: false, Description: "Existing domain-owned identifier for an API or HTTP request.", Sensitivity: "internal"},
	FieldNameResultId: {Name: FieldNameResultId, Type: "uuid", Required: false, Description: "UUID identifying a competitive or persisted match result.", Sensitivity: "confidential"},
	FieldNameRetentionTier: {Name: FieldNameRetentionTier, Type: "string", Required: false, Description: "Retention classification: ephemeral_dev, operational, diagnostic_report, or audit_grade.", Sensitivity: "internal"},
	FieldNameRoomId: {Name: FieldNameRoomId, Type: "string", Required: false, Description: "Existing domain-owned identifier for a room flow.", Sensitivity: "internal"},
	FieldNameRoute: {Name: FieldNameRoute, Type: "string", Required: false, Description: "API, HTTP, or logical route associated with the event; exclude credentials and raw secrets.", Sensitivity: "internal"},
	FieldNameSchemaVersion: {Name: FieldNameSchemaVersion, Type: "integer", Required: true, Description: "Observability event schema version; the permanent contract currently defines version 1.", Sensitivity: "internal"},
	FieldNameService: {Name: FieldNameService, Type: "string", Required: true, Description: "Product service or client component that emitted the event.", Sensitivity: "internal"},
	FieldNameServiceInstanceId: {Name: FieldNameServiceInstanceId, Type: "uuid", Required: true, Description: "UUID identifying the running service instance that emitted the event.", Sensitivity: "internal"},
	FieldNameSessionId: {Name: FieldNameSessionId, Type: "string", Required: false, Description: "Existing domain-owned identifier for a gameplay or service session.", Sensitivity: "internal"},
	FieldNameTargetId: {Name: FieldNameTargetId, Type: "string", Required: false, Description: "Existing domain-owned identifier for the target of an audit-worthy action.", Sensitivity: "confidential"},
	FieldNameTargetType: {Name: FieldNameTargetType, Type: "string", Required: false, Description: "Category of target affected by an audit-worthy action.", Sensitivity: "confidential"},
	FieldNameTimestamp: {Name: FieldNameTimestamp, Type: "string", Required: true, Description: "Event creation time as an RFC3339 timestamp with nanosecond precision, normalized to UTC.", Sensitivity: "internal"},
	FieldNameTraceId: {Name: FieldNameTraceId, Type: "uuid", Required: false, Description: "UUID correlating one distributed operation or investigation chain.", Sensitivity: "internal"},
	FieldNameTransactionId: {Name: FieldNameTransactionId, Type: "uuid", Required: false, Description: "UUID identifying a transaction or entitlement operation without exposing payment data.", Sensitivity: "confidential"},
	FieldNameWorkerId: {Name: FieldNameWorkerId, Type: "string", Required: false, Description: "Worker name or index for the worker or job execution that emitted the event.", Sensitivity: "internal"},
}

var EventDefinitions = map[EventName]EventDefinition{
	EventNameAccountRestrictionBlocked: {Name: EventNameAccountRestrictionBlocked, Category: "session_admission", DefaultLevel: LevelWarn, Description: "A banned or suspended account was blocked from admission.", Services: []string{"api_server", "game_server"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameAdminActionApplied: {Name: EventNameAdminActionApplied, Category: "devtools_admin", DefaultLevel: LevelInfo, Description: "An administrative state-changing action was applied.", Services: []string{"api_server", "game_server", "player_data"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameAdminActionFailed: {Name: EventNameAdminActionFailed, Category: "devtools_admin", DefaultLevel: LevelError, Description: "An administrative state-changing action failed.", Services: []string{"api_server", "game_server", "player_data"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameAdminActionRequested: {Name: EventNameAdminActionRequested, Category: "devtools_admin", DefaultLevel: LevelInfo, Description: "An administrative state-changing action was requested.", Services: []string{"api_server", "game_server"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameAdmissionFailed: {Name: EventNameAdmissionFailed, Category: "session_admission", DefaultLevel: LevelWarn, Description: "Session admission failed after authentication or environment checks.", Services: []string{"api_server", "client", "game_server"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameAggregatorDuplicateSuppressed: {Name: EventNameAggregatorDuplicateSuppressed, Category: "aggregator_ingestion", DefaultLevel: LevelDebug, Description: "The aggregator suppressed a duplicate event.", Services: []string{"log_aggregator"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierEphemeralDev},
	EventNameAggregatorEventAccepted: {Name: EventNameAggregatorEventAccepted, Category: "aggregator_ingestion", DefaultLevel: LevelDebug, Description: "The aggregator accepted an event or batch.", Services: []string{"log_aggregator"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierEphemeralDev},
	EventNameAggregatorEventRedacted: {Name: EventNameAggregatorEventRedacted, Category: "aggregator_ingestion", DefaultLevel: LevelWarn, Description: "The aggregator redacted unsafe or sensitive event fields.", Services: []string{"log_aggregator"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameAggregatorEventRejected: {Name: EventNameAggregatorEventRejected, Category: "aggregator_ingestion", DefaultLevel: LevelWarn, Description: "The aggregator rejected an event or batch for schema or safety reasons.", Services: []string{"log_aggregator"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameAggregatorQueryFailed: {Name: EventNameAggregatorQueryFailed, Category: "aggregator_query", DefaultLevel: LevelError, Description: "An aggregator search or filtering query failed.", Services: []string{"log_aggregator"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameAggregatorStorageFailed: {Name: EventNameAggregatorStorageFailed, Category: "aggregator_storage", DefaultLevel: LevelCritical, Description: "Durable aggregator storage failed.", Services: []string{"log_aggregator"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameAggregatorUnavailable: {Name: EventNameAggregatorUnavailable, Category: "aggregator_lifecycle", DefaultLevel: LevelError, Description: "The log aggregator is unavailable; producers must remain non-blocking.", Services: []string{"api_server", "client", "game_server", "log_aggregator", "player_data"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameApiRateLimitTriggered: {Name: EventNameApiRateLimitTriggered, Category: "api_request", DefaultLevel: LevelWarn, Description: "An API rate limit was triggered.", Services: []string{"api_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameApiRequestCompleted: {Name: EventNameApiRequestCompleted, Category: "api_request", DefaultLevel: LevelDebug, Description: "An API request completed successfully.", Services: []string{"api_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameApiRequestFailed: {Name: EventNameApiRequestFailed, Category: "api_request", DefaultLevel: LevelError, Description: "An API request failed.", Services: []string{"api_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameApiRequestStarted: {Name: EventNameApiRequestStarted, Category: "api_request", DefaultLevel: LevelDebug, Description: "An API request began.", Services: []string{"api_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierEphemeralDev},
	EventNameApiRequestTimeout: {Name: EventNameApiRequestTimeout, Category: "api_request", DefaultLevel: LevelWarn, Description: "An API request exceeded its timeout.", Services: []string{"api_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameApiUnauthorized: {Name: EventNameApiUnauthorized, Category: "api_request", DefaultLevel: LevelWarn, Description: "An API request was unauthorized or forbidden.", Services: []string{"api_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameApiUpstreamUnavailable: {Name: EventNameApiUpstreamUnavailable, Category: "api_request", DefaultLevel: LevelError, Description: "An API upstream dependency was unavailable.", Services: []string{"api_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameApiValidationFailed: {Name: EventNameApiValidationFailed, Category: "api_request", DefaultLevel: LevelWarn, Description: "An API request failed input validation.", Services: []string{"api_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameAuditRecordCreated: {Name: EventNameAuditRecordCreated, Category: "aggregator_storage", DefaultLevel: LevelInfo, Description: "An audit-required event was validated and promoted to an audit-grade record.", Services: []string{"log_aggregator"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameAuditRecordCreationFailed: {Name: EventNameAuditRecordCreationFailed, Category: "aggregator_storage", DefaultLevel: LevelCritical, Description: "The aggregator could not persist an audit-grade record.", Services: []string{"log_aggregator"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameAuthCallbackReceived: {Name: EventNameAuthCallbackReceived, Category: "auth", DefaultLevel: LevelInfo, Description: "An authentication provider callback was received without recording credentials.", Services: []string{"api_server", "client"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameAuthFailed: {Name: EventNameAuthFailed, Category: "auth", DefaultLevel: LevelWarn, Description: "Authentication failed.", Services: []string{"api_server", "client"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameAuthFlowStarted: {Name: EventNameAuthFlowStarted, Category: "auth", DefaultLevel: LevelInfo, Description: "An authentication flow began.", Services: []string{"api_server", "client"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameAuthProviderUnavailable: {Name: EventNameAuthProviderUnavailable, Category: "auth", DefaultLevel: LevelError, Description: "An authentication provider was unavailable.", Services: []string{"api_server", "client"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameAuthSucceeded: {Name: EventNameAuthSucceeded, Category: "auth", DefaultLevel: LevelInfo, Description: "Authentication completed successfully.", Services: []string{"api_server", "client"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameBotTasFlagApplied: {Name: EventNameBotTasFlagApplied, Category: "integrity", DefaultLevel: LevelWarn, Description: "A bot or tool-assisted-run flag was attached to a run or result.", Services: []string{"api_server", "game_server", "player_data"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameBugReportCreated: {Name: EventNameBugReportCreated, Category: "diagnostics", DefaultLevel: LevelInfo, Description: "A bug report was created with diagnostic context.", Services: []string{"client", "log_aggregator"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameBugReportUploadFailed: {Name: EventNameBugReportUploadFailed, Category: "diagnostics", DefaultLevel: LevelWarn, Description: "A diagnostic report upload failed while local diagnostics remain available.", Services: []string{"client", "log_aggregator"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameBugReportUploadStarted: {Name: EventNameBugReportUploadStarted, Category: "diagnostics", DefaultLevel: LevelInfo, Description: "A diagnostic report upload began.", Services: []string{"client", "log_aggregator"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameBugReportUploadSucceeded: {Name: EventNameBugReportUploadSucceeded, Category: "diagnostics", DefaultLevel: LevelInfo, Description: "A diagnostic report upload succeeded.", Services: []string{"client", "log_aggregator"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameBuildVersionLoaded: {Name: EventNameBuildVersionLoaded, Category: "configuration", DefaultLevel: LevelInfo, Description: "The build or release version was loaded.", Services: []string{"api_server", "client", "game_server", "log_aggregator", "player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameClientConfigLoadFailed: {Name: EventNameClientConfigLoadFailed, Category: "client_startup", DefaultLevel: LevelError, Description: "Client configuration could not be loaded.", Services: []string{"client"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameClientConnected: {Name: EventNameClientConnected, Category: "client_network", DefaultLevel: LevelInfo, Description: "The client established a network connection.", Services: []string{"api_server", "client", "game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameClientConnectionFailed: {Name: EventNameClientConnectionFailed, Category: "client_network", DefaultLevel: LevelWarn, Description: "A client network connection attempt failed.", Services: []string{"api_server", "client", "game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameClientDisconnected: {Name: EventNameClientDisconnected, Category: "client_network", DefaultLevel: LevelWarn, Description: "The client lost a connection unexpectedly or completed an expected disconnect.", Services: []string{"api_server", "client", "game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameClientRuntimeMismatch: {Name: EventNameClientRuntimeMismatch, Category: "client_startup", DefaultLevel: LevelError, Description: "The packaged client runtime does not match its expected release contract.", Services: []string{"client"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameClientStarting: {Name: EventNameClientStarting, Category: "client_startup", DefaultLevel: LevelInfo, Description: "The client has begun startup.", Services: []string{"client"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameClientStartupFailed: {Name: EventNameClientStartupFailed, Category: "client_startup", DefaultLevel: LevelError, Description: "The client failed to boot its main scene or session shell.", Services: []string{"client"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameCollisionShapeMissing: {Name: EventNameCollisionShapeMissing, Category: "simulation", DefaultLevel: LevelWarn, Description: "An authoritative simulation entity lacked a required collision shape.", Services: []string{"game_server"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameCompatibilityBlocked: {Name: EventNameCompatibilityBlocked, Category: "session_admission", DefaultLevel: LevelWarn, Description: "A client or session was blocked by compatibility checks.", Services: []string{"api_server", "client", "game_server"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameConfigurationInvalid: {Name: EventNameConfigurationInvalid, Category: "configuration", DefaultLevel: LevelCritical, Description: "Required or parsed configuration is invalid.", Services: []string{"api_server", "client", "game_server", "log_aggregator", "player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameConfigurationUnsafe: {Name: EventNameConfigurationUnsafe, Category: "configuration", DefaultLevel: LevelCritical, Description: "Configuration would permit an unsafe release or environment behavior.", Services: []string{"api_server", "client", "game_server", "log_aggregator", "player_data"}, TraceRequired: false, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameConnectionAttemptStarted: {Name: EventNameConnectionAttemptStarted, Category: "client_network", DefaultLevel: LevelDebug, Description: "A client network connection attempt began.", Services: []string{"client"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierEphemeralDev},
	EventNameContractVersionLoaded: {Name: EventNameContractVersionLoaded, Category: "configuration", DefaultLevel: LevelInfo, Description: "The protocol, API, or data contract version was loaded.", Services: []string{"api_server", "client", "game_server", "log_aggregator", "player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameCopyDiagnosticsGenerated: {Name: EventNameCopyDiagnosticsGenerated, Category: "diagnostics", DefaultLevel: LevelInfo, Description: "Safe copyable diagnostics were generated for a user or tester.", Services: []string{"client", "log_aggregator"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameDatabaseMigrationFailed: {Name: EventNameDatabaseMigrationFailed, Category: "player_data", DefaultLevel: LevelCritical, Description: "A database migration failed.", Services: []string{"player_data"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameDatabaseUnavailable: {Name: EventNameDatabaseUnavailable, Category: "player_data", DefaultLevel: LevelError, Description: "The player-data database or storage dependency is unavailable.", Services: []string{"player_data"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameDependencyHealthFailed: {Name: EventNameDependencyHealthFailed, Category: "health_readiness", DefaultLevel: LevelError, Description: "A required dependency failed health checks.", Services: []string{"api_server", "game_server", "log_aggregator", "player_data"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameDependencyInitializationFailed: {Name: EventNameDependencyInitializationFailed, Category: "service_lifecycle", DefaultLevel: LevelError, Description: "A required dependency failed during initialization.", Services: []string{"api_server", "game_server", "log_aggregator", "player_data"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameDevtoolsCommandApplied: {Name: EventNameDevtoolsCommandApplied, Category: "devtools_admin", DefaultLevel: LevelInfo, Description: "A state-changing devtools command was applied.", Services: []string{"client", "game_server"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameDevtoolsCommandRejected: {Name: EventNameDevtoolsCommandRejected, Category: "devtools_admin", DefaultLevel: LevelWarn, Description: "A devtools command was rejected by capability or validation policy.", Services: []string{"client", "game_server"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameDevtoolsEnabled: {Name: EventNameDevtoolsEnabled, Category: "devtools_admin", DefaultLevel: LevelInfo, Description: "Devtools capability was enabled in an allowed environment.", Services: []string{"client", "game_server"}, TraceRequired: false, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameDiagnosticBundleCreated: {Name: EventNameDiagnosticBundleCreated, Category: "diagnostics", DefaultLevel: LevelInfo, Description: "A bounded diagnostic bundle was created.", Services: []string{"client", "game_server", "log_aggregator"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameDiagnosticChainGrouped: {Name: EventNameDiagnosticChainGrouped, Category: "aggregator_query", DefaultLevel: LevelInfo, Description: "Events were grouped into a correlation-preserving diagnostic chain.", Services: []string{"log_aggregator"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameDiagnosticRedactionFailed: {Name: EventNameDiagnosticRedactionFailed, Category: "diagnostics", DefaultLevel: LevelCritical, Description: "Required diagnostic redaction failed, preventing safe export or storage.", Services: []string{"client", "log_aggregator"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameDiagnosticReportRejected: {Name: EventNameDiagnosticReportRejected, Category: "diagnostics", DefaultLevel: LevelWarn, Description: "A diagnostic report was rejected for unsafe or invalid fields.", Services: []string{"log_aggregator"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameEntityCountThresholdCrossed: {Name: EventNameEntityCountThresholdCrossed, Category: "runtime_threshold", DefaultLevel: LevelWarn, Description: "Active entity count crossed its configured warning threshold.", Services: []string{"game_server"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameEnvironmentDegraded: {Name: EventNameEnvironmentDegraded, Category: "health_readiness", DefaultLevel: LevelWarn, Description: "The operating environment entered a degraded condition.", Services: []string{"api_server", "client", "game_server", "log_aggregator", "player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameEnvironmentRecovered: {Name: EventNameEnvironmentRecovered, Category: "health_readiness", DefaultLevel: LevelInfo, Description: "The operating environment recovered from degradation.", Services: []string{"api_server", "client", "game_server", "log_aggregator", "player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameEnvironmentSelected: {Name: EventNameEnvironmentSelected, Category: "configuration", DefaultLevel: LevelInfo, Description: "The runtime environment was selected.", Services: []string{"api_server", "client", "game_server", "log_aggregator", "player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameFeatureModeLoaded: {Name: EventNameFeatureModeLoaded, Category: "configuration", DefaultLevel: LevelInfo, Description: "A feature flag, devtools mode, or release capability was loaded.", Services: []string{"api_server", "client", "game_server"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierEphemeralDev},
	EventNameFramePressureThresholdCrossed: {Name: EventNameFramePressureThresholdCrossed, Category: "runtime_threshold", DefaultLevel: LevelWarn, Description: "Client frame pressure crossed its configured warning threshold.", Services: []string{"client"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameGameOverDetected: {Name: EventNameGameOverDetected, Category: "simulation", DefaultLevel: LevelInfo, Description: "The authoritative simulation detected game over.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameGameServerClientConnected: {Name: EventNameGameServerClientConnected, Category: "game_networking", DefaultLevel: LevelInfo, Description: "A client connected to the game server.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameGameServerClientDisconnected: {Name: EventNameGameServerClientDisconnected, Category: "game_networking", DefaultLevel: LevelWarn, Description: "A client disconnected unexpectedly from the game server.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameGameServerConnectionUpgradeFailed: {Name: EventNameGameServerConnectionUpgradeFailed, Category: "game_networking", DefaultLevel: LevelWarn, Description: "A game-server WebSocket upgrade failed.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameGameServerReadFailed: {Name: EventNameGameServerReadFailed, Category: "game_networking", DefaultLevel: LevelWarn, Description: "A game-server socket read failed unexpectedly.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameGameServerWriteFailed: {Name: EventNameGameServerWriteFailed, Category: "game_networking", DefaultLevel: LevelError, Description: "A game-server socket write failed.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameGameServerWriteSlow: {Name: EventNameGameServerWriteSlow, Category: "runtime_threshold", DefaultLevel: LevelWarn, Description: "A game-server write exceeded its latency threshold.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameIdempotencyConflict: {Name: EventNameIdempotencyConflict, Category: "api_request", DefaultLevel: LevelWarn, Description: "An idempotency key conflicted with an existing operation.", Services: []string{"api_server", "player_data"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameImpossibleStateDetected: {Name: EventNameImpossibleStateDetected, Category: "integrity", DefaultLevel: LevelWarn, Description: "An impossible state or input was detected.", Services: []string{"client", "game_server"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameIntegrityCheckFailed: {Name: EventNameIntegrityCheckFailed, Category: "integrity", DefaultLevel: LevelWarn, Description: "An integrity check failed or produced a suspicious result.", Services: []string{"api_server", "client", "game_server"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameIntegrityEligibilityChanged: {Name: EventNameIntegrityEligibilityChanged, Category: "integrity", DefaultLevel: LevelWarn, Description: "A player's or result's integrity eligibility changed.", Services: []string{"api_server", "player_data"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameInvalidEntityStateDetected: {Name: EventNameInvalidEntityStateDetected, Category: "simulation", DefaultLevel: LevelError, Description: "The authoritative simulation detected an invalid entity state.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameLivenessCheckFailed: {Name: EventNameLivenessCheckFailed, Category: "health_readiness", DefaultLevel: LevelError, Description: "Internal liveness checks failed.", Services: []string{"api_server", "game_server", "log_aggregator", "player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameLoadScenarioCompleted: {Name: EventNameLoadScenarioCompleted, Category: "runtime_threshold", DefaultLevel: LevelInfo, Description: "A bounded load or soak scenario completed.", Services: []string{"api_server", "game_server", "log_aggregator"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierEphemeralDev},
	EventNameLoadScenarioFailed: {Name: EventNameLoadScenarioFailed, Category: "runtime_threshold", DefaultLevel: LevelError, Description: "A bounded load or soak scenario failed.", Services: []string{"api_server", "game_server", "log_aggregator"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameLoadScenarioStarted: {Name: EventNameLoadScenarioStarted, Category: "runtime_threshold", DefaultLevel: LevelInfo, Description: "A bounded load or soak scenario began.", Services: []string{"api_server", "game_server", "log_aggregator"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierEphemeralDev},
	EventNameLocalServerConnected: {Name: EventNameLocalServerConnected, Category: "client_startup", DefaultLevel: LevelInfo, Description: "The client connected to its bundled local server.", Services: []string{"client", "game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameLocalServerExitedUnexpectedly: {Name: EventNameLocalServerExitedUnexpectedly, Category: "client_startup", DefaultLevel: LevelError, Description: "The bundled local server exited without an expected shutdown.", Services: []string{"client", "game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameLocalServerLaunchFailed: {Name: EventNameLocalServerLaunchFailed, Category: "client_startup", DefaultLevel: LevelError, Description: "The bundled local server failed to launch.", Services: []string{"client", "game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameLocalServerLaunchRequested: {Name: EventNameLocalServerLaunchRequested, Category: "client_startup", DefaultLevel: LevelInfo, Description: "The client requested launch of the bundled local server.", Services: []string{"client"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameMaintenanceModeEntered: {Name: EventNameMaintenanceModeEntered, Category: "health_readiness", DefaultLevel: LevelWarn, Description: "A service or environment entered maintenance mode.", Services: []string{"api_server", "game_server", "log_aggregator", "player_data"}, TraceRequired: false, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameMaintenanceModeExited: {Name: EventNameMaintenanceModeExited, Category: "health_readiness", DefaultLevel: LevelInfo, Description: "A service or environment exited maintenance mode.", Services: []string{"api_server", "game_server", "log_aggregator", "player_data"}, TraceRequired: false, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameMatchEnded: {Name: EventNameMatchEnded, Category: "simulation", DefaultLevel: LevelInfo, Description: "Authoritative match simulation ended.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameMatchResultDuplicateSuppressed: {Name: EventNameMatchResultDuplicateSuppressed, Category: "match_results", DefaultLevel: LevelInfo, Description: "A duplicate or idempotent match result was suppressed.", Services: []string{"api_server", "player_data"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameMatchResultMarkedPending: {Name: EventNameMatchResultMarkedPending, Category: "match_results", DefaultLevel: LevelWarn, Description: "A match result was preserved as pending for later delivery or processing.", Services: []string{"api_server", "game_server", "player_data"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameMatchResultReportFailed: {Name: EventNameMatchResultReportFailed, Category: "match_results", DefaultLevel: LevelError, Description: "A match result report failed.", Services: []string{"api_server", "game_server", "player_data"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameMatchResultReportStarted: {Name: EventNameMatchResultReportStarted, Category: "match_results", DefaultLevel: LevelInfo, Description: "A match result report began.", Services: []string{"api_server", "game_server", "player_data"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameMatchResultReportSucceeded: {Name: EventNameMatchResultReportSucceeded, Category: "match_results", DefaultLevel: LevelInfo, Description: "A match result report was accepted and persisted.", Services: []string{"api_server", "game_server", "player_data"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameMatchResultRetryExhausted: {Name: EventNameMatchResultRetryExhausted, Category: "match_results", DefaultLevel: LevelError, Description: "All configured retries for a match result operation were exhausted.", Services: []string{"api_server", "player_data"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameMatchResultRetryScheduled: {Name: EventNameMatchResultRetryScheduled, Category: "match_results", DefaultLevel: LevelWarn, Description: "A failed match result operation was scheduled for retry.", Services: []string{"api_server", "player_data"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameMatchResultRetrySucceeded: {Name: EventNameMatchResultRetrySucceeded, Category: "match_results", DefaultLevel: LevelInfo, Description: "A retried match result operation succeeded.", Services: []string{"api_server", "player_data"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameMatchStarted: {Name: EventNameMatchStarted, Category: "simulation", DefaultLevel: LevelInfo, Description: "Authoritative match simulation started.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameMemoryGrowthThresholdCrossed: {Name: EventNameMemoryGrowthThresholdCrossed, Category: "runtime_threshold", DefaultLevel: LevelWarn, Description: "Observed memory growth crossed its configured warning threshold.", Services: []string{"api_server", "client", "game_server", "log_aggregator", "player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameModerationActionApplied: {Name: EventNameModerationActionApplied, Category: "integrity", DefaultLevel: LevelWarn, Description: "A moderation or enforcement action was applied.", Services: []string{"api_server", "game_server"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameObservabilityUnavailable: {Name: EventNameObservabilityUnavailable, Category: "health_readiness", DefaultLevel: LevelError, Description: "Telemetry or logging was unavailable before or after launch.", Services: []string{"api_server", "client", "game_server", "log_aggregator", "player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameOutboundPacketEncodeFailed: {Name: EventNameOutboundPacketEncodeFailed, Category: "game_networking", DefaultLevel: LevelError, Description: "A game-server outbound packet could not be encoded.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNamePacketDecodeFailed: {Name: EventNamePacketDecodeFailed, Category: "networking", DefaultLevel: LevelWarn, Description: "A received packet could not be decoded.", Services: []string{"client", "game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNamePacketEnvelopeDecodeFailed: {Name: EventNamePacketEnvelopeDecodeFailed, Category: "game_networking", DefaultLevel: LevelWarn, Description: "A game-server packet envelope could not be decoded.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNamePacketRouteFailed: {Name: EventNamePacketRouteFailed, Category: "game_networking", DefaultLevel: LevelWarn, Description: "A game-server packet could not be routed.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNamePacketRouteUnknown: {Name: EventNamePacketRouteUnknown, Category: "networking", DefaultLevel: LevelWarn, Description: "A decoded packet had no known route.", Services: []string{"client", "game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNamePacketSizeThresholdCrossed: {Name: EventNamePacketSizeThresholdCrossed, Category: "runtime_threshold", DefaultLevel: LevelWarn, Description: "A packet size warning or danger threshold was crossed.", Services: []string{"client", "game_server"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNamePlayerDataReadFailed: {Name: EventNamePlayerDataReadFailed, Category: "player_data", DefaultLevel: LevelError, Description: "A player-data read failed.", Services: []string{"api_server", "player_data"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNamePlayerDataStoreInitializationFailed: {Name: EventNamePlayerDataStoreInitializationFailed, Category: "player_data", DefaultLevel: LevelCritical, Description: "The player-data store failed initialization.", Services: []string{"player_data"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNamePlayerDataStoreInitialized: {Name: EventNamePlayerDataStoreInitialized, Category: "player_data", DefaultLevel: LevelInfo, Description: "The player-data store initialized successfully.", Services: []string{"player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNamePlayerDataWriteFailed: {Name: EventNamePlayerDataWriteFailed, Category: "player_data", DefaultLevel: LevelError, Description: "A player-data write failed.", Services: []string{"api_server", "player_data"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNamePlayerDied: {Name: EventNamePlayerDied, Category: "simulation", DefaultLevel: LevelInfo, Description: "A player avatar died in authoritative simulation.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameProductionCapabilityViolation: {Name: EventNameProductionCapabilityViolation, Category: "configuration", DefaultLevel: LevelCritical, Description: "A production build exposed a forbidden client or server capability.", Services: []string{"client", "game_server"}, TraceRequired: false, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameProfileBackupFailed: {Name: EventNameProfileBackupFailed, Category: "profile_migration", DefaultLevel: LevelError, Description: "A local profile migration backup failed.", Services: []string{"client", "player_data"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameProfileMigrationFailed: {Name: EventNameProfileMigrationFailed, Category: "profile_migration", DefaultLevel: LevelError, Description: "A local profile migration failed.", Services: []string{"client", "player_data"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameProfileMigrationStarted: {Name: EventNameProfileMigrationStarted, Category: "profile_migration", DefaultLevel: LevelInfo, Description: "A local profile migration began.", Services: []string{"client", "player_data"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameProfileMigrationSucceeded: {Name: EventNameProfileMigrationSucceeded, Category: "profile_migration", DefaultLevel: LevelInfo, Description: "A local profile migration completed successfully.", Services: []string{"client", "player_data"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameReadinessCheckFailed: {Name: EventNameReadinessCheckFailed, Category: "health_readiness", DefaultLevel: LevelWarn, Description: "A service failed readiness checks.", Services: []string{"api_server", "game_server", "log_aggregator", "player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameReconnectAttemptScheduled: {Name: EventNameReconnectAttemptScheduled, Category: "client_network", DefaultLevel: LevelWarn, Description: "A client reconnect attempt was scheduled after connection loss.", Services: []string{"client"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameReconnectFailed: {Name: EventNameReconnectFailed, Category: "client_network", DefaultLevel: LevelWarn, Description: "A client reconnect attempt failed.", Services: []string{"client", "game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameReconnectSucceeded: {Name: EventNameReconnectSucceeded, Category: "client_network", DefaultLevel: LevelInfo, Description: "A client reconnect attempt succeeded.", Services: []string{"client", "game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameRespawnBlocked: {Name: EventNameRespawnBlocked, Category: "simulation", DefaultLevel: LevelWarn, Description: "A requested player respawn was blocked.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameRetentionPolicyApplied: {Name: EventNameRetentionPolicyApplied, Category: "aggregator_retention", DefaultLevel: LevelInfo, Description: "Configured retention policy was applied to aggregated records.", Services: []string{"log_aggregator"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameRewardCalculationFailed: {Name: EventNameRewardCalculationFailed, Category: "progression", DefaultLevel: LevelError, Description: "Reward calculation for a completed result failed.", Services: []string{"api_server", "player_data"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameRewardGrantFailed: {Name: EventNameRewardGrantFailed, Category: "progression", DefaultLevel: LevelError, Description: "A reward grant failed.", Services: []string{"api_server", "player_data"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameRewardGrantSucceeded: {Name: EventNameRewardGrantSucceeded, Category: "progression", DefaultLevel: LevelInfo, Description: "A reward grant completed successfully.", Services: []string{"api_server", "player_data"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameRoomCleanedUp: {Name: EventNameRoomCleanedUp, Category: "rooms", DefaultLevel: LevelInfo, Description: "A room was cleaned up after its lifecycle ended.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameRoomCountdownCanceled: {Name: EventNameRoomCountdownCanceled, Category: "rooms", DefaultLevel: LevelInfo, Description: "A room starting countdown was canceled.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameRoomCountdownStarted: {Name: EventNameRoomCountdownStarted, Category: "rooms", DefaultLevel: LevelInfo, Description: "A room starting countdown began.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameRoomCreated: {Name: EventNameRoomCreated, Category: "rooms", DefaultLevel: LevelInfo, Description: "A game-server room was created.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameRoomCreationFailed: {Name: EventNameRoomCreationFailed, Category: "rooms", DefaultLevel: LevelError, Description: "A game-server room could not be created.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameRoomJoinFailed: {Name: EventNameRoomJoinFailed, Category: "rooms", DefaultLevel: LevelWarn, Description: "A player could not join a room.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameRoomMatchEnded: {Name: EventNameRoomMatchEnded, Category: "rooms", DefaultLevel: LevelInfo, Description: "A room ended a match.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameRoomMatchStarted: {Name: EventNameRoomMatchStarted, Category: "rooms", DefaultLevel: LevelInfo, Description: "A room started a match.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameRoomPlayerRemoved: {Name: EventNameRoomPlayerRemoved, Category: "rooms", DefaultLevel: LevelInfo, Description: "A player was removed from a room by timeout or an administrative action.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
	EventNameRoomReadyStateChanged: {Name: EventNameRoomReadyStateChanged, Category: "rooms", DefaultLevel: LevelDebug, Description: "A room changed its readiness state.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierEphemeralDev},
	EventNameServiceEnteredAdmissionBlockedState: {Name: EventNameServiceEnteredAdmissionBlockedState, Category: "service_lifecycle", DefaultLevel: LevelWarn, Description: "A service is running but blocks new admissions.", Services: []string{"api_server", "game_server", "player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameServiceEnteredDegradedState: {Name: EventNameServiceEnteredDegradedState, Category: "service_lifecycle", DefaultLevel: LevelWarn, Description: "A service entered a named degraded operating state.", Services: []string{"api_server", "client", "game_server", "log_aggregator", "player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameServiceRecovered: {Name: EventNameServiceRecovered, Category: "service_lifecycle", DefaultLevel: LevelInfo, Description: "A service recovered from a degraded, offline, or blocked state.", Services: []string{"api_server", "client", "game_server", "log_aggregator", "player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameServiceStarted: {Name: EventNameServiceStarted, Category: "service_lifecycle", DefaultLevel: LevelInfo, Description: "A service completed startup and is available for normal operation.", Services: []string{"api_server", "game_server", "log_aggregator", "player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameServiceStarting: {Name: EventNameServiceStarting, Category: "service_lifecycle", DefaultLevel: LevelInfo, Description: "A service has begun startup.", Services: []string{"api_server", "game_server", "log_aggregator", "player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameServiceStartupFailed: {Name: EventNameServiceStartupFailed, Category: "service_lifecycle", DefaultLevel: LevelCritical, Description: "A service could not complete startup.", Services: []string{"api_server", "game_server", "log_aggregator", "player_data"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameServiceStopped: {Name: EventNameServiceStopped, Category: "service_lifecycle", DefaultLevel: LevelInfo, Description: "A service completed shutdown.", Services: []string{"api_server", "game_server", "log_aggregator", "player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameServiceStopping: {Name: EventNameServiceStopping, Category: "service_lifecycle", DefaultLevel: LevelInfo, Description: "A service has begun an intentional shutdown.", Services: []string{"api_server", "game_server", "log_aggregator", "player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameSimulationPanicRecovered: {Name: EventNameSimulationPanicRecovered, Category: "simulation", DefaultLevel: LevelCritical, Description: "The game server recovered from a simulation panic or unsafe failure.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameSlowTickThresholdCrossed: {Name: EventNameSlowTickThresholdCrossed, Category: "runtime_threshold", DefaultLevel: LevelWarn, Description: "Simulation tick duration crossed its configured warning threshold.", Services: []string{"game_server"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameSoakDegradationDetected: {Name: EventNameSoakDegradationDetected, Category: "runtime_threshold", DefaultLevel: LevelError, Description: "A soak run detected sustained runtime degradation.", Services: []string{"api_server", "client", "game_server", "log_aggregator"}, TraceRequired: true, AuditEligible: false, RetentionTier: RetentionTierDiagnosticReport},
	EventNameStorageBackendInvalid: {Name: EventNameStorageBackendInvalid, Category: "player_data", DefaultLevel: LevelCritical, Description: "The configured storage backend is invalid for the environment.", Services: []string{"player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameStorageBackendSelected: {Name: EventNameStorageBackendSelected, Category: "player_data", DefaultLevel: LevelInfo, Description: "The player-data storage backend was selected.", Services: []string{"player_data"}, TraceRequired: false, AuditEligible: false, RetentionTier: RetentionTierOperational},
	EventNameSuspiciousPacketRejected: {Name: EventNameSuspiciousPacketRejected, Category: "integrity", DefaultLevel: LevelWarn, Description: "A suspicious or invalid packet was rejected.", Services: []string{"game_server"}, TraceRequired: true, AuditEligible: true, RetentionTier: RetentionTierAuditGrade},
}

func IsCanonicalLevel(value Level) bool {
	switch value {
	case LevelDebug, LevelInfo, LevelWarn, LevelError, LevelCritical:
		return true
	default:
		return false
	}
}

func IsKnownField(value FieldName) bool {
	_, ok := FieldDefinitions[value]
	return ok
}

func IsKnownEvent(value EventName) bool {
	_, ok := EventDefinitions[value]
	return ok
}

func IsRetentionTier(value RetentionTier) bool {
	switch value {
	case RetentionTierAuditGrade, RetentionTierDiagnosticReport, RetentionTierEphemeralDev, RetentionTierOperational:
		return true
	default:
		return false
	}
}

func FieldDefinitionFor(value FieldName) (FieldDefinition, bool) {
	definition, ok := FieldDefinitions[value]
	return definition, ok
}

func EventDefinitionFor(value EventName) (EventDefinition, bool) {
	definition, ok := EventDefinitions[value]
	return definition, ok
}

const UUIDPattern = "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
const EventNamePattern = "^[a-z0-9]+(?:_[a-z0-9]+)*$"
const FreeFormKeyPattern = "^[a-z][a-z0-9_]{0,63}$"

const (
	MaxBatchEvents = 100
	MaxEventBytes = 65536
	MaxEventFields = 64
	MaxStringBytes = 4096
	MaxCollectionItems = 128
	MaxFreeFormFields = 32
	MaxFreeFormValueBytes = 4096
	MaxDiagnosticBundleEvents = 500
	MaxDiagnosticBundleEventBytes = 65536
	MaxDiagnosticBundleTotalBytes = 5242880
	MaxDiagnosticBundleMetadataFields = 32
	MaxDiagnosticBundleCorrelationFields = 16
	MaxDiagnosticBundleRedactionSummaryEntries = 32
)
