// Code generated by tools/data_sync/main.py; DO NOT EDIT.
package game

import runtime "github.com/Lokee86/space-rocks/services/game-server/internal/game/runtime"

const (
	PacketTypeInput                         = "input"
	PacketTypeClientConfig                  = "client_config"
	PacketTypeBulletBlast                   = "bullet_blast"
	PacketTypeShipDeath                     = "ship_death"
	PacketTypeRespawn                       = "respawn"
	PacketTypePauseRequest                  = "pause_request"
	PacketTypePlayerPauseState              = "player_pause_state"
	PacketTypeSetTargetPlayerRequest        = "set_target_player_request"
	PacketTypeSelectTargetAtPositionRequest = "select_target_at_position_request"
	PacketTypeClearTargetRequest            = "clear_target_request"
	PacketTypeSetViewTargetRequest          = "set_view_target_request"
	PacketTypeClearViewTargetRequest        = "clear_view_target_request"
	PacketTypeResyncRequest                 = "resync_request"
	PacketTypeCreateRoomRequest             = "create_room_request"
	PacketTypeJoinRoomRequest               = "join_room_request"
	PacketTypeLeaveRoomRequest              = "leave_room_request"
	PacketTypeSetReadyRequest               = "set_ready_request"
	PacketTypeSetTeamAssignmentRequest      = "set_team_assignment_request"
	PacketTypeLoadoutOptionsRequest         = "loadout_options_request"
	PacketTypeLoadoutOptions                = "loadout_options"
	PacketTypeSetLoadoutRequest             = "set_loadout_request"
	PacketTypeStartGameRequest              = "start_game_request"
	PacketTypeAddBotRequest                 = "add_bot_request"
	PacketTypeRemoveRoomMemberRequest       = "remove_room_member_request"
	PacketTypeStartSinglePlayerRequest      = "start_single_player_request"
	PacketTypeReturnToLobbyRequest          = "return_to_lobby_request"
	PacketTypeAuthenticateRequest           = "authenticate_request"
	PacketTypeAuthenticateResult            = "authenticate_result"
	PacketTypeRoomSnapshot                  = "room_snapshot"
	PacketTypeRoomStateChanged              = "room_state_changed"
	PacketTypeRoomError                     = "room_error"
	PacketTypeWebrtcOffer                   = "webrtc_offer"
	PacketTypeWebrtcAnswer                  = "webrtc_answer"
	PacketTypeWebrtcIceCandidate            = "webrtc_ice_candidate"
	PacketTypeWebrtcReady                   = "webrtc_ready"
	PacketTypeWebrtcSmoke                   = "webrtc_smoke"
	PacketTypeWebrtcFailed                  = "webrtc_failed"
)

type ClientPacket struct {
	Type                   string               `json:"type"`
	TraceID                string               `json:"trace_id"`
	MatchID                string               `json:"match_id"`
	Input                  runtime.InputState   `json:"input"`
	Config                 runtime.ClientConfig `json:"config"`
	RoomCode               string               `json:"room_code"`
	LocalProfileID         string               `json:"local_profile_id"`
	PlayMode               string               `json:"play_mode"`
	ModeID                 string               `json:"mode_id"`
	TeamStructure          string               `json:"team_structure"`
	TeamAssignmentMode     string               `json:"team_assignment_mode"`
	TeamCount              int                  `json:"team_count"`
	MaxPlayers             int                  `json:"max_players"`
	PresetID               string               `json:"preset_id"`
	StartingLives          int                  `json:"starting_lives"`
	InfiniteLives          bool                 `json:"infinite_lives"`
	TargetScore            int                  `json:"target_score"`
	TargetPlayerID         string               `json:"target_player_id"`
	ViewTargetPlayerID     string               `json:"view_target_player_id"`
	TeamID                 string               `json:"team_id"`
	Ready                  bool                 `json:"ready"`
	PlayerID               string               `json:"player_id"`
	SelectedOwnedShipID    string               `json:"selected_owned_ship_id"`
	SelectedWeaponsByPoint map[string]string    `json:"selected_weapons_by_point"`
	SelectedModulesBySlot  map[string]string    `json:"selected_modules_by_slot"`
	StartingAmmoByPoint    map[string]int       `json:"starting_ammo_by_point"`
	X                      float64              `json:"x"`
	Y                      float64              `json:"y"`
	TargetKind             string               `json:"target_kind"`
	TargetID               string               `json:"target_id"`
	Token                  string               `json:"token"`
	Sequence               int                  `json:"sequence"`
	Lane                   string               `json:"lane"`
	BaselineID             string               `json:"baseline_id"`
	Reason                 string               `json:"reason"`
}

type PlayerLocatorState struct {
	ID        string  `json:"id"`
	X         float64 `json:"x"`
	Y         float64 `json:"y"`
	VelocityX float64 `json:"velocity_x"`
	VelocityY float64 `json:"velocity_y"`
	Active    bool    `json:"active"`
}

type CreateRoomRequest struct {
	Type               string `json:"type"`
	TraceID            string `json:"trace_id"`
	LocalProfileID     string `json:"local_profile_id"`
	TeamStructure      string `json:"team_structure"`
	TeamAssignmentMode string `json:"team_assignment_mode"`
	TeamCount          int    `json:"team_count"`
	MaxPlayers         int    `json:"max_players"`
	PresetID           string `json:"preset_id"`
	StartingLives      int    `json:"starting_lives"`
	InfiniteLives      bool   `json:"infinite_lives"`
	TargetScore        int    `json:"target_score"`
}

type JoinRoomRequest struct {
	Type     string `json:"type"`
	TraceID  string `json:"trace_id"`
	RoomCode string `json:"room_code"`
}

type LeaveRoomRequest struct {
	Type string `json:"type"`
}

type SetReadyRequest struct {
	Type  string `json:"type"`
	Ready bool   `json:"ready"`
}

type SetTeamAssignmentRequest struct {
	Type           string `json:"type"`
	TargetPlayerID string `json:"target_player_id"`
	TeamID         string `json:"team_id"`
}

type LoadoutOptionsRequest struct {
	Type           string `json:"type"`
	TraceID        string `json:"trace_id"`
	LocalProfileID string `json:"local_profile_id"`
	PlayMode       string `json:"play_mode"`
	ModeID         string `json:"mode_id"`
}

type SetLoadoutRequest struct {
	Type                   string            `json:"type"`
	TraceID                string            `json:"trace_id"`
	SelectedOwnedShipID    string            `json:"selected_owned_ship_id"`
	SelectedWeaponsByPoint map[string]string `json:"selected_weapons_by_point"`
	SelectedModulesBySlot  map[string]string `json:"selected_modules_by_slot"`
	StartingAmmoByPoint    map[string]int    `json:"starting_ammo_by_point"`
}

type StartGameRequest struct {
	Type string `json:"type"`
}

type AddBotRequest struct {
	Type string `json:"type"`
}

type RemoveRoomMemberRequest struct {
	Type     string `json:"type"`
	PlayerID string `json:"player_id"`
}

type StartSinglePlayerRequest struct {
	Type           string `json:"type"`
	TraceID        string `json:"trace_id"`
	LocalProfileID string `json:"local_profile_id"`
}

type ReturnToLobbyRequest struct {
	Type string `json:"type"`
}

type AuthenticateRequest struct {
	Type    string `json:"type"`
	Token   string `json:"token"`
	TraceID string `json:"trace_id"`
}

type AuthenticateResult struct {
	Type          string `json:"type"`
	Authenticated bool   `json:"authenticated"`
	TraceID       string `json:"trace_id"`
	UserID        int    `json:"user_id"`
	DisplayName   string `json:"display_name"`
	ErrorCode     string `json:"error_code"`
	Message       string `json:"message"`
}

type BuildShipOption struct {
	OwnedShipID            string `json:"owned_ship_id"`
	ShipID                 string `json:"ship_id"`
	WeightClass            string `json:"weight_class"`
	DefaultPrimaryWeaponID string `json:"default_primary_weapon_id"`
}

type BuildWeaponOption struct {
	OwnedWeaponID string `json:"owned_weapon_id"`
	WeaponID      string `json:"weapon_id"`
	WeaponPoint   string `json:"weapon_point"`
}

type BuildModuleOption struct {
	OwnedModuleID string `json:"owned_module_id"`
	ModuleID      string `json:"module_id"`
	ModuleSlot    string `json:"module_slot"`
}

type BuildBlockedOption struct {
	Kind            string `json:"kind"`
	OwnedInstanceID string `json:"owned_instance_id"`
	CatalogID       string `json:"catalog_id"`
	WeaponPoint     string `json:"weapon_point"`
	ModuleSlot      string `json:"module_slot"`
	ReasonCode      string `json:"reason_code"`
}

type EligibleBuildOptionsState struct {
	ModeID          string               `json:"mode_id"`
	PlayerID        string               `json:"player_id"`
	EligibleShips   []BuildShipOption    `json:"eligible_ships"`
	EligibleWeapons []BuildWeaponOption  `json:"eligible_weapons"`
	EligibleModules []BuildModuleOption  `json:"eligible_modules"`
	BlockedOptions  []BuildBlockedOption `json:"blocked_options"`
}

type LoadoutSelectionState struct {
	SelectedOwnedShipID    string            `json:"selected_owned_ship_id"`
	SelectedWeaponsByPoint map[string]string `json:"selected_weapons_by_point"`
	SelectedModulesBySlot  map[string]string `json:"selected_modules_by_slot"`
	StartingAmmoByPoint    map[string]int    `json:"starting_ammo_by_point"`
	Valid                  bool              `json:"valid"`
	ErrorCode              string            `json:"error_code"`
	Message                string            `json:"message"`
}

type LoadoutOptionsPacket struct {
	Type             string                    `json:"type"`
	TraceID          string                    `json:"trace_id"`
	BuildOptions     EligibleBuildOptionsState `json:"build_options"`
	LoadoutSelection LoadoutSelectionState     `json:"loadout_selection"`
}

type RoomMemberState struct {
	PlayerID  string `json:"player_id"`
	Ready     bool   `json:"ready"`
	Connected bool   `json:"connected"`
	IsBot     bool   `json:"is_bot"`
	TeamID    string `json:"team_id"`
}

type RoomPlayerMatchSummary struct {
	GamePlayerID string `json:"game_player_id"`
	TeamID       string `json:"team_id"`
	Score        int    `json:"score"`
	ShipDeaths   int    `json:"ship_deaths"`
	Won          bool   `json:"won"`
}

type RoomMatchResultSummary struct {
	MatchID string                   `json:"match_id"`
	Mode    string                   `json:"mode"`
	Players []RoomPlayerMatchSummary `json:"players"`
}

type RoomSnapshot struct {
	Type                  string                    `json:"type"`
	RoomCode              string                    `json:"room_code"`
	RoomState             string                    `json:"room_state"`
	CurrentMatchID        string                    `json:"current_match_id"`
	Members               []RoomMemberState         `json:"members"`
	LocalPlayerID         string                    `json:"local_player_id"`
	OwnerID               string                    `json:"owner_id"`
	MaxPlayers            int                       `json:"max_players"`
	PresetID              string                    `json:"preset_id"`
	ModeID                string                    `json:"mode_id"`
	ModeLocked            bool                      `json:"mode_locked"`
	StartingLives         int                       `json:"starting_lives"`
	InfiniteLives         bool                      `json:"infinite_lives"`
	TargetScore           int                       `json:"target_score"`
	TeamStructure         string                    `json:"team_structure"`
	TeamAssignmentMode    string                    `json:"team_assignment_mode"`
	TeamCount             int                       `json:"team_count"`
	TeamAssignmentsLocked bool                      `json:"team_assignments_locked"`
	BuildOptions          EligibleBuildOptionsState `json:"build_options"`
	LoadoutSelection      LoadoutSelectionState     `json:"loadout_selection"`
	MatchResult           RoomMatchResultSummary    `json:"match_result"`
}

type RoomStateChanged struct {
	Type      string `json:"type"`
	RoomCode  string `json:"room_code"`
	RoomState string `json:"room_state"`
}

type RoomError struct {
	Type      string `json:"type"`
	TraceID   string `json:"trace_id"`
	ErrorCode string `json:"error_code"`
	Message   string `json:"message"`
}

type EventState struct {
	Type         string  `json:"type"`
	PlayerID     string  `json:"player_id"`
	Lives        int     `json:"lives"`
	RespawnDelay float64 `json:"respawn_delay"`
	X            float64 `json:"x"`
	Y            float64 `json:"y"`
	PickupID     string  `json:"pickup_id"`
	PickupType   string  `json:"pickup_type"`
	SourceType   string  `json:"source_type"`
	SourceID     string  `json:"source_id"`
	TableID      string  `json:"table_id"`
	LivesAfter   int     `json:"lives_after"`
	EffectType   string  `json:"effect_type"`
	Amount       int     `json:"amount"`
}

type PlayerPauseState struct {
	Type     string `json:"type"`
	PlayerID string `json:"player_id"`
	Paused   bool   `json:"paused"`
}

type PlayerSessionState struct {
	ID                  string  `json:"id"`
	ShipType            string  `json:"ship_type"`
	Score               int     `json:"score"`
	Lives               int     `json:"lives"`
	RespawnCooldown     float64 `json:"respawn_cooldown"`
	PrimaryWeaponID     string  `json:"primary_weapon_id"`
	PrimaryAmmoPolicy   string  `json:"primary_ammo_policy"`
	SecondaryWeaponID   string  `json:"secondary_weapon_id"`
	SecondaryAmmoPolicy string  `json:"secondary_ammo_policy"`
	MaxHealth           int     `json:"max_health"`
	MaxShields          int     `json:"max_shields"`
	ShieldModuleID      string  `json:"shield_module_id"`
	ArmorModuleID       string  `json:"armor_module_id"`
	EngineModuleID      string  `json:"engine_module_id"`
	UtilityModuleID     string  `json:"utility_module_id"`
	SpawnX              float64 `json:"spawn_x"`
	SpawnY              float64 `json:"spawn_y"`
}

type PickupState struct {
	ID              string  `json:"id"`
	Type            string  `json:"type"`
	PickupClass     string  `json:"pickup_class"`
	X               float64 `json:"x"`
	Y               float64 `json:"y"`
	Health          int     `json:"health"`
	AgeSeconds      float64 `json:"age_seconds"`
	LifespanSeconds float64 `json:"lifespan_seconds"`
}

type WebRTCOffer struct {
	Type            string `json:"type"`
	DescriptionType string `json:"description_type"`
	Sdp             string `json:"sdp"`
}

type WebRTCAnswer struct {
	Type            string `json:"type"`
	DescriptionType string `json:"description_type"`
	Sdp             string `json:"sdp"`
}

type WebRTCIceCandidate struct {
	Type  string `json:"type"`
	Media string `json:"media"`
	Index int    `json:"index"`
	Name  string `json:"name"`
}

type WebRTCReady struct {
	Type         string `json:"type"`
	ChannelLabel string `json:"channel_label"`
	ChannelID    int    `json:"channel_id"`
}

type WebRTCSmoke struct {
	Type    string `json:"type"`
	SmokeID string `json:"smoke_id"`
	Origin  string `json:"origin"`
	Message string `json:"message"`
}

type WebRTCFailed struct {
	Type      string `json:"type"`
	ErrorCode string `json:"error_code"`
	Message   string `json:"message"`
}
