// Code generated by tools/data_sync/main.py; DO NOT EDIT.
package game

import entities "github.com/Lokee86/space-rocks/server/internal/game/entities"

const (
	PacketTypeInput                    = "input"
	PacketTypeClientConfig             = "client_config"
	PacketTypeState                    = "state"
	PacketTypeBulletBlast              = "bullet_blast"
	PacketTypeShipDeath                = "ship_death"
	PacketTypeRespawn                  = "respawn"
	PacketTypePauseRequest             = "pause_request"
	PacketTypePlayerPauseState         = "player_pause_state"
	PacketTypeToggleDebugInvincible    = "toggle_debug_invincible"
	PacketTypeToggleDebugInfiniteLives = "toggle_debug_infinite_lives"
	PacketTypeToggleDebugFreezeWorld   = "toggle_debug_freeze_world"
	PacketTypeToggleDebugFreezePlayer  = "toggle_debug_freeze_player"
	PacketTypeCreateRoomRequest        = "create_room_request"
	PacketTypeJoinRoomRequest          = "join_room_request"
	PacketTypeLeaveRoomRequest         = "leave_room_request"
	PacketTypeSetReadyRequest          = "set_ready_request"
	PacketTypeStartGameRequest         = "start_game_request"
	PacketTypeStartSinglePlayerRequest = "start_single_player_request"
	PacketTypeReturnToLobbyRequest     = "return_to_lobby_request"
	PacketTypeRoomSnapshot             = "room_snapshot"
	PacketTypeRoomStateChanged         = "room_state_changed"
	PacketTypeRoomError                = "room_error"
)

type ClientPacket struct {
	Type     string                `json:"type"`
	Input    entities.InputState   `json:"input"`
	Config   entities.ClientConfig `json:"config"`
	RoomCode string                `json:"room_code"`
	Ready    bool                  `json:"ready"`
}

type CreateRoomRequest struct {
	Type string `json:"type"`
}

type JoinRoomRequest struct {
	Type     string `json:"type"`
	RoomCode string `json:"room_code"`
}

type LeaveRoomRequest struct {
	Type string `json:"type"`
}

type SetReadyRequest struct {
	Type  string `json:"type"`
	Ready bool   `json:"ready"`
}

type StartGameRequest struct {
	Type string `json:"type"`
}

type StartSinglePlayerRequest struct {
	Type string `json:"type"`
}

type ReturnToLobbyRequest struct {
	Type string `json:"type"`
}

type RoomMemberState struct {
	MemberID  string `json:"member_id"`
	PlayerID  string `json:"player_id"`
	Ready     bool   `json:"ready"`
	Connected bool   `json:"connected"`
}

type RoomSnapshot struct {
	Type          string            `json:"type"`
	RoomCode      string            `json:"room_code"`
	RoomState     string            `json:"room_state"`
	Members       []RoomMemberState `json:"members"`
	LocalMemberID string            `json:"local_member_id"`
	LocalPlayerID string            `json:"local_player_id"`
	OwnerID       string            `json:"owner_id"`
	MaxPlayers    int               `json:"max_players"`
}

type RoomStateChanged struct {
	Type      string `json:"type"`
	RoomCode  string `json:"room_code"`
	RoomState string `json:"room_state"`
}

type RoomError struct {
	Type      string `json:"type"`
	ErrorCode string `json:"error_code"`
	Message   string `json:"message"`
}

type EventState struct {
	Type         string  `json:"type"`
	PlayerID     string  `json:"player_id"`
	Lives        int     `json:"lives"`
	RespawnDelay float64 `json:"respawn_delay"`
	X            float64 `json:"x"`
	Y            float64 `json:"y"`
}

type DebugStatus struct {
	Invincible    bool `json:"invincible"`
	InfiniteLives bool `json:"infinite_lives"`
	WorldFrozen   bool `json:"world_frozen"`
	PlayerFrozen  bool `json:"player_frozen"`
}

type PlayerPauseState struct {
	Type     string `json:"type"`
	PlayerID string `json:"player_id"`
	Paused   bool   `json:"paused"`
}

type StatePacket struct {
	Type            string                            `json:"type"`
	SelfID          string                            `json:"self_id"`
	Lives           int                               `json:"lives"`
	DebugStatus     DebugStatus                       `json:"debug_status"`
	Players         map[string]entities.ShipState     `json:"players"`
	PlayerLifecycle map[string]string                 `json:"player_lifecycle"`
	Bullets         map[string]entities.BulletState   `json:"bullets"`
	Asteroids       map[string]entities.AsteroidState `json:"asteroids"`
	Events          []EventState                      `json:"events"`
}
