// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicHomepage } from "./plasmic/space_rocks_devlog/PlasmicHomepage";
import type { DefaultHomepageProps } from "./plasmic/space_rocks_devlog/PlasmicHomepage";
import type {
  HomepageContent,
  HomepageMediaKind,
} from "../content/homepageContent";
import { normalizeHomepageContent } from "../content/homepageContent";

// Your component props start with props for variants and slots you defined
// in Plasmic, but you can add more here, like event handlers that you can
// attach to named nodes in your component.
//
// If you don't want to expose certain variants or slots as a prop, you can use
// Omit to hide them:
//
// interface HomepageProps extends Omit<DefaultHomepageProps, "hideProps1"|"hideProp2"> {
//   // etc.
// }
//
// You can also stop extending from DefaultHomepageProps altogether and have
// total control over the props for your component.
export interface HomepageProps extends DefaultHomepageProps {
  content?: Partial<HomepageContent>;
}

function getMediaFrameProps(
  mediaKind: HomepageMediaKind,
  images: string[],
  youtubeUrl: string,
  mediaAlt: string,
) {
  if (mediaKind === "images") {
    return {
      mediaMode: "imageList" as const,
      imageItems: images,
      alt: mediaAlt,
      youtubeUrl: undefined,
    };
  }

  if (mediaKind === "youtube") {
    return {
      youtubeUrl,
      youtubeTitle: mediaAlt,
      alt: mediaAlt,
      mediaMode: undefined,
      imageItems: [],
    };
  }

  return {
    imageItems: [],
    youtubeUrl: undefined,
  };
}

function Homepage_(props: HomepageProps, _ref: React.ForwardedRef<unknown>) {
  // Use PlasmicHomepage to render this component as it was
  // designed in Plasmic, by activating the appropriate variants,
  // attaching the appropriate event handlers, etc.  You
  // can also install whatever React hooks you need here to manage state or
  // fetch data.
  //
  // Props you can pass into PlasmicHomepage are:
  // 1. Variants you want to activate,
  // 2. Contents for slots you want to fill,
  // 3. Overrides for any named node in the component to attach behavior and data,
  // 4. Props to set on the root node.
  //
  // By default, we are just piping all HomepageProps here, but feel free
  // to do whatever works for you.

  const content = normalizeHomepageContent(props.content ?? {});

  return (
    <PlasmicHomepage
      {...props}
      heroLine1Media={{ children: content.heroLine1 }}
      heroLine1Desktop={{ children: content.heroLine1 }}
      heroLine2Media={{ children: content.heroLine2 }}
      heroLine2Desktop={{ children: content.heroLine2 }}
      heroLine3Media={{ children: content.heroLine3 }}
      heroLine3Desktop={{ children: content.heroLine3 }}
      heroMediaFrame={getMediaFrameProps(
        content.heroMediaKind,
        content.heroImages,
        content.heroYoutubeUrl,
        content.heroMediaAlt,
      )}
      articleLabel={{ children: content.articleLabel }}
      articleTitle={{ children: content.articleTitle }}
      introText={{ children: content.intro }}
      articleMediaFrame={getMediaFrameProps(
        content.articleMediaKind,
        content.articleImages,
        content.articleYoutubeUrl,
        content.articleMediaAlt,
      )}
      whatChangedText={{ children: content.whatChanged }}
      calloutText={{ children: content.callout }}
      whatsNextText={{ children: content.whatsNext }}
      finishedBody={{ children: content.finishedBody }}
      nowBody={{ children: content.nowBody }}
      comingUpBody={{ children: content.comingUpBody }}
      utilityText={{ children: content.utilityText }}
      finePrint={{ children: content.finePrint }}
    />
  );
}

const Homepage = React.forwardRef(Homepage_);
export default Homepage;
