extends RefCounted

const SERVER_TICK_RATE := 60

const PLAYER_ROTATION_SPEED := 4.0
const PLAYER_THRUST_FORCE := 1000.0
const PLAYER_MAX_SPEED := 1500.0
const PLAYER_DAMPING := 0.98

const BACKGROUND_PARALLAX := 0.25
const FOREGROUND_BACKGROUND_PARALLAX := 0.45
const FOREGROUND_BACKGROUND_OFFSET := Vector2(480.0, 270.0)
const PLAYER_INTERPOLATION_SPEED := 18.0

const ASTEROID_SPAWN_INTERVAL := 3.0
const ASTEROID_SPAWN_MARGIN := 160.0
const ASTEROID_DESPAWN_MARGIN := 320.0
const ASTEROID_MIN_SPEED := 90.0
const ASTEROID_MAX_SPEED := 170.0
const ASTEROID_SIZE_SCALE := 0.125
const ASTEROID_AIM_RANDOMNESS_DEGREES := 30.0
