# Code generated by tools/scripts/generate_packets.py; DO NOT EDIT.
extends RefCounted

const TYPE_INPUT := "input"
const TYPE_CLIENT_CONFIG := "client_config"
const TYPE_STATE := "state"
const TYPE_BULLET_BLAST := "bullet_blast"
const TYPE_SHIP_DEATH := "ship_death"
const TYPE_RESPAWN := "respawn"
const TYPE_PAUSE_PLAYER := "pause_player"
const TYPE_RESUME_PLAYER := "resume_player"
const TYPE_TOGGLE_DEBUG_INVINCIBLE := "toggle_debug_invincible"
const TYPE_TOGGLE_DEBUG_INFINITE_LIVES := "toggle_debug_infinite_lives"

const FIELD_ASTEROIDS := "asteroids"
const FIELD_BACK := "back"
const FIELD_BULLETS := "bullets"
const FIELD_CONFIG := "config"
const FIELD_EVENTS := "events"
const FIELD_FORWARD := "forward"
const FIELD_ID := "id"
const FIELD_INPUT := "input"
const FIELD_LEFT := "left"
const FIELD_LIVES := "lives"
const FIELD_OWNER_ID := "owner_id"
const FIELD_PAUSED := "paused"
const FIELD_PLAYER_ID := "player_id"
const FIELD_PLAYERS := "players"
const FIELD_RESPAWN_DELAY := "respawn_delay"
const FIELD_RIGHT := "right"
const FIELD_ROTATION := "rotation"
const FIELD_SCORE := "score"
const FIELD_SELF_ID := "self_id"
const FIELD_SHOOT := "shoot"
const FIELD_SIZE := "size"
const FIELD_TYPE := "type"
const FIELD_VARIANT := "variant"
const FIELD_VISIBLE_WORLD_HEIGHT := "visible_world_height"
const FIELD_VISIBLE_WORLD_WIDTH := "visible_world_width"
const FIELD_X := "x"
const FIELD_Y := "y"

static func input_packet(forward, back, right, left, shoot) -> Dictionary:
	var packet := {}
	packet[FIELD_TYPE] = TYPE_INPUT
	var packet_input := {}
	packet_input[FIELD_FORWARD] = forward
	packet_input[FIELD_BACK] = back
	packet_input[FIELD_RIGHT] = right
	packet_input[FIELD_LEFT] = left
	packet_input[FIELD_SHOOT] = shoot
	packet[FIELD_INPUT] = packet_input
	return packet

static func respawn_packet() -> Dictionary:
	var packet := {}
	packet[FIELD_TYPE] = TYPE_RESPAWN
	return packet

static func pause_player_packet() -> Dictionary:
	var packet := {}
	packet[FIELD_TYPE] = "pause_player"
	return packet

static func resume_player_packet() -> Dictionary:
	var packet := {}
	packet[FIELD_TYPE] = "resume_player"
	return packet

static func toggle_debug_invincible_packet() -> Dictionary:
	var packet := {}
	packet[FIELD_TYPE] = "toggle_debug_invincible"
	return packet

static func toggle_debug_infinite_lives_packet() -> Dictionary:
	var packet := {}
	packet[FIELD_TYPE] = "toggle_debug_infinite_lives"
	return packet

static func client_config_packet(visible_world_width, visible_world_height) -> Dictionary:
	var packet := {}
	packet[FIELD_TYPE] = TYPE_CLIENT_CONFIG
	var packet_config := {}
	packet_config[FIELD_VISIBLE_WORLD_WIDTH] = visible_world_width
	packet_config[FIELD_VISIBLE_WORLD_HEIGHT] = visible_world_height
	packet[FIELD_CONFIG] = packet_config
	return packet
