[[structs]]
id = "DebugStatus"

[[structs.fields]]
name = "invincible"
json = "invincible"
type = "bool"

[[structs.fields]]
name = "infinite_lives"
go_name = "InfiniteLives"
json = "infinite_lives"
type = "bool"

[[structs.fields]]
name = "world_frozen"
go_name = "WorldFrozen"
json = "world_frozen"
type = "bool"

[[structs.fields]]
name = "player_frozen"
go_name = "PlayerFrozen"
json = "player_frozen"
type = "bool"

[[structs]]
id = "DebugCommand"

[[structs.fields]]
name = "type"
json = "type"
type = "string"

[[structs.fields]]
name = "target_player_id"
go_name = "TargetPlayerID"
json = "target_player_id"
type = "string"

[[structs.fields]]
name = "entity_type"
json = "entity_type"
type = "string"

[[structs.fields]]
name = "x"
json = "x"
type = "float"

[[structs.fields]]
name = "y"
json = "y"
type = "float"

[[structs.fields]]
name = "has_direction"
go_name = "HasDirection"
json = "has_direction"
type = "bool"

[[structs.fields]]
name = "direction_x"
go_name = "DirectionX"
json = "direction_x"
type = "float"

[[structs.fields]]
name = "direction_y"
go_name = "DirectionY"
json = "direction_y"
type = "float"

[[packet_types]]
id = "toggle_debug_invincible"
value = "toggle_debug_invincible"

[[packet_types]]
id = "toggle_debug_infinite_lives"
value = "toggle_debug_infinite_lives"

[[packet_types]]
id = "toggle_debug_freeze_world"
value = "toggle_debug_freeze_world"

[[packet_types]]
id = "toggle_debug_freeze_player"
value = "toggle_debug_freeze_player"

[[packet_types]]
id = "debug_kill_player"
value = "debug_kill_player"

[[packet_types]]
id = "debug_spawn_entity"
value = "debug_spawn_entity"

[[packet_types]]
id = "debug_respawn_player"
value = "debug_respawn_player"

[[builders]]
id = "toggle_debug_invincible_packet"

[builders.body]
type = "toggle_debug_invincible"

[[builders]]
id = "toggle_debug_invincible_target_player_packet"
args = ["target_player_id"]

[builders.body]
type = "toggle_debug_invincible"
target_player_id = "$target_player_id"

[[builders]]
id = "toggle_debug_infinite_lives_packet"

[builders.body]
type = "toggle_debug_infinite_lives"

[[builders]]
id = "toggle_debug_infinite_lives_target_player_packet"
args = ["target_player_id"]

[builders.body]
type = "toggle_debug_infinite_lives"
target_player_id = "$target_player_id"

[[builders]]
id = "toggle_debug_freeze_world_packet"

[builders.body]
type = "toggle_debug_freeze_world"

[[builders]]
id = "toggle_debug_freeze_player_packet"

[builders.body]
type = "toggle_debug_freeze_player"

[[builders]]
id = "toggle_debug_freeze_player_target_player_packet"
args = ["target_player_id"]

[builders.body]
type = "toggle_debug_freeze_player"
target_player_id = "$target_player_id"

[[builders]]
id = "debug_kill_player_packet"

[builders.body]
type = "debug_kill_player"

[[builders]]
id = "debug_kill_target_player_packet"
args = ["target_player_id"]

[builders.body]
type = "debug_kill_player"
target_player_id = "$target_player_id"
