/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uNJepqX5kmDcUn9dDb3UVD

import { createUseGlobalVariants } from "@plasmicapp/react-web";

import { useScreenVariants as useScreenVariantst0MnnasaXtR } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: t0mnnasaXT_R/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantst0MnnasaXtR
});
