/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uNJepqX5kmDcUn9dDb3UVD
// Component: I3TbBX3qgAwU

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { CrtMediaFrame } from "@/src/components/media/CrtMediaFrame"; // plasmic-import: S_Lqfgq4vzxV/codeComponent
import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uNJepqX5kmDcUn9dDb3UVD/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: uNJepqX5kmDcUn9dDb3UVD/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import "./plasmic.css"; // plasmic-import: uNJepqX5kmDcUn9dDb3UVD/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: I3TbBX3qgAwU/css

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "Devlog Archive",

    openGraph: {
      title: "Devlog Archive"
    },
    twitter: {
      card: "summary" as const,
      title: "Devlog Archive"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicHomepage__VariantMembers = {};
export type PlasmicHomepage__VariantsArgs = {};
type VariantPropType = keyof PlasmicHomepage__VariantsArgs;
export const PlasmicHomepage__VariantProps = new Array<VariantPropType>();

export type PlasmicHomepage__ArgsType = {};
type ArgPropType = keyof PlasmicHomepage__ArgsType;
export const PlasmicHomepage__ArgProps = new Array<ArgPropType>();

export type PlasmicHomepage__OverridesType = {
  root?: Flex__<"main">;
  header?: Flex__<"header">;
  nav?: Flex__<"nav">;
  hero?: Flex__<"section">;
  screenStack?: Flex__<"div">;
  heroMediaFrame?: Flex__<typeof CrtMediaFrame>;
  heroLine1Media?: Flex__<"span">;
  heroLine2Media?: Flex__<"span">;
  heroLine3Media?: Flex__<"span">;
  heroLine1Desktop?: Flex__<"span">;
  heroLine2Desktop?: Flex__<"span">;
  heroLine3Desktop?: Flex__<"span">;
  article?: Flex__<"article">;
  articleLabel?: Flex__<"span">;
  articleTitle?: Flex__<"h1">;
  introText?: Flex__<"p">;
  screenStack2?: Flex__<"div">;
  articleMediaFrame?: Flex__<typeof CrtMediaFrame>;
  whatChangedText?: Flex__<"p">;
  blockquote?: Flex__<"blockquote">;
  calloutText?: Flex__<"span">;
  whatsNextText?: Flex__<"p">;
  aside?: Flex__<"aside">;
  finishedBody?: Flex__<"p">;
  nowBody?: Flex__<"p">;
  comingUpBody?: Flex__<"p">;
  utilityText?: Flex__<"p">;
  footer?: Flex__<"footer">;
  finePrint?: Flex__<"span">;
};

export interface DefaultHomepageProps {
  className?: string;
}

const $$ = {};

function PlasmicHomepage__RenderFunc(props: {
  variants: PlasmicHomepage__VariantsArgs;
  args: PlasmicHomepage__ArgsType;
  overrides: PlasmicHomepage__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <div className={"plasmic_page_wrapper"}>
        <main
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_uNJepqX5kmDcUn9dDb3UVD",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root
          )}
          id={"uW6XQJEMGRlw"}
        >
          <header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("all", sty.header)}
            id={"Lt3Sxj5b4ANm"}
            style={{
              backgroundImage: "none",
              backgroundSize: "100% 100%",
              backgroundPosition: "center center",
              backgroundRepeat: "no-repeat",
              borderImageSource: "none",
              borderImageSlice: "0",
              borderImageWidth: "0",
              borderImageRepeat: "stretch"
            }}
          >
            <div
              className={classNames("all", sty.freeBox__dgPdn)}
              id={"j3R8Eb4zkpzk"}
              style={
                hasVariant(globalVariants, "screen", "tablet")
                  ? {
                      borderImageSource: "none",
                      borderImageSlice: "0",
                      borderImageWidth: "0",
                      borderImageRepeat: "stretch",
                      backgroundImage: "url('/assets/ui/nav_bar.png')",
                      backgroundSize: "100% 100%",
                      backgroundPosition: "center center",
                      backgroundRepeat: "no-repeat"
                    }
                  : {
                      borderImageSource: 'url("/assets/ui/nav_bar.png")',
                      borderImageSlice: "1 37 fill",
                      borderImageWidth: "0 37px",
                      borderImageRepeat: "stretch"
                    }
              }
            />

            <div
              className={classNames("all", sty.freeBox__cCgxs)}
              id={"xDSDd6Ys-1-a"}
              style={{
                filter: "drop-shadow(rgba(255, 47, 67, 0.55) 0px 0px 6px)"
              }}
            >
              <span
                className={classNames(
                  "all",
                  "span",
                  "span__uNJep",
                  sty.span___5TEwn
                )}
                id={"Nj6kH7kOTZa1"}
              >
                <PlasmicImg__
                  alt={"Space"}
                  className={classNames(sty.img__v0Nxc)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "23px"
                      : "27px"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  id={"8_vwG4m979nZ"}
                  loading={"lazy"}
                  src={"/assets/ui/title_space.png"}
                />
              </span>
              <span
                className={classNames(
                  "all",
                  "span",
                  "span__uNJep",
                  sty.span___36Bli
                )}
                id={"QBJ1gzsIIPl-"}
              >
                <PlasmicImg__
                  alt={"Rocks"}
                  className={classNames(sty.img__otCxx)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "25px"
                      : "29px"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  id={"BlQXx-nQqG_H"}
                  loading={"lazy"}
                  src={"/assets/ui/title_rocks.png"}
                />
              </span>
            </div>
            <nav
              data-plasmic-name={"nav"}
              data-plasmic-override={overrides.nav}
              className={classNames("all", sty.nav)}
              id={"1T0XsvhpLi9A"}
              style={{ textShadow: "rgba(0, 229, 255, 0.65) 0px 0px 10px" }}
            >
              <PlasmicLink__
                className={classNames("all", "a", "a__uNJep", sty.link__jyTn4)}
                href={"/"}
                id={"9d3FT6XjLgDj"}
                platform={"react"}
              >
                <span
                  className={classNames(
                    "all",
                    "span",
                    "span__uNJep",
                    "__wab_text",
                    sty.span__b4VVy
                  )}
                >
                  {"Home"}
                </span>
              </PlasmicLink__>
              <PlasmicLink__
                className={classNames("all", "a", "a__uNJep", sty.link__isIz)}
                href={"/archive/"}
                id={"rW8um3abfDUl"}
                platform={"react"}
              >
                <span
                  className={classNames(
                    "all",
                    "span",
                    "span__uNJep",
                    "__wab_text",
                    sty.span__plWgD
                  )}
                  id={"DQFgbrwD_vap"}
                >
                  {"Archive"}
                </span>
              </PlasmicLink__>
              <PlasmicLink__
                className={classNames("all", "a", "a__uNJep", sty.link__t6Ksv)}
                href={"https://github.com/Lokee86/space-rocks"}
                id={"gbV0TczdRWrh"}
                platform={"react"}
              >
                <span
                  className={classNames(
                    "all",
                    "span",
                    "span__uNJep",
                    "__wab_text",
                    sty.span__yfF9T
                  )}
                  id={"Qwxrm5UGzmw5"}
                >
                  {"GitHub"}
                </span>
              </PlasmicLink__>
            </nav>
          </header>
          <div
            className={classNames("all", sty.freeBox__ket3A)}
            id={"gMSVNH-NZasS"}
          >
            <section
              data-plasmic-name={"hero"}
              data-plasmic-override={overrides.hero}
              className={classNames("all", sty.hero)}
              id={"k3Lfx4O4BCjs"}
              style={
                hasVariant(globalVariants, "screen", "mobile")
                  ? {
                      gridTemplateColumns: "1fr",
                      gridAutoRows: "auto",
                      justifyItems: "center"
                    }
                  : hasVariant(globalVariants, "screen", "tablet")
                    ? {
                        backgroundPosition: "center top",
                        backgroundSize: "cover",
                        gridTemplateColumns:
                          "repeat(auto-fit, minmax(max(225px, calc((100% - 15px) / 2)), 1fr))",
                        justifyItems: "center"
                      }
                    : {
                        backgroundPosition: "right center",
                        backgroundSize: "cover"
                      }
              }
            >
              <div
                data-plasmic-name={"screenStack"}
                data-plasmic-override={overrides.screenStack}
                className={classNames("all", sty.screenStack)}
                id={"J8HFxhDbsPA3"}
                style={
                  hasVariant(globalVariants, "screen", "tablet")
                    ? {
                        order: "1",
                        gridColumn: "1 / -1",
                        justifySelf: "center"
                      }
                    : undefined
                }
              >
                <CrtMediaFrame
                  data-plasmic-name={"heroMediaFrame"}
                  data-plasmic-override={overrides.heroMediaFrame}
                  alt={""}
                  animationSpeed={1}
                  aspectRatio={"16 / 9"}
                  autoAdvanceMs={5000}
                  baseColor={"#020617"}
                  className={classNames("__wab_instance", sty.heroMediaFrame)}
                  disabledControls={""}
                  edgeCornerGlowPower={2.2}
                  edgeCornerGlowWidth={0.055}
                  edgeGlowSoftness={0.018}
                  edgeGlowStrength={0.08}
                  edgeGlowWidth={0.01}
                  effectCutoff={0.018}
                  effectGain={1.25}
                  fit={"cover"}
                  flickerSecondaryStrength={0.35}
                  flickerSpeed={18}
                  flickerSpeedVariance={0.55}
                  flickerStrength={0.025}
                  flickerVarianceSpeed={1.35}
                  freezeShaderTime={false}
                  glowColor={"#00e5ff"}
                  horizontalShimmerCount={42}
                  horizontalShimmerSpeed={1.8}
                  horizontalShimmerStrength={0.055}
                  imageItems={""}
                  initialIndex={0}
                  lineJitterStrength={0.0012}
                  rollDuration={1.2}
                  rollHorizontalVariation={0.15}
                  rollInterval={5}
                  rollSpeed={1}
                  rollStrength={0.08}
                  rollWidth={0.1}
                  scanlineBreakupCutoff={0.46}
                  scanlineBreakupSegments={36}
                  scanlineBreakupSoftness={0.18}
                  scanlineBreakupStrength={0.16}
                  scanlineColor={"#7dd3fc"}
                  scanlineCount={480}
                  scanlineHardness={1.65}
                  scanlineLineVarianceStrength={0.08}
                  scanlineStrength={0.24}
                  screenInsetBottom={11}
                  screenInsetLeft={2}
                  screenInsetRight={1}
                  screenInsetTop={8}
                  seekSeconds={10}
                  shaderDebug={false}
                  shaderEnabled={true}
                  showControls={true}
                  tint={"cyan"}
                  videoSrc={""}
                  vignetteEdgeBypassStrength={1}
                  vignetteEdgeBypassWidth={0.035}
                  vignetteStrength={0.24}
                  waveFineScale={210}
                  waveMediumScale={63}
                  waveSlowScale={18}
                  waveSpeed={1}
                  waveStrength={1}
                />

                {(
                  hasVariant(globalVariants, "screen", "mobile")
                    ? true
                    : hasVariant(globalVariants, "screen", "tablet")
                      ? true
                      : false
                ) ? (
                  <div
                    className={classNames("all", sty.freeBox___1FnmC)}
                    id={"8byqGt8dEJls"}
                    style={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? {
                            order: "2",
                            gridColumn: "1 / -1",
                            justifySelf: "center",
                            textShadow:
                              "rgb(255, 0, 0) 2px 0px 0px, rgb(255, 0, 0) -2px 0px 0px, rgb(255, 0, 0) 0px 2px 0px, rgb(255, 0, 0) 0px -2px 0px, rgba(255, 47, 67, 0.78) 0px 0px 10px"
                          }
                        : hasVariant(globalVariants, "screen", "tablet")
                          ? {
                              order: "2",
                              textShadow:
                                "rgb(255, 0, 0) 2px 0px 0px, rgb(255, 0, 0) -2px 0px 0px, rgb(255, 0, 0) 0px 2px 0px, rgb(255, 0, 0) 0px -2px 0px, rgba(255, 47, 67, 0.78) 0px 0px 10px",
                              gridColumn: "auto",
                              justifySelf: "center"
                            }
                          : {
                              textShadow:
                                "rgb(255, 0, 0) 2px 0px 0px, rgb(255, 0, 0) -2px 0px 0px, rgb(255, 0, 0) 0px 2px 0px, rgb(255, 0, 0) 0px -2px 0px, rgba(255, 47, 67, 0.78) 0px 0px 10px",
                              order: "0",
                              gridColumn: "auto",
                              justifySelf: "auto"
                            }
                    }
                  >
                    <span
                      className={classNames(
                        "all",
                        "span",
                        "span__uNJep",
                        sty.span__nGAzp
                      )}
                      id={"JQUEp_z-buj3"}
                    >
                      <span
                        data-plasmic-name={"heroLine1Media"}
                        data-plasmic-override={overrides.heroLine1Media}
                        className={classNames(
                          "all",
                          "span",
                          "span__uNJep",
                          "__wab_text",
                          sty.heroLine1Media
                        )}
                        id={"NzSf9Y9fVjp8"}
                      >
                        {"Lorem ipsum dolor"}
                      </span>
                    </span>
                    <span
                      className={classNames(
                        "all",
                        "span",
                        "span__uNJep",
                        sty.span__iHKfh
                      )}
                      id={"VuOMS-AA1yAs"}
                    >
                      <span
                        data-plasmic-name={"heroLine2Media"}
                        data-plasmic-override={overrides.heroLine2Media}
                        className={classNames(
                          "all",
                          "span",
                          "span__uNJep",
                          "__wab_text",
                          sty.heroLine2Media
                        )}
                        id={"LeNRnq4QrpBe"}
                      >
                        {"sit amet, consectetur"}
                      </span>
                    </span>
                    <span
                      className={classNames(
                        "all",
                        "span",
                        "span__uNJep",
                        sty.span__gxw3T
                      )}
                      id={"Ihv6qwVFlaQT"}
                    >
                      <span
                        data-plasmic-name={"heroLine3Media"}
                        data-plasmic-override={overrides.heroLine3Media}
                        className={classNames(
                          "all",
                          "span",
                          "span__uNJep",
                          "__wab_text",
                          sty.heroLine3Media
                        )}
                        id={"D9CgjTnY0hm0"}
                      >
                        {"adipiscing elit, sed do"}
                      </span>
                    </span>
                  </div>
                ) : null}
                {(
                  hasVariant(globalVariants, "screen", "mobile")
                    ? true
                    : hasVariant(globalVariants, "screen", "tablet")
                      ? true
                      : false
                ) ? (
                  <PlasmicImg__
                    alt={"Space Rocks"}
                    className={classNames(sty.img__hKbjp)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "tablet")
                        ? "auto"
                        : "auto"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "100%"
                        : hasVariant(globalVariants, "screen", "tablet")
                          ? "100%"
                          : "30%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? "min(320px, 100%)"
                        : hasVariant(globalVariants, "screen", "tablet")
                          ? "min(320px, 100%)"
                          : "min(340px, 30%)"
                    }
                    id={"_sxn1Y_NLVgG"}
                    loading={"lazy"}
                    src={"/assets/ui/title.png"}
                    style={
                      hasVariant(globalVariants, "screen", "mobile")
                        ? {
                            order: "3",
                            gridColumn: "1 / -1",
                            justifySelf: "center"
                          }
                        : hasVariant(globalVariants, "screen", "tablet")
                          ? {
                              order: "3",
                              gridColumn: "auto",
                              justifySelf: "center"
                            }
                          : {
                              filter: "none",
                              order: "0",
                              gridColumn: "auto",
                              justifySelf: "auto"
                            }
                    }
                  />
                ) : null}
              </div>
              <div
                className={classNames("all", sty.freeBox__wR5Os)}
                id={"8byqGt8dEJls"}
                style={
                  hasVariant(globalVariants, "screen", "mobile")
                    ? {
                        order: "2",
                        gridColumn: "1 / -1",
                        justifySelf: "center",
                        textShadow:
                          "rgb(255, 0, 0) 2px 0px 0px, rgb(255, 0, 0) -2px 0px 0px, rgb(255, 0, 0) 0px 2px 0px, rgb(255, 0, 0) 0px -2px 0px, rgba(255, 47, 67, 0.78) 0px 0px 10px"
                      }
                    : hasVariant(globalVariants, "screen", "tablet")
                      ? {
                          order: "2",
                          textShadow:
                            "rgb(255, 0, 0) 2px 0px 0px, rgb(255, 0, 0) -2px 0px 0px, rgb(255, 0, 0) 0px 2px 0px, rgb(255, 0, 0) 0px -2px 0px, rgba(255, 47, 67, 0.78) 0px 0px 10px",
                          gridColumn: "auto",
                          justifySelf: "center"
                        }
                      : {
                          textShadow:
                            "rgb(255, 0, 0) 2px 0px 0px, rgb(255, 0, 0) -2px 0px 0px, rgb(255, 0, 0) 0px 2px 0px, rgb(255, 0, 0) 0px -2px 0px, rgba(255, 47, 67, 0.78) 0px 0px 10px",
                          order: "0",
                          gridColumn: "auto",
                          justifySelf: "auto"
                        }
                }
              >
                <span
                  className={classNames(
                    "all",
                    "span",
                    "span__uNJep",
                    sty.span__xh1Fs
                  )}
                  id={"JQUEp_z-buj3"}
                >
                  <span
                    data-plasmic-name={"heroLine1Desktop"}
                    data-plasmic-override={overrides.heroLine1Desktop}
                    className={classNames(
                      "all",
                      "span",
                      "span__uNJep",
                      "__wab_text",
                      sty.heroLine1Desktop
                    )}
                    id={"NzSf9Y9fVjp8"}
                  >
                    {"Lorem ipsum dolor"}
                  </span>
                </span>
                <span
                  className={classNames(
                    "all",
                    "span",
                    "span__uNJep",
                    sty.span__tjK1R
                  )}
                  id={"VuOMS-AA1yAs"}
                >
                  <span
                    data-plasmic-name={"heroLine2Desktop"}
                    data-plasmic-override={overrides.heroLine2Desktop}
                    className={classNames(
                      "all",
                      "span",
                      "span__uNJep",
                      "__wab_text",
                      sty.heroLine2Desktop
                    )}
                    id={"LeNRnq4QrpBe"}
                  >
                    {"sit amet, consectetur"}
                  </span>
                </span>
                <span
                  className={classNames(
                    "all",
                    "span",
                    "span__uNJep",
                    sty.span__xr4Fm
                  )}
                  id={"Ihv6qwVFlaQT"}
                >
                  <span
                    data-plasmic-name={"heroLine3Desktop"}
                    data-plasmic-override={overrides.heroLine3Desktop}
                    className={classNames(
                      "all",
                      "span",
                      "span__uNJep",
                      "__wab_text",
                      sty.heroLine3Desktop
                    )}
                    id={"D9CgjTnY0hm0"}
                  >
                    {"adipiscing elit, sed do"}
                  </span>
                </span>
              </div>
              <PlasmicImg__
                alt={"Space Rocks"}
                className={classNames(sty.img__puIYz)}
                displayHeight={
                  hasVariant(globalVariants, "screen", "tablet")
                    ? "auto"
                    : "auto"
                }
                displayMaxHeight={"none"}
                displayMaxWidth={
                  hasVariant(globalVariants, "screen", "mobile")
                    ? "100%"
                    : hasVariant(globalVariants, "screen", "tablet")
                      ? "100%"
                      : "30%"
                }
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={
                  hasVariant(globalVariants, "screen", "mobile")
                    ? "min(320px, 100%)"
                    : hasVariant(globalVariants, "screen", "tablet")
                      ? "min(320px, 100%)"
                      : "min(340px, 30%)"
                }
                id={"_sxn1Y_NLVgG"}
                loading={"lazy"}
                src={"/assets/ui/title.png"}
                style={
                  hasVariant(globalVariants, "screen", "mobile")
                    ? {
                        order: "3",
                        gridColumn: "1 / -1",
                        justifySelf: "center"
                      }
                    : hasVariant(globalVariants, "screen", "tablet")
                      ? {
                          order: "3",
                          gridColumn: "auto",
                          justifySelf: "center"
                        }
                      : {
                          filter: "none",
                          order: "0",
                          gridColumn: "auto",
                          justifySelf: "auto"
                        }
                }
              />
            </section>
            <section
              className={classNames("all", sty.section___4BcfR)}
              id={"PBJ79k9JaqHy"}
              style={
                hasVariant(globalVariants, "screen", "tablet")
                  ? { gridTemplateColumns: "minmax(0, 1fr)" }
                  : { gridTemplateColumns: "minmax(0px, 1fr) 250px" }
              }
            >
              <article
                data-plasmic-name={"article"}
                data-plasmic-override={overrides.article}
                className={classNames("all", sty.article)}
                id={"VKe6otEBvVPa"}
              >
                <div
                  className={classNames("all", sty.freeBox__pNhK)}
                  id={"lyrSSAnBMjvn"}
                  style={{ mixBlendMode: "screen" }}
                />

                <div
                  className={classNames("all", sty.freeBox__xvdC)}
                  id={"-eKcTnjjhipn"}
                >
                  <div
                    className={classNames("all", sty.freeBox___5Iy)}
                    id={"2RDFfzp8Eh0J"}
                  >
                    <span
                      data-plasmic-name={"articleLabel"}
                      data-plasmic-override={overrides.articleLabel}
                      className={classNames(
                        "all",
                        "span",
                        "span__uNJep",
                        "__wab_text",
                        sty.articleLabel
                      )}
                      id={"d7Y2Thqs0Eze"}
                    >
                      {"Devlog Entry"}
                    </span>
                  </div>
                  <h1
                    data-plasmic-name={"articleTitle"}
                    data-plasmic-override={overrides.articleTitle}
                    className={classNames(
                      "all",
                      "h1",
                      "h1__uNJep",
                      "__wab_text",
                      sty.articleTitle
                    )}
                    id={"zjUo3Aobz4Hf"}
                  >
                    {"Lorem Ipsum Delor"}
                  </h1>
                  <p
                    data-plasmic-name={"introText"}
                    data-plasmic-override={overrides.introText}
                    className={classNames(
                      "all",
                      "p",
                      "p__uNJep",
                      "__wab_text",
                      sty.introText
                    )}
                    id={"2k_fW1gkoIiS"}
                  >
                    {
                      "Main article content goes here. This panel is the reusable devlog body area. Screenshots and clips can use framed media components inside the article flow."
                    }
                  </p>
                  <div
                    data-plasmic-name={"screenStack2"}
                    data-plasmic-override={overrides.screenStack2}
                    className={classNames("all", sty.screenStack2)}
                    id={"Fe-CSVAjzAup"}
                  >
                    <CrtMediaFrame
                      data-plasmic-name={"articleMediaFrame"}
                      data-plasmic-override={overrides.articleMediaFrame}
                      alt={""}
                      animationSpeed={1}
                      aspectRatio={"16 / 9"}
                      autoAdvanceMs={5000}
                      baseColor={"#020617"}
                      className={classNames(
                        "__wab_instance",
                        sty.articleMediaFrame
                      )}
                      disabledControls={""}
                      edgeCornerGlowPower={2.2}
                      edgeCornerGlowWidth={0.055}
                      edgeGlowSoftness={0.018}
                      edgeGlowStrength={0.08}
                      edgeGlowWidth={0.01}
                      effectCutoff={0.018}
                      effectGain={1.25}
                      fit={"cover"}
                      flickerSecondaryStrength={0.35}
                      flickerSpeed={18}
                      flickerSpeedVariance={0.55}
                      flickerStrength={0.025}
                      flickerVarianceSpeed={1.35}
                      freezeShaderTime={false}
                      glowColor={"#00e5ff"}
                      horizontalShimmerCount={42}
                      horizontalShimmerSpeed={1.8}
                      horizontalShimmerStrength={0.055}
                      imageItems={""}
                      initialIndex={0}
                      lineJitterStrength={0.0012}
                      rollDuration={1.2}
                      rollHorizontalVariation={0.15}
                      rollInterval={5}
                      rollSpeed={1}
                      rollStrength={0.08}
                      rollWidth={0.1}
                      scanlineBreakupCutoff={0.46}
                      scanlineBreakupSegments={36}
                      scanlineBreakupSoftness={0.18}
                      scanlineBreakupStrength={0.16}
                      scanlineColor={"#7dd3fc"}
                      scanlineCount={480}
                      scanlineHardness={1.65}
                      scanlineLineVarianceStrength={0.08}
                      scanlineStrength={0.24}
                      screenInsetBottom={11}
                      screenInsetLeft={2}
                      screenInsetRight={1}
                      screenInsetTop={8}
                      seekSeconds={10}
                      shaderDebug={false}
                      shaderEnabled={true}
                      showControls={true}
                      tint={"cyan"}
                      videoSrc={""}
                      vignetteEdgeBypassStrength={1}
                      vignetteEdgeBypassWidth={0.035}
                      vignetteStrength={0.24}
                      waveFineScale={210}
                      waveMediumScale={63}
                      waveSlowScale={18}
                      waveSpeed={1}
                      waveStrength={1}
                    />
                  </div>
                  <h2
                    className={classNames(
                      "all",
                      "h2",
                      "h2__uNJep",
                      "__wab_text",
                      sty.h2__in94K
                    )}
                    id={"Ae5U6wXArW_l"}
                  >
                    {"What changed"}
                  </h2>
                  <p
                    data-plasmic-name={"whatChangedText"}
                    data-plasmic-override={overrides.whatChangedText}
                    className={classNames(
                      "all",
                      "p",
                      "p__uNJep",
                      "__wab_text",
                      sty.whatChangedText
                    )}
                    id={"OEGT_uR78XFv"}
                  >
                    {
                      "Use this content panel for the current article. Body text, bullet lists, screenshots, GIFs, and comparison images all live here."
                    }
                  </p>
                  <blockquote
                    data-plasmic-name={"blockquote"}
                    data-plasmic-override={overrides.blockquote}
                    className={classNames("all", sty.blockquote)}
                    id={"yDJN7vxc91bA"}
                  >
                    <span
                      data-plasmic-name={"calloutText"}
                      data-plasmic-override={overrides.calloutText}
                      className={classNames(
                        "all",
                        "span",
                        "span__uNJep",
                        "__wab_text",
                        sty.calloutText
                      )}
                      id={"ksvrQbBLRcHG"}
                    >
                      {"Callout / quote / patch note highlight goes here."}
                    </span>
                  </blockquote>
                  <h2
                    className={classNames(
                      "all",
                      "h2",
                      "h2__uNJep",
                      "__wab_text",
                      sty.h2__vg9B
                    )}
                    id={"E0-KynfStX4T"}
                  >
                    {"What\u2019s next"}
                  </h2>
                  <p
                    data-plasmic-name={"whatsNextText"}
                    data-plasmic-override={overrides.whatsNextText}
                    className={classNames(
                      "all",
                      "p",
                      "p__uNJep",
                      "__wab_text",
                      sty.whatsNextText
                    )}
                    id={"FlNdghLeU55C"}
                  >
                    {"Next steps, rough roadmap, and developer notes go here."}
                  </p>
                </div>
              </article>
              <aside
                data-plasmic-name={"aside"}
                data-plasmic-override={overrides.aside}
                className={classNames("all", sty.aside)}
                id={"PVnadxe5IWfd"}
                style={
                  hasVariant(globalVariants, "screen", "tablet")
                    ? {
                        gridTemplateColumns:
                          "repeat(auto-fit, minmax(max(225px, calc((100% - 15px) / 2)), 1fr))",
                        containerType: "inline-size",
                        containerName: "sidebar-cards",
                        gridAutoRows: "auto",
                        justifyItems: "stretch"
                      }
                    : undefined
                }
              >
                <section
                  className={classNames("all", sty.section___4Lxpy)}
                  id={"pqZTrfwD_wAR"}
                  style={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? {
                          backgroundImage:
                            "linear-gradient(rgba(20,23,24,0.88), rgba(20,23,24,0.88)), url('/assets/ui/backgroun-fore.png')",
                          backgroundSize: "auto, cover",
                          backgroundPosition: "center center, center center",
                          backgroundRepeat: "repeat, no-repeat",
                          borderImageSource: "url('/assets/ui/card_frame.png')",
                          borderImageSlice: "78 58",
                          borderImageWidth: "42px",
                          borderImageRepeat: "stretch",
                          justifySelf: "stretch",
                          aspectRatio: "auto"
                        }
                      : {
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "center center",
                          backgroundRepeat: "repeat",
                          borderImageSource: "none",
                          borderImageSlice: "0",
                          borderImageWidth: "0",
                          borderImageRepeat: "stretch",
                          isolation: "isolate"
                        }
                  }
                >
                  <div
                    className={classNames("all", sty.freeBox__un5Q4)}
                    style={{
                      borderImageSource: 'url("/assets/ui/card_frame.png")',
                      borderImageSlice: "78 58",
                      borderImageWidth: "37px",
                      borderImageRepeat: "stretch"
                    }}
                  />

                  <div
                    className={classNames("all", sty.freeBox__vvgXp)}
                    style={{
                      backgroundImage:
                        'linear-gradient(rgba(20, 23, 24, 0.88), rgba(20, 23, 24, 0.88)), url("/assets/ui/backgroun-fore.png")',
                      backgroundSize: "auto, cover",
                      backgroundPosition: "center center, center center",
                      backgroundRepeat: "repeat, no-repeat"
                    }}
                  />

                  <div className={classNames("all", sty.freeBox__aJ8Qy)}>
                    <div
                      className={classNames("all", sty.freeBox__uodNb)}
                      style={{
                        textShadow: "rgba(0, 229, 255, 0.55) 0px 0px 8px"
                      }}
                    >
                      <span
                        className={classNames(
                          "all",
                          "span",
                          "span__uNJep",
                          "__wab_text",
                          sty.span__qlEz
                        )}
                      >
                        {"Finished"}
                      </span>
                    </div>
                    <div
                      className={classNames("all", sty.freeBox__n2Nr)}
                      style={{
                        textShadow: "rgba(255, 255, 255, 0.18) 0px 0px 6px"
                      }}
                    >
                      <span
                        className={classNames(
                          "all",
                          "span",
                          "span__uNJep",
                          "__wab_text",
                          sty.span__eKbhG
                        )}
                      >
                        {"Client V2"}
                      </span>
                    </div>
                    <p
                      data-plasmic-name={"finishedBody"}
                      data-plasmic-override={overrides.finishedBody}
                      className={classNames(
                        "all",
                        "p",
                        "p__uNJep",
                        "__wab_text",
                        sty.finishedBody
                      )}
                    >
                      {"Current client foundation."}
                    </p>
                  </div>
                </section>
                <section
                  className={classNames("all", sty.section__a4YtY)}
                  id={"QpB8MdHpq8c3"}
                  style={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? {
                          backgroundImage:
                            "linear-gradient(rgba(20,23,24,0.88), rgba(20,23,24,0.88)), url('/assets/ui/backgroun-fore.png')",
                          backgroundSize: "auto, cover",
                          backgroundPosition: "center center, center center",
                          backgroundRepeat: "repeat, no-repeat",
                          borderImageSource: "url('/assets/ui/card_frame.png')",
                          borderImageSlice: "78 58",
                          borderImageWidth: "42px",
                          borderImageRepeat: "stretch",
                          justifySelf: "stretch",
                          aspectRatio: "auto"
                        }
                      : {
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "center center",
                          backgroundRepeat: "repeat",
                          borderImageSource: "none",
                          borderImageSlice: "0",
                          borderImageWidth: "0",
                          borderImageRepeat: "stretch",
                          isolation: "isolate"
                        }
                  }
                >
                  <div
                    className={classNames("all", sty.freeBox__xhs6N)}
                    style={{
                      borderImageSource: 'url("/assets/ui/card_frame.png")',
                      borderImageSlice: "78 58",
                      borderImageWidth: "37px",
                      borderImageRepeat: "stretch"
                    }}
                  />

                  <div
                    className={classNames("all", sty.freeBox__aFdp)}
                    style={{
                      backgroundImage:
                        'linear-gradient(rgba(20, 23, 24, 0.88), rgba(20, 23, 24, 0.88)), url("/assets/ui/backgroun-fore.png")',
                      backgroundSize: "auto, cover",
                      backgroundPosition: "center center, center center",
                      backgroundRepeat: "repeat, no-repeat"
                    }}
                  />

                  <div className={classNames("all", sty.freeBox___13Dry)}>
                    <div
                      className={classNames("all", sty.freeBox__r9GtT)}
                      style={{
                        textShadow: "rgba(255, 216, 64, 0.48) 0px 0px 8px"
                      }}
                    >
                      <span
                        className={classNames(
                          "all",
                          "span",
                          "span__uNJep",
                          "__wab_text",
                          sty.span__xm4N2
                        )}
                      >
                        {"Now"}
                      </span>
                    </div>
                    <div
                      className={classNames("all", sty.freeBox__gDGi)}
                      style={{
                        textShadow: "rgba(255, 255, 255, 0.18) 0px 0px 6px"
                      }}
                    >
                      <span
                        className={classNames(
                          "all",
                          "span",
                          "span__uNJep",
                          "__wab_text",
                          sty.span___11XoU
                        )}
                      >
                        {"Devlog"}
                      </span>
                    </div>
                    <p
                      data-plasmic-name={"nowBody"}
                      data-plasmic-override={overrides.nowBody}
                      className={classNames(
                        "all",
                        "p",
                        "p__uNJep",
                        "__wab_text",
                        sty.nowBody
                      )}
                    >
                      {"Website and presentation pass."}
                    </p>
                  </div>
                </section>
                <section
                  className={classNames("all", sty.section__lgSqn)}
                  id={"BHn98j_Sc3AH"}
                  style={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? {
                          backgroundImage:
                            "linear-gradient(rgba(20,23,24,0.88), rgba(20,23,24,0.88)), url('/assets/ui/backgroun-fore.png')",
                          backgroundSize: "auto, cover",
                          backgroundPosition: "center center, center center",
                          backgroundRepeat: "repeat, no-repeat",
                          borderImageSource: "url('/assets/ui/card_frame.png')",
                          borderImageSlice: "78 58",
                          borderImageWidth: "42px",
                          borderImageRepeat: "stretch",
                          justifySelf: "stretch",
                          aspectRatio: "auto"
                        }
                      : {
                          backgroundImage: "none",
                          backgroundSize: "auto",
                          backgroundPosition: "center center",
                          backgroundRepeat: "repeat",
                          borderImageSource: "none",
                          borderImageSlice: "0",
                          borderImageWidth: "0",
                          borderImageRepeat: "stretch",
                          isolation: "isolate"
                        }
                  }
                >
                  <div
                    className={classNames("all", sty.freeBox___4C9Vx)}
                    style={{
                      borderImageSource: 'url("/assets/ui/card_frame.png")',
                      borderImageSlice: "78 58",
                      borderImageWidth: "37px",
                      borderImageRepeat: "stretch"
                    }}
                  />

                  <div
                    className={classNames("all", sty.freeBox__rB9Hu)}
                    style={{
                      backgroundImage:
                        'linear-gradient(rgba(20, 23, 24, 0.88), rgba(20, 23, 24, 0.88)), url("/assets/ui/backgroun-fore.png")',
                      backgroundSize: "auto, cover",
                      backgroundPosition: "center center, center center",
                      backgroundRepeat: "repeat, no-repeat"
                    }}
                  />

                  <div className={classNames("all", sty.freeBox___3Uf3D)}>
                    <div
                      className={classNames("all", sty.freeBox__hwSiu)}
                      style={{
                        textShadow: "rgba(255, 91, 124, 0.5) 0px 0px 8px"
                      }}
                    >
                      <span
                        className={classNames(
                          "all",
                          "span",
                          "span__uNJep",
                          "__wab_text",
                          sty.span___5T64X
                        )}
                      >
                        {"Coming Up"}
                      </span>
                    </div>
                    <div
                      className={classNames("all", sty.freeBox__csPjo)}
                      style={{
                        textShadow: "rgba(255, 255, 255, 0.18) 0px 0px 6px"
                      }}
                    >
                      <span
                        className={classNames(
                          "all",
                          "span",
                          "span__uNJep",
                          "__wab_text",
                          sty.span__fi2Y
                        )}
                      >
                        {"Protocol"}
                      </span>
                    </div>
                    <p
                      data-plasmic-name={"comingUpBody"}
                      data-plasmic-override={overrides.comingUpBody}
                      className={classNames(
                        "all",
                        "p",
                        "p__uNJep",
                        "__wab_text",
                        sty.comingUpBody
                      )}
                    >
                      {"Realtime packet cleanup."}
                    </p>
                  </div>
                </section>
                <section
                  className={classNames("all", sty.section___07Lze)}
                  id={"K2hQxbqrczUB"}
                  style={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? {
                          backgroundImage:
                            "linear-gradient(rgba(40,40,40,0.86), rgba(40,40,40,0.86))",
                          backgroundSize: "auto",
                          backgroundPosition: "center center",
                          backgroundRepeat: "repeat",
                          borderImageSource: "none",
                          borderImageSlice: "0",
                          borderImageWidth: "0",
                          borderImageRepeat: "stretch",
                          justifySelf: "stretch"
                        }
                      : {
                          backgroundImage:
                            "linear-gradient(rgba(40,40,40,0.86), rgba(40,40,40,0.86))",
                          backgroundSize: "auto",
                          backgroundPosition: "center center",
                          backgroundRepeat: "repeat",
                          borderImageSource: "none",
                          borderImageSlice: "0",
                          borderImageWidth: "0",
                          borderImageRepeat: "stretch"
                        }
                  }
                >
                  <div
                    className={classNames("all", sty.freeBox__yPCaK)}
                    id={"3K7yfGuK_MbB"}
                    style={{
                      textShadow: "rgba(0, 229, 255, 0.55) 0px 0px 8px"
                    }}
                  >
                    <span
                      className={classNames(
                        "all",
                        "span",
                        "span__uNJep",
                        "__wab_text",
                        sty.span__txctb
                      )}
                      id={"ouzuXoWOEzne"}
                    >
                      {"Utility"}
                    </span>
                  </div>
                  <p
                    data-plasmic-name={"utilityText"}
                    data-plasmic-override={overrides.utilityText}
                    className={classNames(
                      "all",
                      "p",
                      "p__uNJep",
                      "__wab_text",
                      sty.utilityText
                    )}
                    id={"PSA7Vlu9NjQY"}
                    style={
                      hasVariant(globalVariants, "screen", "tablet")
                        ? { columnCount: "1", columnFill: "balance" }
                        : { columnCount: "1", columnFill: "balance" }
                    }
                  >
                    {"Optional sidebar panel."}
                  </p>
                </section>
              </aside>
            </section>
          </div>
          <footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("all", sty.footer)}
            id={"1-P9dmk7ulsu"}
            style={{
              backgroundImage: "none",
              backgroundSize: "100% 100%",
              backgroundPosition: "center center",
              backgroundRepeat: "no-repeat",
              borderImageSource: "none",
              borderImageSlice: "0",
              borderImageWidth: "0",
              borderImageRepeat: "stretch"
            }}
          >
            <div
              className={classNames("all", sty.freeBox__gzj9Q)}
              id={"qUWecrQrzm2C"}
              style={
                hasVariant(globalVariants, "screen", "tablet")
                  ? {
                      borderImageSource: "none",
                      borderImageSlice: "0",
                      borderImageWidth: "0",
                      borderImageRepeat: "stretch",
                      backgroundImage: "url('/assets/ui/footer_bar.png')",
                      backgroundSize: "100% 100%",
                      backgroundPosition: "center center",
                      backgroundRepeat: "no-repeat"
                    }
                  : {
                      borderImageSource: 'url("/assets/ui/footer_bar.png")',
                      borderImageSlice: "1 37 fill",
                      borderImageWidth: "0 37px",
                      borderImageRepeat: "stretch"
                    }
              }
            />

            <span
              className={classNames(
                "all",
                "span",
                "span__uNJep",
                sty.span___13Omw
              )}
              id={"iz3Jjsa3dVBS"}
            >
              <span
                className={classNames(
                  "all",
                  "span",
                  "span__uNJep",
                  "__wab_text",
                  sty.span__r3Sf9
                )}
              >
                {"Footer"}
              </span>
            </span>
            <span
              className={classNames(
                "all",
                "span",
                "span__uNJep",
                sty.span___1Gu6Z
              )}
              id={"2tere_V7K577"}
            >
              <span
                className={classNames(
                  "all",
                  "span",
                  "span__uNJep",
                  "__wab_text",
                  sty.span__yGMd6
                )}
              >
                {"Space Rocks Devlog"}
              </span>
            </span>
          </footer>
          <div
            className={classNames("all", sty.freeBox__r0HPi)}
            id={"xBsj_u1286GT"}
          >
            <span
              data-plasmic-name={"finePrint"}
              data-plasmic-override={overrides.finePrint}
              className={classNames(
                "all",
                "span",
                "span__uNJep",
                "__wab_text",
                sty.finePrint
              )}
              id={"-vFjetRuUugf"}
            >
              {
                "Space Rocks! is an active development project. All media, features, and content are work in progress and subject to change before final release."
              }
            </span>
          </div>
        </main>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "nav",
    "hero",
    "screenStack",
    "heroMediaFrame",
    "heroLine1Media",
    "heroLine2Media",
    "heroLine3Media",
    "heroLine1Desktop",
    "heroLine2Desktop",
    "heroLine3Desktop",
    "article",
    "articleLabel",
    "articleTitle",
    "introText",
    "screenStack2",
    "articleMediaFrame",
    "whatChangedText",
    "blockquote",
    "calloutText",
    "whatsNextText",
    "aside",
    "finishedBody",
    "nowBody",
    "comingUpBody",
    "utilityText",
    "footer",
    "finePrint"
  ],
  header: ["header", "nav"],
  nav: ["nav"],
  hero: [
    "hero",
    "screenStack",
    "heroMediaFrame",
    "heroLine1Media",
    "heroLine2Media",
    "heroLine3Media",
    "heroLine1Desktop",
    "heroLine2Desktop",
    "heroLine3Desktop"
  ],
  screenStack: [
    "screenStack",
    "heroMediaFrame",
    "heroLine1Media",
    "heroLine2Media",
    "heroLine3Media"
  ],
  heroMediaFrame: ["heroMediaFrame"],
  heroLine1Media: ["heroLine1Media"],
  heroLine2Media: ["heroLine2Media"],
  heroLine3Media: ["heroLine3Media"],
  heroLine1Desktop: ["heroLine1Desktop"],
  heroLine2Desktop: ["heroLine2Desktop"],
  heroLine3Desktop: ["heroLine3Desktop"],
  article: [
    "article",
    "articleLabel",
    "articleTitle",
    "introText",
    "screenStack2",
    "articleMediaFrame",
    "whatChangedText",
    "blockquote",
    "calloutText",
    "whatsNextText"
  ],
  articleLabel: ["articleLabel"],
  articleTitle: ["articleTitle"],
  introText: ["introText"],
  screenStack2: ["screenStack2", "articleMediaFrame"],
  articleMediaFrame: ["articleMediaFrame"],
  whatChangedText: ["whatChangedText"],
  blockquote: ["blockquote", "calloutText"],
  calloutText: ["calloutText"],
  whatsNextText: ["whatsNextText"],
  aside: ["aside", "finishedBody", "nowBody", "comingUpBody", "utilityText"],
  finishedBody: ["finishedBody"],
  nowBody: ["nowBody"],
  comingUpBody: ["comingUpBody"],
  utilityText: ["utilityText"],
  footer: ["footer"],
  finePrint: ["finePrint"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "main";
  header: "header";
  nav: "nav";
  hero: "section";
  screenStack: "div";
  heroMediaFrame: typeof CrtMediaFrame;
  heroLine1Media: "span";
  heroLine2Media: "span";
  heroLine3Media: "span";
  heroLine1Desktop: "span";
  heroLine2Desktop: "span";
  heroLine3Desktop: "span";
  article: "article";
  articleLabel: "span";
  articleTitle: "h1";
  introText: "p";
  screenStack2: "div";
  articleMediaFrame: typeof CrtMediaFrame;
  whatChangedText: "p";
  blockquote: "blockquote";
  calloutText: "span";
  whatsNextText: "p";
  aside: "aside";
  finishedBody: "p";
  nowBody: "p";
  comingUpBody: "p";
  utilityText: "p";
  footer: "footer";
  finePrint: "span";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHomepage__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHomepage__VariantsArgs;
    args?: PlasmicHomepage__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicHomepage__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicHomepage__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    nav: makeNodeComponent("nav"),
    hero: makeNodeComponent("hero"),
    screenStack: makeNodeComponent("screenStack"),
    heroMediaFrame: makeNodeComponent("heroMediaFrame"),
    heroLine1Media: makeNodeComponent("heroLine1Media"),
    heroLine2Media: makeNodeComponent("heroLine2Media"),
    heroLine3Media: makeNodeComponent("heroLine3Media"),
    heroLine1Desktop: makeNodeComponent("heroLine1Desktop"),
    heroLine2Desktop: makeNodeComponent("heroLine2Desktop"),
    heroLine3Desktop: makeNodeComponent("heroLine3Desktop"),
    article: makeNodeComponent("article"),
    articleLabel: makeNodeComponent("articleLabel"),
    articleTitle: makeNodeComponent("articleTitle"),
    introText: makeNodeComponent("introText"),
    screenStack2: makeNodeComponent("screenStack2"),
    articleMediaFrame: makeNodeComponent("articleMediaFrame"),
    whatChangedText: makeNodeComponent("whatChangedText"),
    blockquote: makeNodeComponent("blockquote"),
    calloutText: makeNodeComponent("calloutText"),
    whatsNextText: makeNodeComponent("whatsNextText"),
    aside: makeNodeComponent("aside"),
    finishedBody: makeNodeComponent("finishedBody"),
    nowBody: makeNodeComponent("nowBody"),
    comingUpBody: makeNodeComponent("comingUpBody"),
    utilityText: makeNodeComponent("utilityText"),
    footer: makeNodeComponent("footer"),
    finePrint: makeNodeComponent("finePrint"),

    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/",
      pagePath: "/",
      params: {},
      query: {}
    })
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
