/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uNJepqX5kmDcUn9dDb3UVD
// Component: jbxoeWnqZPbP

import * as React from "react";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uNJepqX5kmDcUn9dDb3UVD/projectModule
import { _useStyleTokens } from "./PlasmicStyleTokensProvider"; // plasmic-import: uNJepqX5kmDcUn9dDb3UVD/styleTokensProvider

import "@plasmicapp/react-web/lib/plasmic.css";

import "./plasmic.css"; // plasmic-import: uNJepqX5kmDcUn9dDb3UVD/projectcss
import sty from "./PlasmicArchive.module.css"; // plasmic-import: jbxoeWnqZPbP/css

const emptyProxy: any = new Proxy(() => "", {
  get(_, prop) {
    return prop === Symbol.toPrimitive ? () => "" : emptyProxy;
  }
});

function wrapQueriesWithLoadingProxy($q: any): any {
  return new Proxy($q, {
    get(target, queryName) {
      const query = target[queryName];
      return !query || query.isLoading || !query.data ? emptyProxy : query;
    }
  });
}

export type PageCtx = {
  pageRoute: string;
  pagePath: string;
  params: Record<string, string | string[] | undefined>;
  query: Record<string, string | string[] | undefined>;
};

export function generateDynamicMetadata($q: any, $ctx: PageCtx) {
  return {
    title: "Devlog Archive",

    openGraph: {
      title: "Devlog Archive"
    },
    twitter: {
      card: "summary" as const,
      title: "Devlog Archive"
    }
  };
}

createPlasmicElementProxy;

export type PlasmicArchive__VariantMembers = {};
export type PlasmicArchive__VariantsArgs = {};
type VariantPropType = keyof PlasmicArchive__VariantsArgs;
export const PlasmicArchive__VariantProps = new Array<VariantPropType>();

export type PlasmicArchive__ArgsType = {};
type ArgPropType = keyof PlasmicArchive__ArgsType;
export const PlasmicArchive__ArgProps = new Array<ArgPropType>();

export type PlasmicArchive__OverridesType = {
  root?: Flex__<"main">;
  header?: Flex__<"header">;
  nav?: Flex__<"nav">;
  section?: Flex__<"section">;
  article?: Flex__<"article">;
  h1?: Flex__<"h1">;
  p?: Flex__<"p">;
  footer?: Flex__<"footer">;
};

export interface DefaultArchiveProps {
  className?: string;
}

const $$ = {};

function PlasmicArchive__RenderFunc(props: {
  variants: PlasmicArchive__VariantsArgs;
  args: PlasmicArchive__ArgsType;
  overrides: PlasmicArchive__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const globalVariants = _useGlobalVariants();

  const styleTokensClassNames = _useStyleTokens();

  return (
    <React.Fragment>
      <div className={"plasmic_page_wrapper"}>
        <main
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            "all",
            "root_reset_uNJepqX5kmDcUn9dDb3UVD",
            "plasmic_default_styles",
            "plasmic_mixins",
            styleTokensClassNames,
            sty.root
          )}
          id={"uW6XQJEMGRlw"}
        >
          <header
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            className={classNames("all", sty.header)}
            id={"Lt3Sxj5b4ANm"}
            style={{
              backgroundImage: "none",
              backgroundSize: "100% 100%",
              backgroundPosition: "center center",
              backgroundRepeat: "no-repeat",
              borderImageSource: "none",
              borderImageSlice: "0",
              borderImageWidth: "0",
              borderImageRepeat: "stretch"
            }}
          >
            <div
              className={classNames("all", sty.freeBox__gls3Y)}
              id={"j3R8Eb4zkpzk"}
              style={
                hasVariant(globalVariants, "screen", "tablet")
                  ? {
                      borderImageSource: "none",
                      borderImageSlice: "0",
                      borderImageWidth: "0",
                      borderImageRepeat: "stretch",
                      backgroundImage: "url('/assets/ui/nav_bar.png')",
                      backgroundSize: "100% 100%",
                      backgroundPosition: "center center",
                      backgroundRepeat: "no-repeat"
                    }
                  : {
                      borderImageSource: 'url("/assets/ui/nav_bar.png")',
                      borderImageSlice: "1 37 fill",
                      borderImageWidth: "0 37px",
                      borderImageRepeat: "stretch"
                    }
              }
            />

            <div
              className={classNames("all", sty.freeBox___4H7Rq)}
              id={"xDSDd6Ys-1-a"}
              style={{
                filter: "drop-shadow(rgba(255, 47, 67, 0.55) 0px 0px 6px)"
              }}
            >
              <span
                className={classNames(
                  "all",
                  "span",
                  "span__uNJep",
                  sty.span__qsxx
                )}
                id={"Nj6kH7kOTZa1"}
              >
                <PlasmicImg__
                  alt={"Space"}
                  className={classNames(sty.img__zokOz)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "23px"
                      : "27px"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  id={"8_vwG4m979nZ"}
                  loading={"lazy"}
                  src={"/assets/ui/title_space.png"}
                />
              </span>
              <span
                className={classNames(
                  "all",
                  "span",
                  "span__uNJep",
                  sty.span__hFyq1
                )}
                id={"QBJ1gzsIIPl-"}
              >
                <PlasmicImg__
                  alt={"Rocks"}
                  className={classNames(sty.img__vbDRj)}
                  displayHeight={
                    hasVariant(globalVariants, "screen", "tablet")
                      ? "25px"
                      : "29px"
                  }
                  displayMaxHeight={"none"}
                  displayMaxWidth={"none"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"auto"}
                  id={"BlQXx-nQqG_H"}
                  loading={"lazy"}
                  src={"/assets/ui/title_rocks.png"}
                />
              </span>
            </div>
            <nav
              data-plasmic-name={"nav"}
              data-plasmic-override={overrides.nav}
              className={classNames("all", sty.nav)}
              id={"1T0XsvhpLi9A"}
              style={{ textShadow: "rgba(0, 229, 255, 0.65) 0px 0px 10px" }}
            >
              <PlasmicLink__
                className={classNames("all", "a", "a__uNJep", sty.link__eCfV)}
                href={"#latest"}
                id={"9d3FT6XjLgDj"}
                platform={"react"}
              >
                <span
                  className={classNames(
                    "all",
                    "span",
                    "span__uNJep",
                    "__wab_text",
                    sty.span___4FTrj
                  )}
                  id={"rPs-U--Ym39L"}
                >
                  {"Devlog"}
                </span>
              </PlasmicLink__>
              <PlasmicLink__
                className={classNames("all", "a", "a__uNJep", sty.link__mIwf9)}
                href={"#archive"}
                id={"rW8um3abfDUl"}
                platform={"react"}
              >
                <span
                  className={classNames(
                    "all",
                    "span",
                    "span__uNJep",
                    "__wab_text",
                    sty.span__sSaxg
                  )}
                  id={"DQFgbrwD_vap"}
                >
                  {"Archive"}
                </span>
              </PlasmicLink__>
              <PlasmicLink__
                className={classNames("all", "a", "a__uNJep", sty.link__bXZhO)}
                href={"#"}
                id={"gbV0TczdRWrh"}
                platform={"react"}
              >
                <span
                  className={classNames(
                    "all",
                    "span",
                    "span__uNJep",
                    "__wab_text",
                    sty.span__nhW0
                  )}
                  id={"Qwxrm5UGzmw5"}
                >
                  {"GitHub"}
                </span>
              </PlasmicLink__>
            </nav>
          </header>
          <div
            className={classNames("all", sty.freeBox__gTn7Y)}
            id={"gMSVNH-NZasS"}
          >
            <section
              data-plasmic-name={"section"}
              data-plasmic-override={overrides.section}
              className={classNames("all", sty.section)}
              id={"PBJ79k9JaqHy"}
              style={
                hasVariant(globalVariants, "screen", "tablet")
                  ? { gridTemplateColumns: "minmax(0, 1fr)" }
                  : { gridTemplateColumns: "minmax(0px, 1fr) 250px" }
              }
            >
              <article
                data-plasmic-name={"article"}
                data-plasmic-override={overrides.article}
                className={classNames("all", sty.article)}
                id={"VKe6otEBvVPa"}
                style={
                  hasVariant(globalVariants, "screen", "mobile")
                    ? { gridColumn: "1 / -1" }
                    : hasVariant(globalVariants, "screen", "tablet")
                      ? { gridColumn: "1 / -1" }
                      : { gridColumn: "1 / -1" }
                }
              >
                <div
                  className={classNames("all", sty.freeBox__hLksr)}
                  id={"lyrSSAnBMjvn"}
                  style={{ mixBlendMode: "screen" }}
                />

                <div className={classNames("all", sty.freeBox__fZydz)}>
                  <div className={classNames("all", sty.freeBox__x5Kc)}>
                    <span
                      className={classNames(
                        "all",
                        "span",
                        "span__uNJep",
                        "__wab_text",
                        sty.span__lrQfN
                      )}
                    >
                      {"Archive"}
                    </span>
                  </div>
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      "all",
                      "h1",
                      "h1__uNJep",
                      "__wab_text",
                      sty.h1
                    )}
                  >
                    {"Devlog Archive"}
                  </h1>
                  <p
                    data-plasmic-name={"p"}
                    data-plasmic-override={overrides.p}
                    className={classNames(
                      "all",
                      "p",
                      "p__uNJep",
                      "__wab_text",
                      sty.p
                    )}
                  >
                    {
                      "All development posts for Space Rocks. This page is intentionally plain so the eventual archive data can fill this full-width article slot."
                    }
                  </p>
                  <div className={classNames("all", sty.freeBox__sTgK)}>
                    <div className={classNames("all", sty.freeBox__dc33F)}>
                      <span
                        className={classNames(
                          "all",
                          "span",
                          "span__uNJep",
                          "__wab_text",
                          sty.span__oimVm
                        )}
                      >
                        {"June 2026 \u2014 Building the Devlog Site"}
                      </span>
                    </div>
                    <div className={classNames("all", sty.freeBox___4TR2C)}>
                      <span
                        className={classNames(
                          "all",
                          "span",
                          "span__uNJep",
                          "__wab_text",
                          sty.span__nmlY1
                        )}
                      >
                        {"June 2026 \u2014 Plasmic Layout Pass"}
                      </span>
                    </div>
                    <div className={classNames("all", sty.freeBox__u0Eys)}>
                      <span
                        className={classNames(
                          "all",
                          "span",
                          "span__uNJep",
                          "__wab_text",
                          sty.span__crdNy
                        )}
                      >
                        {"May 2026 \u2014 Match Flow and Local Profiles"}
                      </span>
                    </div>
                    <div className={classNames("all", sty.freeBox___9YyrA)}>
                      <span
                        className={classNames(
                          "all",
                          "span",
                          "span__uNJep",
                          "__wab_text",
                          sty.span__koHm0
                        )}
                      >
                        {"May 2026 \u2014 Asteroid Variants"}
                      </span>
                    </div>
                  </div>
                </div>
              </article>
            </section>
          </div>
          <footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("all", sty.footer)}
            id={"1-P9dmk7ulsu"}
            style={{
              backgroundImage: "none",
              backgroundSize: "100% 100%",
              backgroundPosition: "center center",
              backgroundRepeat: "no-repeat",
              borderImageSource: "none",
              borderImageSlice: "0",
              borderImageWidth: "0",
              borderImageRepeat: "stretch"
            }}
          >
            <div
              className={classNames("all", sty.freeBox__hZwOk)}
              id={"qUWecrQrzm2C"}
              style={
                hasVariant(globalVariants, "screen", "tablet")
                  ? {
                      borderImageSource: "none",
                      borderImageSlice: "0",
                      borderImageWidth: "0",
                      borderImageRepeat: "stretch",
                      backgroundImage: "url('/assets/ui/footer_bar.png')",
                      backgroundSize: "100% 100%",
                      backgroundPosition: "center center",
                      backgroundRepeat: "no-repeat"
                    }
                  : {
                      borderImageSource: 'url("/assets/ui/footer_bar.png")',
                      borderImageSlice: "1 37 fill",
                      borderImageWidth: "0 37px",
                      borderImageRepeat: "stretch"
                    }
              }
            />

            <span
              className={classNames(
                "all",
                "span",
                "span__uNJep",
                sty.span__zpaOi
              )}
              id={"iz3Jjsa3dVBS"}
            >
              <span
                className={classNames(
                  "all",
                  "span",
                  "span__uNJep",
                  "__wab_text",
                  sty.span__sj1Bb
                )}
              >
                {"Footer"}
              </span>
            </span>
            <span
              className={classNames(
                "all",
                "span",
                "span__uNJep",
                sty.span__m5OfV
              )}
              id={"2tere_V7K577"}
            >
              <span
                className={classNames(
                  "all",
                  "span",
                  "span__uNJep",
                  "__wab_text",
                  sty.span__k3Oem
                )}
              >
                {"Space Rocks Devlog"}
              </span>
            </span>
          </footer>
          <div
            className={classNames("all", sty.freeBox__dv5Kc)}
            id={"xBsj_u1286GT"}
            style={
              hasVariant(globalVariants, "screen", "mobile")
                ? { plasmicDisplayNone: "true" }
                : hasVariant(globalVariants, "screen", "tablet")
                  ? { plasmicDisplayNone: "true" }
                  : { plasmicDisplayNone: "true" }
            }
          >
            <span
              className={classNames(
                "all",
                "span",
                "span__uNJep",
                "__wab_text",
                sty.span__uE7Sz
              )}
              id={"-vFjetRuUugf"}
            >
              {
                "Space Rocks! is an active development project. All media, features, and content are work in progress and subject to change before final release."
              }
            </span>
          </div>
        </main>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "header", "nav", "section", "article", "h1", "p", "footer"],
  header: ["header", "nav"],
  nav: ["nav"],
  section: ["section", "article", "h1", "p"],
  article: ["article", "h1", "p"],
  h1: ["h1"],
  p: ["p"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "main";
  header: "header";
  nav: "nav";
  section: "section";
  article: "article";
  h1: "h1";
  p: "p";
  footer: "footer";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicArchive__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicArchive__VariantsArgs;
    args?: PlasmicArchive__ArgsType;
    overrides?: NodeOverridesType<T>;
  } &
    // Specify variants directly as props
    Omit<PlasmicArchive__VariantsArgs, ReservedPropsType> &
    // Specify args directly as props
    Omit<PlasmicArchive__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicArchive__ArgProps,
          internalVariantPropNames: PlasmicArchive__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicArchive__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicArchive";
  } else {
    func.displayName = `PlasmicArchive.${nodeName}`;
  }
  return func;
}

export const PlasmicArchive = Object.assign(
  // Top-level PlasmicArchive renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    nav: makeNodeComponent("nav"),
    section: makeNodeComponent("section"),
    article: makeNodeComponent("article"),
    h1: makeNodeComponent("h1"),
    p: makeNodeComponent("p"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicArchive
    internalVariantProps: PlasmicArchive__VariantProps,
    internalArgProps: PlasmicArchive__ArgProps,

    pageMetadata: generateDynamicMetadata(wrapQueriesWithLoadingProxy({}), {
      pageRoute: "/archive",
      pagePath: "/archive",
      params: {},
      query: {}
    })
  }
);

export default PlasmicArchive;
/* prettier-ignore-end */
