#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


GENERATED_HEADER = "Code generated by tools/scripts/generate_constants.py; DO NOT EDIT."
VECTOR_COMPONENTS = {"x": 0, "y": 1}


def main() -> None:
    repo_root = Path(__file__).resolve().parents[2]
    parser = argparse.ArgumentParser(description="Generate constants files from shared JSON.")
    parser.add_argument(
        "--source",
        default="shared/constants/constants.json",
        help="Path to the constants JSON file, relative to the repo root.",
    )
    args = parser.parse_args()

    source_path = repo_root / args.source
    data = json.loads(source_path.read_text(encoding="utf-8"))
    groups_by_id = {group["id"]: group for group in data["groups"]}

    for output in data["outputs"]:
        language = output["language"]
        lines = render_output(language, output, groups_by_id)
        output_path = repo_root / output["path"]
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"generated {output_path.relative_to(repo_root)}")


def render_output(language: str, output: dict[str, Any], groups_by_id: dict[str, Any]) -> list[str]:
    if language == "gdscript":
        return render_gdscript(output, groups_by_id)
    if language == "go":
        return render_go(output, groups_by_id)

    raise ValueError(f"Unsupported constants output language: {language}")


def render_gdscript(output: dict[str, Any], groups_by_id: dict[str, Any]) -> list[str]:
    lines = [
        f"# {GENERATED_HEADER}",
        f"extends {output.get('base', 'RefCounted')}",
    ]

    for group_id in output["groups"]:
        group_lines = render_group_constants("gdscript", groups_by_id[group_id])
        if not group_lines:
            continue

        lines.append("")
        lines.extend(group_lines)

    return lines


def render_go(output: dict[str, Any], groups_by_id: dict[str, Any]) -> list[str]:
    lines = [
        f"// {GENERATED_HEADER}",
        f"package {output['package']}",
        "",
        "const (",
    ]

    first_group = True
    for group_id in output["groups"]:
        group_lines = render_group_constants("go", groups_by_id[group_id])
        if not group_lines:
            continue

        if not first_group:
            lines.append("")
        first_group = False

        lines.extend(f"\t{line}" for line in align_go_constants(group_lines))

    lines.append(")")
    return lines


def render_group_constants(language: str, group: dict[str, Any]) -> list[str]:
    lines: list[str] = []

    for constant in group["constants"]:
        target = constant.get("targets", {}).get(language)
        if target is None:
            continue

        if isinstance(target, list):
            for item in target:
                lines.append(render_constant(language, constant, item))
        else:
            lines.append(render_constant(language, constant, target))

    return lines


def render_constant(language: str, constant: dict[str, Any], target: dict[str, Any]) -> str:
    value = value_for_target(constant, target)

    if language == "gdscript":
        return f"const {target['name']} := {format_gdscript_value(constant['type'], value)}"
    if language == "go":
        return f"{target['name']} = {format_go_value(constant['type'], value)}"

    raise ValueError(f"Unsupported constants output language: {language}")


def value_for_target(constant: dict[str, Any], target: dict[str, Any]) -> Any:
    value = constant["value"]
    component = target.get("component")
    if component is None:
        return value

    if constant["type"] != "vector2":
        raise ValueError(f"{constant['id']} uses component on non-vector2 value")

    return value[VECTOR_COMPONENTS[component]]


def format_gdscript_value(value_type: str, value: Any) -> str:
    if value_type == "vector2":
        return f"Vector2({format_number(value[0])}, {format_number(value[1])})"

    return format_number(value)


def format_go_value(value_type: str, value: Any) -> str:
    if value_type == "vector2" and isinstance(value, list):
        raise ValueError("Go constants cannot render vector2 directly; split it into components.")

    return format_number(value)


def format_number(value: int | float) -> str:
    if isinstance(value, int):
        return str(value)
    if value.is_integer():
        return f"{value:.1f}"
    return str(value)


def align_go_constants(lines: list[str]) -> list[str]:
    split_lines = [line.split(" = ", 1) for line in lines]
    max_name_length = max(len(parts[0]) for parts in split_lines)

    return [
        f"{name.ljust(max_name_length)} = {value}"
        for name, value in split_lines
    ]


if __name__ == "__main__":
    main()
