// Code generated by tools/data_sync/main.py; DO NOT EDIT.
package runtime

type ClientConfig struct {
	VisibleWorldWidth  float64 `json:"visible_world_width"`
	VisibleWorldHeight float64 `json:"visible_world_height"`
}

type InputState struct {
	Forward       bool `json:"forward"`
	Back          bool `json:"back"`
	Right         bool `json:"right"`
	Left          bool `json:"left"`
	PrimaryFire   bool `json:"primary_fire"`
	SecondaryFire bool `json:"secondary_fire"`
}

type ShipState struct {
	ID                         string  `json:"id"`
	ShipType                   string  `json:"ship_type"`
	X                          float64 `json:"x"`
	Y                          float64 `json:"y"`
	Rotation                   float64 `json:"rotation"`
	Health                     int     `json:"health"`
	Shields                    int     `json:"shields"`
	Thrusting                  bool    `json:"thrusting"`
	TargetKind                 string  `json:"target_kind"`
	TargetID                   string  `json:"target_id"`
	PrimaryWeaponID            string  `json:"primary_weapon_id"`
	PrimaryAmmoPolicy          string  `json:"primary_ammo_policy"`
	PrimaryCooldownRemaining   float64 `json:"primary_cooldown_remaining"`
	PrimaryAmmoRemaining       int     `json:"primary_ammo_remaining"`
	SecondaryWeaponID          string  `json:"secondary_weapon_id"`
	SecondaryAmmoPolicy        string  `json:"secondary_ammo_policy"`
	SecondaryCooldownRemaining float64 `json:"secondary_cooldown_remaining"`
	SecondaryAmmoRemaining     int     `json:"secondary_ammo_remaining"`
}

type AsteroidState struct {
	ID      string  `json:"id"`
	X       float64 `json:"x"`
	Y       float64 `json:"y"`
	Size    int     `json:"size"`
	Health  int     `json:"health"`
	Scale   float64 `json:"scale"`
	Variant int     `json:"variant"`
}

type BulletState struct {
	ID             string  `json:"id"`
	OwnerID        string  `json:"owner_id"`
	X              float64 `json:"x"`
	Y              float64 `json:"y"`
	Rotation       float64 `json:"rotation"`
	WeaponID       string  `json:"weapon_id"`
	ProjectileType string  `json:"projectile_type"`
}

type PickupState struct {
	ID              string  `json:"id"`
	Type            string  `json:"type"`
	X               float64 `json:"x"`
	Y               float64 `json:"y"`
	Health          int     `json:"health"`
	AgeSeconds      float64 `json:"age_seconds"`
	LifespanSeconds float64 `json:"lifespan_seconds"`
}
