// Code generated by tools/data_sync/main.py; DO NOT EDIT.
package runtime

type ClientConfig struct {
	VisibleWorldWidth  float64 `json:"visible_world_width"`
	VisibleWorldHeight float64 `json:"visible_world_height"`
}

type InputState struct {
	Forward bool `json:"forward"`
	Back    bool `json:"back"`
	Right   bool `json:"right"`
	Left    bool `json:"left"`
	Shoot   bool `json:"shoot"`
}

type ShipState struct {
	ID             string  `json:"id"`
	ShipType       string  `json:"ship_type"`
	X              float64 `json:"x"`
	Y              float64 `json:"y"`
	Rotation       float64 `json:"rotation"`
	Health         int     `json:"health"`
	Shields        int     `json:"shields"`
	Thrusting      bool    `json:"thrusting"`
	TargetPlayerID string  `json:"target_player_id"`
	TargetKind     string  `json:"target_kind"`
	TargetID       string  `json:"target_id"`
}

type AsteroidState struct {
	ID      string  `json:"id"`
	X       float64 `json:"x"`
	Y       float64 `json:"y"`
	Size    int     `json:"size"`
	Health  int     `json:"health"`
	Scale   float64 `json:"scale"`
	Variant int     `json:"variant"`
}

type BulletState struct {
	ID       string  `json:"id"`
	OwnerID  string  `json:"owner_id"`
	X        float64 `json:"x"`
	Y        float64 `json:"y"`
	Rotation float64 `json:"rotation"`
}
