# Code generated by tools/data_sync; DO NOT EDIT.
extends RefCounted

# data-sync:start constants.server.world
const WORLD_WIDTH := 8625.0
const WORLD_HEIGHT := 4500.0
# data-sync:end constants.server.world

# data-sync:start constants.client.presentation
const GAME_OVER_SOUND_DELAY := 0.4
const BACKGROUND_PARALLAX := 0.25
const FOREGROUND_BACKGROUND_PARALLAX := 0.45
const FOREGROUND_BACKGROUND_OFFSET := Vector2(480.0, 270.0)
const PLAYER_INTERPOLATION_SPEED := 18.0
const WINDOW_MIN_SIZE := Vector2(1280.0, 720.0)
const WINDOW_MAX_SIZE := Vector2(2875.0, 1500.0)
const OSINDICATOR_EDGE_MARGIN := 32.0
const OSINDICATOR_TARGET_VISIBILITY_PADDING := 64.0
# data-sync:end constants.client.presentation
