// Code generated by tools/scripts/generate_packets.py; DO NOT EDIT.
package game

import entities "github.com/Lokee86/space-rocks/server/internal/game/entities"

const (
	PacketTypeInput        = "input"
	PacketTypeClientConfig = "client_config"
	PacketTypeState        = "state"
	PacketTypeBulletBlast  = "bullet_blast"
	PacketTypeShipDeath    = "ship_death"
	PacketTypeRespawn      = "respawn"
)

type ClientPacket struct {
	Type   string                `json:"type"`
	Input  entities.InputState   `json:"input"`
	Config entities.ClientConfig `json:"config"`
}

type EventState struct {
	Type         string  `json:"type"`
	PlayerID     string  `json:"player_id"`
	Lives        int     `json:"lives"`
	RespawnDelay float64 `json:"respawn_delay"`
	X            float64 `json:"x"`
	Y            float64 `json:"y"`
}

type StatePacket struct {
	Type      string                            `json:"type"`
	SelfID    string                            `json:"self_id"`
	Lives     int                               `json:"lives"`
	Players   map[string]entities.ShipState     `json:"players"`
	Bullets   map[string]entities.BulletState   `json:"bullets"`
	Asteroids map[string]entities.AsteroidState `json:"asteroids"`
	Events    []EventState                      `json:"events"`
}
