// Code generated by tools/data_sync; DO NOT EDIT.

package drops

var GeneratedTables = Tables{
    ByID: map[string]Table{
        "basicasteroids": {
            ID: "basicasteroids",
            SourceType: SourceTypeAsteroid,
            DropMode: DropMode("single"),
            MaxDropsPerSource: 1,
            MaxActivePickups: 2,
            Entries: []Entry{
                {
                    PickupType: "1_up",
                    Chance: 1.01,
                    MinSourceSize: 1,
                    MaxSourceSize: 4,
                },
            },
        },
    },
}