// Code generated by tools/data_sync/main.py; DO NOT EDIT.
package entities

type ClientConfig struct {
	VisibleWorldWidth  float64 `json:"visible_world_width"`
	VisibleWorldHeight float64 `json:"visible_world_height"`
}

type InputState struct {
	Forward bool `json:"forward"`
	Back    bool `json:"back"`
	Right   bool `json:"right"`
	Left    bool `json:"left"`
	Shoot   bool `json:"shoot"`
}

type ShipState struct {
	ID       string  `json:"id"`
	X        float64 `json:"x"`
	Y        float64 `json:"y"`
	Rotation float64 `json:"rotation"`
	Score    int     `json:"score"`
	Lives    int     `json:"lives"`
	Paused   bool    `json:"paused"`
}

type AsteroidState struct {
	ID      string  `json:"id"`
	X       float64 `json:"x"`
	Y       float64 `json:"y"`
	Size    int     `json:"size"`
	Variant int     `json:"variant"`
}

type BulletState struct {
	ID       string  `json:"id"`
	OwnerID  string  `json:"owner_id"`
	X        float64 `json:"x"`
	Y        float64 `json:"y"`
	Rotation float64 `json:"rotation"`
}
