// Code generated by tools/data_sync/main.py; DO NOT EDIT.
package protocol

const (
	PacketTypePlayerDataRecordMatchResult       = "player_data_record_match_result"
	PacketTypePlayerDataRecordMatchResultResult = "player_data_record_match_result_result"
	PacketTypePlayerDataLoadStats               = "player_data_load_stats"
	PacketTypePlayerDataLoadStatsResult         = "player_data_load_stats_result"
)

type PlayerDataIdentity struct {
	IdentityKind   string `json:"identity_kind"`
	AccountID      string `json:"account_id"`
	LocalProfileID string `json:"local_profile_id"`
}

type PlayerDataStats struct {
	TotalScore  int `json:"total_score"`
	HighScore   int `json:"high_score"`
	ShipDeaths  int `json:"ship_deaths"`
	GamesPlayed int `json:"games_played"`
	Wins        int `json:"wins"`
}

type PlayerDataRecordMatchResult struct {
	Type       string             `json:"type"`
	ResultID   string             `json:"result_id"`
	MatchID    string             `json:"match_id"`
	Identity   PlayerDataIdentity `json:"identity"`
	Score      int                `json:"score"`
	ShipDeaths int                `json:"ship_deaths"`
	Won        bool               `json:"won"`
}

type PlayerDataRecordMatchResultResult struct {
	Type      string          `json:"type"`
	Accepted  bool            `json:"accepted"`
	Duplicate bool            `json:"duplicate"`
	Stats     PlayerDataStats `json:"stats"`
	ErrorCode string          `json:"error_code"`
	Message   string          `json:"message"`
}

type PlayerDataLoadStats struct {
	Type     string             `json:"type"`
	Identity PlayerDataIdentity `json:"identity"`
}

type PlayerDataLoadStatsResult struct {
	Type      string          `json:"type"`
	Found     bool            `json:"found"`
	Stats     PlayerDataStats `json:"stats"`
	ErrorCode string          `json:"error_code"`
	Message   string          `json:"message"`
}
