from __future__ import annotations

from pathlib import Path

import pytest

from main import run


pytest.importorskip("tomlkit")


GO_PACKETS = """// Code generated by tools/data_sync/main.py; DO NOT EDIT.
package packets

const (
\tPacketTypeInput = "input"
)

type PlayerInputPacket struct {
\tType     string  `json:"type"`
\tSequence uint32  `json:"sequence"`
\tShoot    bool    `json:"shoot"`
\tTurn     float32 `json:"turn"`
}
"""

GDS_PACKETS = """# Code generated by tools/data_sync/main.py; DO NOT EDIT.
extends RefCounted

const TYPE_INPUT := "input"

const FIELD_SEQUENCE := "sequence"
const FIELD_SHOOT := "shoot"
const FIELD_TURN := "turn"
const FIELD_TYPE := "type"

static func input_packet(sequence, shoot, turn) -> Dictionary:
\tvar packet := {}
\tpacket[FIELD_TYPE] = TYPE_INPUT
\tpacket[FIELD_SEQUENCE] = sequence
\tpacket[FIELD_SHOOT] = shoot
\tpacket[FIELD_TURN] = turn
\treturn packet
"""


def write_project(
    tmp_path: Path,
    *,
    packet_output_ids: bool = False,
    packet_target_outputs: tuple[str, ...] = (),
) -> Path:
    for directory in ["shared/packets", "go", "gds", "ts"]:
        (tmp_path / directory).mkdir(parents=True)

    (tmp_path / "shared/game_data.toml").write_text(
        """
[constants.gameplay]
player_speed = 420.0

[constants.client]
client_scale = 2

[table]
id = "basicasteroids"
source_type = "asteroid"
max_active_pickups = 2

[[entries]]
pickup_type = "1_up"
chance = 0.05
min_source_size = 1
max_source_size = 4
""".strip()
        + "\n",
        encoding="utf-8",
    )
    (tmp_path / "shared/packets/packets.toml").write_text(
        packet_toml(include_output_ids=packet_output_ids),
        encoding="utf-8",
    )
    (tmp_path / "shared/drop_tables").mkdir(parents=True, exist_ok=True)
    (tmp_path / "shared/drop_tables/basicasteroids.toml").write_text(
        """
[table]
id = "basicasteroids"
source_type = "asteroid"
drop_mode = "single"
max_drops_per_source = 1
max_active_pickups = 2

[[entries]]
pickup_type = "1_up"
chance = 0.005
min_source_size = 1
max_source_size = 4
""".strip()
        + "\n",
        encoding="utf-8",
    )

    (tmp_path / "go/constants.go").write_text(
        """
package constants

// data-sync:start constants.gameplay
old
// data-sync:end constants.gameplay
""".lstrip(),
        encoding="utf-8",
    )
    (tmp_path / "gds/constants.gd").write_text(
        """
# data-sync:start constants.client
old
# data-sync:end constants.client
""".lstrip(),
        encoding="utf-8",
    )
    (tmp_path / "ts/constants.ts").write_text(
        """
// data-sync:start constants.network
old
// data-sync:end constants.network
""".lstrip(),
        encoding="utf-8",
    )
    (tmp_path / "go/packets.go").write_text("stale go packets\n", encoding="utf-8")
    (tmp_path / "gds/packets.gd").write_text("stale gds packets\n", encoding="utf-8")
    (tmp_path / "ts/packets.ts").write_text("stale ts packets\n", encoding="utf-8")
    (tmp_path / "go/drop_tables.go").write_text("stale drop tables\n", encoding="utf-8")

    config_path = tmp_path / "config.toml"
    config_path.write_text(config_text(packet_target_outputs=packet_target_outputs), encoding="utf-8")
    return config_path


def packet_toml(*, include_output_ids: bool = False) -> str:
    go_id = 'id = "server_game_packets"\n' if include_output_ids else ""
    realtime_id = 'id = "server_realtime_packets"\n' if include_output_ids else ""
    gds_id = 'id = "client_packets"\n' if include_output_ids else ""
    return """
[[outputs]]
{go_id}language = "go"
path = "go/packets.go"
package = "packets"
packet_types = true
structs = ["PlayerInputPacket"]

[[outputs]]
{realtime_id}language = "go"
path = "go/realtime_packets.go"
package = "realtime"
packet_types = true
structs = []

[[outputs]]
{gds_id}language = "gdscript"
path = "gds/packets.gd"
base = "RefCounted"
builders = ["input_packet"]

[[structs]]
id = "PlayerInputPacket"

[[structs.fields]]
name = "type"
json = "type"
type = "string"

[[structs.fields]]
name = "sequence"
json = "sequence"
type = "uint32"

[[structs.fields]]
name = "shoot"
json = "shoot"
type = "bool"

[[structs.fields]]
name = "turn"
json = "turn"
type = "float32"

[[packet_types]]
id = "input"
value = "input"

[[builders]]
id = "input_packet"
args = ["sequence", "shoot", "turn"]

[builders.body]
type = "input"
sequence = "$sequence"
shoot = "$shoot"
turn = "$turn"
""".format(go_id=go_id, realtime_id=realtime_id, gds_id=gds_id).lstrip()


def config_text(*, packet_target_outputs: tuple[str, ...] = ()) -> str:
    outputs_line = ""
    if packet_target_outputs:
        quoted = ", ".join(f'"{value}"' for value in packet_target_outputs)
        outputs_line = f"outputs = [{quoted}]\n"
    return """
[sot.constants]
path = "shared/game_data.toml"

[sot.packets]
path = "shared/packets/packets.toml"

[sot.drop_tables]
path = "shared/drop_tables/basicasteroids.toml"

[constants.go]
files = ["go/constants.go"]
sections = ["constants.gameplay"]
owns = ["constants.gameplay"]

[constants.gds]
files = ["gds/constants.gd"]
sections = ["constants.client"]
owns = ["constants.client"]

[constants.ts]
files = ["ts/constants.ts"]
sections = ["constants.network"]
owns = ["constants.network"]

[packets.go]
files = ["go/packets.go"]
sections = ["packets"]
owns = []
{outputs_line}

[packets.gds]
files = ["gds/packets.gd"]
sections = ["packets"]
owns = []

[packets.ts]
enabled = false
files = []
sections = []
owns = []

[drop_tables.go]
files = ["go/drop_tables.go"]
sections = []
owns = []
""".format(outputs_line=outputs_line).lstrip()


def test_diff_packets_writes_nothing_and_prints_unified_diff(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    config_path = write_project(tmp_path)
    before = (tmp_path / "go/packets.go").read_text(encoding="utf-8")

    assert run(["-diff", "-packets", "-go", "-config", str(config_path)]) == 0

    captured = capsys.readouterr()
    assert "+const (" in captured.out
    assert "+type PlayerInputPacket struct {" in captured.out
    assert (tmp_path / "go/packets.go").read_text(encoding="utf-8") == before


def test_check_packets_exit_codes(tmp_path: Path) -> None:
    config_path = write_project(tmp_path)

    assert run(["-check", "-packets", "-gds", "-config", str(config_path)]) == 1
    (tmp_path / "gds/packets.gd").write_text(GDS_PACKETS, encoding="utf-8")
    assert run(["-check", "-packets", "-gds", "-config", str(config_path)]) == 0


def test_combined_go_gds_packet_check(tmp_path: Path) -> None:
    config_path = write_project(tmp_path)
    (tmp_path / "go/packets.go").write_text(GO_PACKETS, encoding="utf-8")
    (tmp_path / "gds/packets.gd").write_text(GDS_PACKETS, encoding="utf-8")

    assert run(["-check", "-packets", "-go", "-gds", "-config", str(config_path)]) == 0


def test_packet_push_writes_only_requested_language(tmp_path: Path) -> None:
    config_path = write_project(tmp_path)
    gds_before = (tmp_path / "gds/packets.gd").read_text(encoding="utf-8")
    constants_before = (tmp_path / "go/constants.go").read_text(encoding="utf-8")

    assert run(["-push", "-packets", "-go", "-config", str(config_path)]) == 0

    assert (tmp_path / "go/packets.go").read_text(encoding="utf-8") == GO_PACKETS
    assert (tmp_path / "gds/packets.gd").read_text(encoding="utf-8") == gds_before
    assert (tmp_path / "go/constants.go").read_text(encoding="utf-8") == constants_before


def test_packet_push_go_and_gds(tmp_path: Path) -> None:
    config_path = write_project(tmp_path)

    assert run(["-push", "-packets", "-go", "-gds", "-config", str(config_path)]) == 0

    assert (tmp_path / "go/packets.go").read_text(encoding="utf-8") == GO_PACKETS
    assert (tmp_path / "gds/packets.gd").read_text(encoding="utf-8") == GDS_PACKETS
    assert run(["-check", "-packets", "-go", "-gds", "-config", str(config_path)]) == 0


def test_packet_push_uses_configured_output_ids(tmp_path: Path) -> None:
    config_path = write_project(
        tmp_path,
        packet_output_ids=True,
        packet_target_outputs=("server_game_packets", "server_realtime_packets"),
    )
    gds_before = (tmp_path / "gds/packets.gd").read_text(encoding="utf-8")

    assert run(["-push", "-packets", "-go", "-config", str(config_path)]) == 0

    assert (tmp_path / "go/packets.go").read_text(encoding="utf-8") == GO_PACKETS
    assert (tmp_path / "gds/packets.gd").read_text(encoding="utf-8") == gds_before


def test_packet_push_errors_when_configured_output_id_missing(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    config_path = write_project(
        tmp_path,
        packet_output_ids=True,
        packet_target_outputs=("missing_output_id",),
    )

    assert run(["-push", "-packets", "-go", "-config", str(config_path)]) == 1
    captured = capsys.readouterr()
    assert "packet TOML has no output for configured output id: missing_output_id" in captured.err


def test_packet_check_supports_split_packet_sot_paths_with_output_id(
    tmp_path: Path,
) -> None:
    config_path = write_project(
        tmp_path,
        packet_output_ids=True,
        packet_target_outputs=("server_game_packets",),
    )
    outputs_types_path = tmp_path / "shared/packets/packet_outputs_types.toml"
    structs_builders_path = tmp_path / "shared/packets/packet_structs_builders.toml"
    outputs_types_path.write_text(
        """
[[outputs]]
id = "server_game_packets"
language = "go"
path = "go/packets.go"
package = "packets"
packet_types = true
structs = ["PlayerInputPacket"]

[[packet_types]]
id = "input"
value = "input"
""".lstrip(),
        encoding="utf-8",
    )
    structs_builders_path.write_text(
        """
[[structs]]
id = "PlayerInputPacket"

[[structs.fields]]
name = "type"
json = "type"
type = "string"

[[structs.fields]]
name = "sequence"
json = "sequence"
type = "uint32"

[[structs.fields]]
name = "shoot"
json = "shoot"
type = "bool"

[[structs.fields]]
name = "turn"
json = "turn"
type = "float32"

[[builders]]
id = "input_packet"
args = ["sequence", "shoot", "turn"]

[builders.body]
type = "input"
sequence = "$sequence"
shoot = "$shoot"
turn = "$turn"
""".lstrip(),
        encoding="utf-8",
    )
    config_path.write_text(
        config_path.read_text(encoding="utf-8").replace(
            '[sot.packets]\npath = "shared/packets/packets.toml"',
            '[sot.packets]\npaths = ["shared/packets/packet_outputs_types.toml", "shared/packets/packet_structs_builders.toml"]',
        ),
        encoding="utf-8",
    )
    (tmp_path / "go/packets.go").write_text(GO_PACKETS, encoding="utf-8")

    assert run(["-check", "-packets", "-go", "-config", str(config_path)]) == 0


def test_packet_check_fails_on_duplicate_output_id_across_packet_sot_paths(
    tmp_path: Path,
    capsys: pytest.CaptureFixture[str],
) -> None:
    config_path = write_project(
        tmp_path,
        packet_output_ids=True,
        packet_target_outputs=("server_game_packets",),
    )
    first = tmp_path / "shared/packets/packet_first.toml"
    second = tmp_path / "shared/packets/packet_second.toml"
    first.write_text(
        """
[[outputs]]
id = "server_game_packets"
language = "go"
path = "go/packets.go"
package = "packets"
structs = ["PlayerInputPacket"]
""".lstrip(),
        encoding="utf-8",
    )
    second.write_text(
        """
[[outputs]]
id = "server_game_packets"
language = "go"
path = "go/packets_alt.go"
package = "packets"
structs = ["PlayerInputPacket"]
""".lstrip(),
        encoding="utf-8",
    )
    config_path.write_text(
        config_path.read_text(encoding="utf-8").replace(
            '[sot.packets]\npath = "shared/packets/packets.toml"',
            '[sot.packets]\npaths = ["shared/packets/packet_first.toml", "shared/packets/packet_second.toml"]',
        ),
        encoding="utf-8",
    )

    assert run(["-check", "-packets", "-go", "-config", str(config_path)]) == 1
    captured = capsys.readouterr()
    assert "duplicate output id: server_game_packets" in captured.err
