from __future__ import annotations

import json
from pathlib import Path

from data_sync.config import load_config
from data_sync.generators.observability_docs import generate_observability_docs
from data_sync.generators.observability_gds import generate_observability_gds
from data_sync.generators.observability_go import generate_observability_go
from data_sync.generators.observability_json import generate_observability_json
from data_sync.generators.observability_ruby import generate_observability_ruby
from data_sync.observability_sync import plan_observability_updates
from data_sync.observability_validate import validate_observability


REPO = Path(__file__).resolve().parents[3]
CONFIG = REPO / "tools" / "data_sync" / "config.toml"


def _repository_contract():
    config = load_config(CONFIG)
    return validate_observability(config.sot_paths("observability"))


def test_observability_generators_are_deterministic_and_complete() -> None:
    contract = _repository_contract()
    generators = {
        "go": generate_observability_go,
        "gds": generate_observability_gds,
        "ruby": generate_observability_ruby,
        "json": generate_observability_json,
        "docs": generate_observability_docs,
    }
    outputs = {name: generator(contract) for name, generator in generators.items()}

    for name, generator in generators.items():
        assert outputs[name] == generator(contract)
        assert outputs[name].endswith("\n")
        assert not outputs[name].endswith("\n\n")

    go_output = outputs["go"]
    assert "type Level string" in go_output
    assert "type EventName string" in go_output
    assert "type FieldName string" in go_output
    assert "func IsCanonicalLevel(value Level) bool" in go_output
    assert "func IsKnownField(value FieldName) bool" in go_output
    assert "func IsKnownEvent(value EventName) bool" in go_output

    gds_output = outputs["gds"]
    assert "class_name ObservabilityContractGenerated" in gds_output
    assert "const CANONICAL_LEVELS" in gds_output
    assert "const FIELD_DEFINITIONS" in gds_output
    assert "const EVENT_DEFINITIONS" in gds_output
    assert "static func is_known_field" in gds_output
    assert "static func is_known_event" in gds_output

    ruby_output = outputs["ruby"]
    assert "module Observability" in ruby_output
    assert "module ContractGenerated" in ruby_output
    assert "ALLOWED_TOP_LEVEL_FIELDS = [" in ruby_output
    assert "FIELD_DEFINITIONS = {" in ruby_output
    assert "EVENT_DEFINITIONS = {" in ruby_output
    assert ".freeze" in ruby_output
    assert "def canonical_level?(value)" in ruby_output
    assert "def known_field?(value)" in ruby_output
    assert "def known_event?(value)" in ruby_output

    json_output = outputs["json"]
    payload = json.loads(json_output)
    assert payload["schema"]["schema_version"] == contract.schema.schema_version
    assert len(payload["fields"]) == len(contract.fields) == 47
    assert len(payload["events"]) == len(contract.events) == 148

    docs_output = outputs["docs"]
    assert "<!-- Code generated by data-sync; DO NOT EDIT. -->" in docs_output
    assert "## Field catalog" in docs_output
    assert "## Event catalog" in docs_output
    assert "## Retention tiers" in docs_output
    assert "| timestamp | string | true |" in docs_output
    assert "| service_starting | service_lifecycle | info |" in docs_output
    assert "| operational |" in docs_output


def test_go_targets_are_byte_identical_from_one_generator() -> None:
    config = load_config(CONFIG)
    updates = plan_observability_updates(config, ("go",))

    assert len(updates) == 3
    assert len({update.after for update in updates}) == 1
    assert tuple(update.path for update in updates) == tuple(
        sorted(config.targets_for("observability", "go")[0].files)
    )
