// Code generated by tools/data_sync/main.py; DO NOT EDIT.
package devtools

const (
	PacketTypeToggleDebugInvincible            = "toggle_debug_invincible"
	PacketTypeToggleDebugInfiniteLives         = "toggle_debug_infinite_lives"
	PacketTypeToggleDebugFreezeWorld           = "toggle_debug_freeze_world"
	PacketTypeToggleDebugFreezePlayer          = "toggle_debug_freeze_player"
	PacketTypeDebugKillPlayer                  = "debug_kill_player"
	PacketTypeDebugSpawnEntity                 = "debug_spawn_entity"
	PacketTypeDebugBeginContinuousBulletStream = "debug_begin_continuous_bullet_stream"
	PacketTypeDebugRespawnPlayer               = "debug_respawn_player"
	PacketTypeDebugSetScore                    = "debug_set_score"
	PacketTypeDebugAddScore                    = "debug_add_score"
	PacketTypeDebugSetLives                    = "debug_set_lives"
	PacketTypeDebugAddLives                    = "debug_add_lives"
	PacketTypeDebugClearBullets                = "debug_clear_bullets"
	PacketTypeDebugClearAsteroids              = "debug_clear_asteroids"
)

type DebugCommand struct {
	Type           string  `json:"type"`
	TargetPlayerID string  `json:"target_player_id"`
	EntityType     string  `json:"entity_type"`
	X              float64 `json:"x"`
	Y              float64 `json:"y"`
	HasDirection   bool    `json:"has_direction"`
	DirectionX     float64 `json:"direction_x"`
	DirectionY     float64 `json:"direction_y"`
	FreezeTarget   string  `json:"freeze_target"`
	Score          int     `json:"score"`
	Amount         int     `json:"amount"`
	Lives          int     `json:"lives"`
}

type DebugStatus struct {
	Invincible       bool `json:"invincible"`
	InfiniteLives    bool `json:"infinite_lives"`
	WorldFrozen      bool `json:"world_frozen"`
	AsteroidsFrozen  bool `json:"asteroids_frozen"`
	BulletsFrozen    bool `json:"bullets_frozen"`
	SpawningFrozen   bool `json:"spawning_frozen"`
	CollisionsFrozen bool `json:"collisions_frozen"`
	PlayerFrozen     bool `json:"player_frozen"`
}
