// Code generated by tools/data_sync/main.py; DO NOT EDIT.
package devtools

const (
	PacketTypeToggleDebugInvincible    = "toggle_debug_invincible"
	PacketTypeToggleDebugInfiniteLives = "toggle_debug_infinite_lives"
	PacketTypeToggleDebugFreezeWorld   = "toggle_debug_freeze_world"
	PacketTypeToggleDebugFreezePlayer  = "toggle_debug_freeze_player"
	PacketTypeDebugKillPlayer          = "debug_kill_player"
	PacketTypeDebugSpawnEntity         = "debug_spawn_entity"
	PacketTypeDebugRespawnPlayer       = "debug_respawn_player"
)

type DebugCommand struct {
	Type           string  `json:"type"`
	TargetPlayerID string  `json:"target_player_id"`
	EntityType     string  `json:"entity_type"`
	X              float64 `json:"x"`
	Y              float64 `json:"y"`
	HasDirection   bool    `json:"has_direction"`
	DirectionX     float64 `json:"direction_x"`
	DirectionY     float64 `json:"direction_y"`
}

type DebugStatus struct {
	Invincible    bool `json:"invincible"`
	InfiniteLives bool `json:"infinite_lives"`
	WorldFrozen   bool `json:"world_frozen"`
	PlayerFrozen  bool `json:"player_frozen"`
}
