/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: uNJepqX5kmDcUn9dDb3UVD

import { createUseStyleTokens } from "@plasmicapp/react-web";

import { _useGlobalVariants } from "./plasmic"; // plasmic-import: uNJepqX5kmDcUn9dDb3UVD/projectModule

const data = {
  base: `${"plasmic_tokens_uNJepqX5kmDcUn9dDb3UVD"}`,
  varianted: []
};

export const _useStyleTokens = createUseStyleTokens(data, _useGlobalVariants);
