// Code generated by tools/data_sync; DO NOT EDIT.
package constants

// data-sync:start constants.server.runtime
const ServerTickRate = 60
// data-sync:end constants.server.runtime

// data-sync:start constants.server.player_movement
const PlayerRotationSpeed = 4.0
const PlayerThrustForce = 1000.0
const PlayerMaxSpeed = 1500.0
const PlayerDamping = 0.98
// data-sync:end constants.server.player_movement

// data-sync:start constants.server.player_lifecycle
const PlayerStartingLives = 3
const PlayerRespawnDelay = 3.0
// data-sync:end constants.server.player_lifecycle

// data-sync:start constants.server.player_session
const PlayerRespawnBuffer = 160.0
const PlayerResumeInvulnerabilitySeconds = 1.5
// data-sync:end constants.server.player_session

// data-sync:start constants.server.world
const WorldWidth = 8625.0
const WorldHeight = 6750.0
// data-sync:end constants.server.world

// data-sync:start constants.server.scoring
const BaseScore = 120
// data-sync:end constants.server.scoring

// data-sync:start constants.server.asteroids
const AsteroidSpawnInterval = 3.0
const AsteroidSpawnBatchSize = 3
const AsteroidSpawnMargin = 160.0
const AsteroidDespawnMargin = 320.0
const AsteroidMinSpeed = 115.0
const AsteroidMaxSpeed = 210.0
const AsteroidAimRandomnessDegrees = 30.0
const AsteroidSizeScale = 0.35
const AsteroidVariants = 8
// data-sync:end constants.server.asteroids

// data-sync:start constants.server.bullets
const BulletSpeed = 1200.0
const BulletLifetime = 1.75
const BulletCooldown = 0.22
const BulletSpawnOffset = 42.0
const CollisionDespawnDelay = 0.05
// data-sync:end constants.server.bullets
