// Code generated by tools/data_sync; DO NOT EDIT.
package constants

// data-sync:start constants.server.powerups.one_up
const PickupOneUpType = "1_up"
const PickupOneUpClass = "powerup"
const PickupOneUpHealth = 1
const PickupOneUpLifespan = 12.0
// data-sync:end constants.server.powerups.one_up
