// Code generated by tools/data_sync; DO NOT EDIT.
package constants

// data-sync:start constants.server.weapons.basic_cannon
const BasicCannonProjectileSpeed = 1200.0
const BasicCannonProjectileLifetime = 1.75
const BasicCannonCooldown = 0.22
const BasicCannonProjectileSpawnOffset = 42.0
const BasicCannonDamage = 1
// data-sync:end constants.server.weapons.basic_cannon

// data-sync:start constants.server.weapons.torpedo
const TorpedoProjectileSpeed = 400.0
const TorpedoProjectileLifetime = 3.5
const TorpedoProjectileSpawnOffset = 42.0
const TorpedoImpactDamage = 0
const TorpedoRadialDamage = 1
const TorpedoRadialZoneSpawnSeconds = 0.05
const TorpedoRadialTickSeconds = 0.05
const TorpedoRadialTotalSeconds = 0.2
const TorpedoRadialZoneLifetimeSeconds = 0.4
// data-sync:end constants.server.weapons.torpedo

// data-sync:start constants.shared.weapons.torpedo
const TorpedoRadialZoneCount = 4
const TorpedoRadialZoneWidth = 10
const TorpedoCooldown = 3.0
// data-sync:end constants.shared.weapons.torpedo