// Code generated by tools/data_sync; DO NOT EDIT.
package constants

// data-sync:start constants.server.weapons.basic_cannon
// data-sync:end constants.server.weapons.basic_cannon

// data-sync:start constants.server.weapons.torpedo
// data-sync:end constants.server.weapons.torpedo
