// Code generated by tools/data_sync; DO NOT EDIT.
package constants

// data-sync:start constants.server.weapon_pickups.torpedo
const PickupTorpedoType = "torpedo"
const PickupTorpedoClass = "weapon"
const PickupTorpedoHealth = 1
const PickupTorpedoLifespan = 12.0
const PickupTorpedoScenePath = "res://scenes/pickups/weapon_pickup.tscn"
const PickupTorpedoIconId = "torpedo"
const PickupTorpedoWeaponId = "torpedo"
const PickupTorpedoSlot = "secondary"
const PickupTorpedoAmmo = 1
// data-sync:end constants.server.weapon_pickups.torpedo
