// Code generated by tools/data_sync/main.py; DO NOT EDIT.
package tooling

const (
	PacketTypeTelemetrySubscribe         = "telemetry_subscribe"
	PacketTypeTelemetryUnsubscribe       = "telemetry_unsubscribe"
	PacketTypeTelemetryPing              = "telemetry_ping"
	PacketTypeMeasurementStart           = "measurement_start"
	PacketTypeMeasurementStop            = "measurement_stop"
	PacketTypeMeasurementReset           = "measurement_reset"
	PacketTypeMeasurementSnapshotRequest = "measurement_snapshot_request"
	PacketTypeDebugStatusSubscribe       = "debug_status_subscribe"
	PacketTypeDebugStatusUnsubscribe     = "debug_status_unsubscribe"
	PacketTypeDebugShapeCatalogRequest   = "debug_shape_catalog_request"
	PacketTypeTelemetrySnapshot          = "telemetry_snapshot"
	PacketTypeTelemetryPong              = "telemetry_pong"
	PacketTypeMeasurementStarted         = "measurement_started"
	PacketTypeMeasurementSnapshot        = "measurement_snapshot"
	PacketTypeMeasurementStopped         = "measurement_stopped"
	PacketTypeToolingError               = "tooling_error"
	PacketTypeToolingCommandResult       = "tooling_command_result"
)

type TelemetrySubscribe struct {
	Type      string `json:"type"`
	RequestID string `json:"request_id"`
}

type TelemetryUnsubscribe struct {
	Type      string `json:"type"`
	RequestID string `json:"request_id"`
}

type TelemetryPing struct {
	Type           string `json:"type"`
	RequestID      string `json:"request_id"`
	Sequence       int    `json:"sequence"`
	ClientSentMsec int    `json:"client_sent_msec"`
}

type MeasurementStart struct {
	Type          string `json:"type"`
	RequestID     string `json:"request_id"`
	ScenarioLabel string `json:"scenario_label"`
}

type MeasurementStop struct {
	Type      string `json:"type"`
	RequestID string `json:"request_id"`
	RunID     string `json:"run_id"`
}

type MeasurementReset struct {
	Type      string `json:"type"`
	RequestID string `json:"request_id"`
	RunID     string `json:"run_id"`
}

type MeasurementSnapshotRequest struct {
	Type      string `json:"type"`
	RequestID string `json:"request_id"`
	RunID     string `json:"run_id"`
}

type DebugStatusSubscribe struct {
	Type      string `json:"type"`
	RequestID string `json:"request_id"`
}

type DebugStatusUnsubscribe struct {
	Type      string `json:"type"`
	RequestID string `json:"request_id"`
}

type DebugShapeCatalogRequest struct {
	Type      string `json:"type"`
	RequestID string `json:"request_id"`
}

type TelemetrySnapshot struct {
	Type          string         `json:"type"`
	TimestampMsec int            `json:"timestamp_msec"`
	Sequence      int            `json:"sequence"`
	Metrics       map[string]any `json:"metrics"`
}

type TelemetryPong struct {
	Type               string `json:"type"`
	RequestID          string `json:"request_id"`
	Sequence           int    `json:"sequence"`
	ClientSentMsec     int    `json:"client_sent_msec"`
	ServerReceivedMsec int    `json:"server_received_msec"`
	ServerSentMsec     int    `json:"server_sent_msec"`
}

type MeasurementStarted struct {
	Type          string `json:"type"`
	RequestID     string `json:"request_id"`
	RunID         string `json:"run_id"`
	TimestampMsec int    `json:"timestamp_msec"`
	ScenarioLabel string `json:"scenario_label"`
}

type MeasurementSnapshot struct {
	Type          string         `json:"type"`
	RequestID     string         `json:"request_id"`
	RunID         string         `json:"run_id"`
	TimestampMsec int            `json:"timestamp_msec"`
	Sequence      int            `json:"sequence"`
	Partial       bool           `json:"partial"`
	Complete      bool           `json:"complete"`
	Metrics       map[string]any `json:"metrics"`
	Report        map[string]any `json:"report"`
}

type MeasurementStopped struct {
	Type          string         `json:"type"`
	RequestID     string         `json:"request_id"`
	RunID         string         `json:"run_id"`
	TimestampMsec int            `json:"timestamp_msec"`
	Partial       bool           `json:"partial"`
	Complete      bool           `json:"complete"`
	Report        map[string]any `json:"report"`
}

type ToolingError struct {
	Type      string `json:"type"`
	RequestID string `json:"request_id"`
	RunID     string `json:"run_id"`
	ErrorCode string `json:"error_code"`
	Message   string `json:"message"`
}

type ToolingCommandResult struct {
	Type        string `json:"type"`
	RequestID   string `json:"request_id"`
	CommandType string `json:"command_type"`
	Applied     bool   `json:"applied"`
}
