"""Go drop table generator."""

from __future__ import annotations

from data_sync.model.drop_tables import DropTable, DropTablesModel


def generate_drop_tables(model: DropTablesModel) -> str:
    lines = [
        "// Code generated by tools/data_sync; DO NOT EDIT.",
        "",
        "package drops",
        "",
        "var GeneratedTables = Tables{",
        "    ByID: map[string]Table{",
    ]

    for table in model.tables:
        lines.extend(_table_lines(table))

    lines.extend([
        "    },",
        "}",
    ])
    return "\n".join(lines)


def _table_lines(table: DropTable) -> list[str]:
    lines = [
        f'        "{_quote_string(table.id)}": {{',
        f'            ID: "{_escape_string(table.id)}",',
        f'            SourceType: {_format_source_type(table.source_type)},',
        f'            DropMode: {_format_drop_mode(table.drop_mode)},',
        f"            MaxDropsPerSource: {table.max_drops_per_source},",
        f"            MaxActivePickups: {table.max_active_pickups},",
        "            Entries: []Entry{",
    ]
    for entry in table.entries:
        lines.extend(
            [
                "                {",
                f'                    PickupType: "{_escape_string(entry.pickup_type)}",',
                f"                    Chance: {repr(entry.chance)},",
                f"                    MinSourceSize: {entry.min_source_size},",
                f"                    MaxSourceSize: {entry.max_source_size},",
                "                },",
            ]
        )
    lines.extend([
        "            },",
        "        },",
    ])
    return lines


def _format_source_type(value: str) -> str:
    if value == "asteroid":
        return "SourceTypeAsteroid"
    return f'SourceType("{_escape_string(value)}")'


def _format_drop_mode(value: str) -> str:
    return f'DropMode("{_escape_string(value)}")'


def _quote_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _escape_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
