"""Go generator for the observability source-of-truth contract."""

from __future__ import annotations

import json
import re

from data_sync.model.observability import ObservabilityContract


_GO_KEYWORDS = {
    "break", "default", "func", "interface", "select", "case", "defer",
    "go", "map", "struct", "chan", "else", "goto", "package", "switch",
    "const", "fallthrough", "if", "range", "type", "continue", "for",
    "import", "return", "var",
}


def _q(value: object) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def _b(value: bool) -> str:
    return "true" if value else "false"


def _identifier(value: str) -> str:
    """Convert a contract name to a stable exported Go identifier."""
    words = [word for word in re.split(r"[^A-Za-z0-9]+", value) if word]
    identifier = "".join(word[:1].upper() + word[1:] for word in words) or "Generated"
    if identifier[0].isdigit() or identifier in _GO_KEYWORDS:
        identifier = "Generated" + identifier
    return identifier


def _const_block(lines: list[str], entries: list[str]) -> None:
    lines.extend(["const (", *[f"\t{entry}" for entry in entries], ")", ""])


def generate_observability_go(contract: ObservabilityContract) -> str:
    """Return one deterministic, self-contained Go source file for observability."""
    schema = contract.schema
    envelope = schema.envelope
    limits = schema.limits
    fields = sorted(contract.fields, key=lambda item: item.name)
    events = sorted(contract.events, key=lambda item: item.name)
    tiers = sorted(contract.retention_tiers, key=lambda item: item.name)

    lines = [
        "// Code generated by tools/data_sync; DO NOT EDIT.",
        "",
        "package observability",
        "",
        f"const SchemaVersion = {schema.schema_version}",
        "",
        "type Level string",
        "",
    ]
    _const_block(
        lines,
        [f"Level{_identifier(level)} Level = {_q(level)}" for level in envelope.canonical_levels],
    )
    lines.extend(["type RetentionTier string", ""])
    _const_block(
        lines,
        [f"RetentionTier{_identifier(tier.name)} RetentionTier = {_q(tier.name)}" for tier in tiers],
    )
    _const_block(
        lines,
        [f"RetentionDefaultAge{_identifier(tier.name)}Seconds = {tier.default_age_seconds}" for tier in tiers]
        + [
            f"FileLoggingMaxActiveSegmentAgeSeconds = {contract.file_logging.max_active_segment_age_seconds}",
            f"FileLoggingCompressionEnabled = {_b(contract.file_logging.compression_enabled)}",
        ],
    )
    lines.extend(["type FieldName string", ""])
    _const_block(
        lines,
        [f"FieldName{_identifier(field.name)} FieldName = {_q(field.name)}" for field in fields],
    )
    lines.extend(["type EventName string", ""])
    _const_block(
        lines,
        [f"EventName{_identifier(event.name)} EventName = {_q(event.name)}" for event in events],
    )

    lines.extend([
        "// RequiredFields and CanonicalLevels are immutable by convention.",
        "var RequiredFields = []FieldName{",
        *[f"\tFieldName{_identifier(name)}," for name in envelope.required_fields],
        "}",
        "",
        "var CanonicalLevels = []Level{",
        *[f"\tLevel{_identifier(level)}," for level in envelope.canonical_levels],
        "}",
        "",
        "type FieldDefinition struct {",
        "\tName FieldName",
        "\tType string",
        "\tRequired bool",
        "\tDescription string",
        "\tSensitivity string",
        "}",
        "",
        "type EventDefinition struct {",
        "\tName EventName",
        "\tCategory string",
        "\tDefaultLevel Level",
        "\tDescription string",
        "\tServices []string",
        "\tTraceRequired bool",
        "\tAuditEligible bool",
        "\tRetentionTier RetentionTier",
        "}",
        "",
        "// FieldDefinitions and EventDefinitions are immutable by convention.",
        "var FieldDefinitions = map[FieldName]FieldDefinition{",
    ])
    for field in fields:
        name = f"FieldName{_identifier(field.name)}"
        lines.append(
            f"\t{name}: {{Name: {name}, Type: {_q(field.type)}, Required: {_b(field.required)}, "
            f"Description: {_q(field.description)}, Sensitivity: {_q(field.sensitivity)}}},"
        )
    lines.extend(["}", "", "var EventDefinitions = map[EventName]EventDefinition{"])
    for event in events:
        name = f"EventName{_identifier(event.name)}"
        services = ", ".join(_q(service) for service in sorted(event.services))
        lines.append(
            f"\t{name}: {{Name: {name}, Category: {_q(event.category)}, "
            f"DefaultLevel: Level{_identifier(event.default_level)}, Description: {_q(event.description)}, "
            f"Services: []string{{{services}}}, TraceRequired: {_b(event.trace_required)}, "
            f"AuditEligible: {_b(event.audit_eligible)}, RetentionTier: RetentionTier{_identifier(event.retention_tier)}}},"
        )
    lines.extend([
        "}",
        "",
        "func IsCanonicalLevel(value Level) bool {",
        "\tswitch value {",
        f"\tcase {', '.join(f'Level{_identifier(level)}' for level in envelope.canonical_levels)}:",
        "\t\treturn true",
        "\tdefault:",
        "\t\treturn false",
        "\t}",
        "}",
        "",
        "func IsKnownField(value FieldName) bool {",
        "\t_, ok := FieldDefinitions[value]",
        "\treturn ok",
        "}",
        "",
        "func IsKnownEvent(value EventName) bool {",
        "\t_, ok := EventDefinitions[value]",
        "\treturn ok",
        "}",
        "",
        "func IsRetentionTier(value RetentionTier) bool {",
        "\tswitch value {",
        f"\tcase {', '.join(f'RetentionTier{_identifier(tier.name)}' for tier in tiers)}:",
        "\t\treturn true",
        "\tdefault:",
        "\t\treturn false",
        "\t}",
        "}",
        "",
        "func FieldDefinitionFor(value FieldName) (FieldDefinition, bool) {",
        "\tdefinition, ok := FieldDefinitions[value]",
        "\treturn definition, ok",
        "}",
        "",
        "func EventDefinitionFor(value EventName) (EventDefinition, bool) {",
        "\tdefinition, ok := EventDefinitions[value]",
        "\treturn definition, ok",
        "}",
        "",
        f"const UUIDPattern = {_q(schema.identifiers.uuid_pattern)}",
        f"const EventNamePattern = {_q(envelope.event_name_pattern)}",
        f"const FreeFormKeyPattern = {_q(schema.free_form_fields.key_pattern)}",
        "",
    ])

    limit_entries = [
        ("MaxBatchEvents", limits.max_batch_events),
        ("MaxEventBytes", limits.max_event_bytes),
        ("MaxEventFields", limits.max_event_fields),
        ("MaxStringBytes", limits.max_string_bytes),
        ("MaxCollectionItems", limits.max_collection_items),
        ("MaxFreeFormFields", limits.max_free_form_fields),
        ("MaxFreeFormValueBytes", limits.max_free_form_value_bytes),
        ("MaxDiagnosticBundleEvents", contract.diagnostic_bundle.max_events),
        ("MaxDiagnosticBundleEventBytes", contract.diagnostic_bundle.max_event_bytes),
        ("MaxDiagnosticBundleTotalBytes", contract.diagnostic_bundle.max_total_bytes),
        ("MaxDiagnosticBundleMetadataFields", contract.diagnostic_bundle.max_metadata_fields),
        ("MaxDiagnosticBundleCorrelationFields", contract.diagnostic_bundle.max_correlation_fields),
        ("MaxDiagnosticBundleRedactionSummaryEntries", contract.diagnostic_bundle.max_redaction_summary_entries),
    ]
    _const_block(lines, [f"{name} = {value}" for name, value in limit_entries])
    return "\n".join(lines).rstrip("\n") + "\n"
