"""GDScript generator for the observability source-of-truth contract."""

from __future__ import annotations

import json
import re

from data_sync.model.observability import ObservabilityContract


def _literal(value: object) -> str:
    return json.dumps(value, ensure_ascii=False, separators=(",", ":"))


def _constant_name(value: str) -> str:
    words = [word for word in re.split(r"[^A-Za-z0-9]+", value) if word]
    name = "_".join(word.upper() for word in words) or "GENERATED"
    if name[0].isdigit():
        name = "VALUE_" + name
    return name


def _constant(prefix: str, value: str) -> str:
    return f"{prefix}_{_constant_name(value)}"


def generate_observability_gds(contract: ObservabilityContract) -> str:
    """Return deterministic, self-contained GDScript for an observability contract."""
    schema = contract.schema
    envelope = schema.envelope
    limits = schema.limits
    free_form = schema.free_form_fields
    fields = sorted(contract.fields, key=lambda item: item.name)
    events = sorted(contract.events, key=lambda item: item.name)
    tiers = sorted(contract.retention_tiers, key=lambda item: item.name)

    lines = [
        "# Code generated by tools/data_sync; DO NOT EDIT.",
        "class_name ObservabilityContractGenerated",
        "extends RefCounted",
        "",
        f"const SCHEMA_VERSION := {schema.schema_version}",
        f"const TIMESTAMP_FORMAT := {_literal(envelope.timestamp_format)}",
        f"const EVENT_NAME_PATTERN := {_literal(envelope.event_name_pattern)}",
        f"const EVENT_NAME_REGEX := {_literal(envelope.event_name_pattern)}",
        f"const UUID_PATTERN := {_literal(schema.identifiers.uuid_pattern)}",
        f"const UUID_REGEX := {_literal(schema.identifiers.uuid_pattern)}",
        f"const FREE_FORM_KEY_PATTERN := {_literal(free_form.key_pattern)}",
        f"const FREE_FORM_KEY_REGEX := {_literal(free_form.key_pattern)}",
        f"const NEW_ID_FORMAT := {_literal(schema.identifiers.new_id_format)}",
        f"const NEW_ID_VERSION := {_literal(schema.identifiers.new_id_version)}",
        f"const REJECT_UNKNOWN_TOP_LEVEL_FIELDS := {_literal(envelope.reject_unknown_top_level_fields)}",
        f"const ALLOWED_TOP_LEVEL_FIELDS := {_literal(list(envelope.allowed_top_level_fields))}",
        f"const FREE_FORM_VALUE_TYPES := {_literal(list(free_form.value_types))}",
        f"const VALUES_MUST_BE_REDACTED := {_literal(free_form.values_must_be_redacted)}",
        f"const UNKNOWN_TOP_LEVEL_FIELD_ACTION := {_literal(schema.validation.unknown_top_level_field_action)}",
        f"const UNSAFE_FIELD_ACTION := {_literal(schema.validation.unsafe_field_action)}",
        f"const NULL_VALUES_ALLOWED := {_literal(schema.validation.null_values_allowed)}",
        "",
    ]

    limit_entries = [
        ("MAX_BATCH_EVENTS", limits.max_batch_events),
        ("MAX_EVENT_BYTES", limits.max_event_bytes),
        ("MAX_EVENT_FIELDS", limits.max_event_fields),
        ("MAX_STRING_BYTES", limits.max_string_bytes),
        ("MAX_COLLECTION_ITEMS", limits.max_collection_items),
        ("MAX_FREE_FORM_FIELDS", limits.max_free_form_fields),
        ("MAX_FREE_FORM_VALUE_BYTES", limits.max_free_form_value_bytes),
        ("MAX_DIAGNOSTIC_BUNDLE_EVENTS", contract.diagnostic_bundle.max_events),
        ("MAX_DIAGNOSTIC_BUNDLE_EVENT_BYTES", contract.diagnostic_bundle.max_event_bytes),
        ("MAX_DIAGNOSTIC_BUNDLE_TOTAL_BYTES", contract.diagnostic_bundle.max_total_bytes),
        ("MAX_DIAGNOSTIC_BUNDLE_METADATA_FIELDS", contract.diagnostic_bundle.max_metadata_fields),
        ("MAX_DIAGNOSTIC_BUNDLE_CORRELATION_FIELDS", contract.diagnostic_bundle.max_correlation_fields),
        ("MAX_DIAGNOSTIC_BUNDLE_REDACTION_SUMMARY_ENTRIES", contract.diagnostic_bundle.max_redaction_summary_entries),
    ]
    lines.extend(f"const {name} := {value}" for name, value in limit_entries)
    lines.extend(["", "# Canonical values are immutable by convention."])

    lines.extend(
        [
            f"const {_constant('LEVEL', level)} := {_literal(level)}"
            for level in envelope.canonical_levels
        ]
    )
    lines.extend(
        [
            f"const {_constant('FIELD', field.name)} := {_literal(field.name)}"
            for field in fields
        ]
    )
    lines.extend(
        [
            f"const {_constant('EVENT', event.name)} := {_literal(event.name)}"
            for event in events
        ]
    )
    lines.extend(
        [
            f"const {_constant('RETENTION_TIER', tier.name)} := {_literal(tier.name)}"
            for tier in tiers
        ]
    )
    lines.extend(
        [
            "",
            f"const CANONICAL_LEVELS := {_literal(list(envelope.canonical_levels))}",
            f"const REQUIRED_FIELDS := {_literal(list(envelope.required_fields))}",
            "",
            "const FIELD_DEFINITIONS := {",
        ]
    )
    for field in fields:
        lines.append(
            f"\t{_constant('FIELD', field.name)}: {_literal({'name': field.name, 'type': field.type, 'required': field.required, 'description': field.description, 'sensitivity': field.sensitivity})},"
        )
    lines.extend(["}", "", "const EVENT_DEFINITIONS := {"])
    for event in events:
        lines.append(
            f"\t{_constant('EVENT', event.name)}: {_literal({'name': event.name, 'category': event.category, 'default_level': event.default_level, 'description': event.description, 'services': sorted(event.services), 'trace_required': event.trace_required, 'audit_eligible': event.audit_eligible, 'retention_tier': event.retention_tier})},"
        )
    lines.extend(
        [
            "}",
            "",
            f"const RETENTION_TIERS := {_literal([tier.name for tier in tiers])}",
            "",
            "static func is_canonical_level(value: String) -> bool:",
            "\treturn value in CANONICAL_LEVELS",
            "",
            "static func is_known_field(value: String) -> bool:",
            "\treturn FIELD_DEFINITIONS.has(value)",
            "",
            "static func is_known_event(value: String) -> bool:",
            "\treturn EVENT_DEFINITIONS.has(value)",
            "",
            "static func is_retention_tier(value: String) -> bool:",
            "\treturn value in RETENTION_TIERS",
            "",
        ]
    )
    return "\n".join(lines).rstrip("\n") + "\n"
