"""Markdown generator for the observability source-of-truth contract."""

from __future__ import annotations

from data_sync.model.observability import ObservabilityContract


def _cell(value: object) -> str:
    """Render a value safely inside a Markdown table cell."""
    return (
        str(value)
        .replace("\\", "\\\\")
        .replace("|", "\\|")
        .replace("\r", " ")
        .replace("\n", " ")
    )


def _bool(value: bool) -> str:
    return str(value).lower()


def _list(values: tuple[object, ...] | list[object]) -> str:
    return ", ".join(_cell(value) for value in values)


def generate_observability_docs(contract: ObservabilityContract) -> str:
    """Return deterministic Markdown documentation for an observability contract."""
    schema = contract.schema
    envelope = schema.envelope
    limits = schema.limits
    free_form = schema.free_form_fields
    validation = schema.validation
    redaction = contract.redaction
    bundle = contract.diagnostic_bundle

    lines = [
        "<!-- Code generated by data-sync; DO NOT EDIT. -->",
        "# Observability Contract",
        "",
        "Parent index: [Generated](./!INDEX.md)",
        "",
        "## Schema summary",
        "",
        f"- Schema version: `{_cell(schema.schema_version)}`",
        f"- Timestamp format: `{_cell(envelope.timestamp_format)}`",
        f"- Event name pattern: `{_cell(envelope.event_name_pattern)}`",
        f"- Reject unknown top-level fields: `{_bool(envelope.reject_unknown_top_level_fields)}`",
        f"- Allowed top-level fields: {_list(envelope.allowed_top_level_fields)}",
        f"- Identifier format: `{_cell(schema.identifiers.new_id_format)}` (version `{_cell(schema.identifiers.new_id_version)}`)",
        f"- UUID pattern: `{_cell(schema.identifiers.uuid_pattern)}`",
        "",
        "### Limits",
        "",
        "| Limit | Value |",
        "| --- | --- |",
        f"| Maximum batch events | `{_cell(limits.max_batch_events)}` |",
        f"| Maximum event bytes | `{_cell(limits.max_event_bytes)}` |",
        f"| Maximum event fields | `{_cell(limits.max_event_fields)}` |",
        f"| Maximum string bytes | `{_cell(limits.max_string_bytes)}` |",
        f"| Maximum collection items | `{_cell(limits.max_collection_items)}` |",
        f"| Maximum free-form fields | `{_cell(limits.max_free_form_fields)}` |",
        f"| Maximum free-form value bytes | `{_cell(limits.max_free_form_value_bytes)}` |",
        "",
        "### Free-form fields and validation",
        "",
        f"- Key pattern: `{_cell(free_form.key_pattern)}`",
        f"- Value types: {_list(free_form.value_types)}",
        f"- Values must be redacted: `{_bool(free_form.values_must_be_redacted)}`",
        f"- Unknown top-level field action: `{_cell(validation.unknown_top_level_field_action)}`",
        f"- Unsafe field action: `{_cell(validation.unsafe_field_action)}`",
        f"- Null values allowed: `{_bool(validation.null_values_allowed)}`",
        "",
        "## Canonical levels",
        "",
        _list(envelope.canonical_levels),
        "",
        "## Required fields",
        "",
        _list(envelope.required_fields),
        "",
        "## Services",
        "",
        "| Stable key | Emitted name |",
        "| --- | --- |",
    ]
    lines.extend(
        f"| {_cell(service.key)} | {_cell(service.emitted_name)} |"
        for service in sorted(contract.services, key=lambda item: item.key)
    )
    lines += [
        "",
        "## Emission rejection codes",
        "",
        _list(schema.rejection_codes),
        "",
        "## Field catalog",
        "",
        "| Name | Type | Required | Description | Sensitivity |",
        "| --- | --- | --- | --- | --- |",
    ]
    lines.extend(
        f"| {_cell(field.name)} | {_cell(field.type)} | {_bool(field.required)} | {_cell(field.description)} | {_cell(field.sensitivity)} |"
        for field in sorted(contract.fields, key=lambda item: item.name)
    )

    lines += [
        "",
        "## Event catalog",
        "",
        "| Name | Category | Default level | Description | Services | Trace required | Audit eligible | Retention tier | Bridge only |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    lines.extend(
        f"| {_cell(event.name)} | {_cell(event.category)} | {_cell(event.default_level)} | {_cell(event.description)} | {_list(tuple(sorted(event.services)))} | {_bool(event.trace_required)} | {_bool(event.audit_eligible)} | {_cell(event.retention_tier)} | {_bool(event.bridge_only)} |"
        for event in sorted(contract.events, key=lambda item: item.name)
    )

    lines += [
        "",
        "## Redaction",
        "",
        f"- Schema version: `{_cell(redaction.schema_version)}`",
        f"- Case sensitive: `{_bool(redaction.case_sensitive)}`",
        f"- Key matching: `{_cell(redaction.key_matching)}`",
        f"- Forbidden value handling: `{_cell(redaction.forbidden_value_handling)}`",
        f"- Rejected values preserved: `{_bool(redaction.rejected_values_must_be_preserved)}`",
        f"- Raw forbidden values may be logged: `{_bool(redaction.raw_forbidden_values_may_be_logged)}`",
        "",
        "### Redaction actions",
        "",
        "| Name | Description | Value preserved | Replacement used | Replacement marker |",
        "| --- | --- | --- | --- | --- |",
    ]
    lines.extend(
        f"| {_cell(action.name)} | {_cell(action.description)} | {_bool(action.value_preserved)} | {_bool(action.replacement_used)} | {_cell(action.replacement_marker or '')} |"
        for action in sorted(redaction.actions, key=lambda item: item.name)
    )
    lines += [
        "",
        "### Forbidden exact keys",
        "",
        "| Category | Action | Keys |",
        "| --- | --- | --- |",
    ]
    lines.extend(
        f"| {_cell(rule.category)} | {_cell(rule.action)} | {_list(tuple(sorted(rule.keys)))} |"
        for rule in sorted(redaction.exact_rules, key=lambda item: item.category)
    )
    lines += [
        "",
        "### Forbidden key fragments",
        "",
        "| Category | Action | Fragments |",
        "| --- | --- | --- |",
    ]
    lines.extend(
        f"| {_cell(rule.category)} | {_cell(rule.action)} | {_list(tuple(sorted(rule.fragments)))} |"
        for rule in sorted(redaction.fragment_rules, key=lambda item: item.category)
    )
    lines += [
        "",
        "### Redaction validation",
        "",
        f"- Missing action: `{_cell(redaction.missing_action)}`",
        f"- Ambiguous match action: `{_cell(redaction.ambiguous_match_action)}`",
        f"- Redaction failure action: `{_cell(redaction.redaction_failure_action)}`",
        f"- Rejected content must be discarded: `{_bool(redaction.rejected_content_must_be_discarded)}`",
        "",
        "## Retention tiers",
        "",
        f"- Age unit: `{_cell(contract.retention_policy.age_unit)}`",
        f"- Age values are configuration metadata: `{_bool(contract.retention_policy.age_values_are_configuration_metadata)}`",
        f"- Production legal retention commitment: `{_bool(contract.retention_policy.production_legal_retention_commitment)}`",
        "",
        "| Name | Purpose | Durability | Compression | Delete policy | Default age | Maximum age | Age configurable | Legal commitment |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    lines.extend(
        f"| {_cell(tier.name)} | {_cell(tier.purpose)} | {_cell(tier.durability)} | {_cell(tier.compression)} | {_cell(tier.delete_policy)} | {_cell(tier.default_age_seconds)} | {_cell(tier.max_age_seconds)} | {_bool(tier.age_is_configurable)} | {_bool(tier.legal_commitment)} |"
        for tier in sorted(contract.retention_tiers, key=lambda item: item.name)
    )

    lines += [
        "",
        "### Shared file-logging defaults",
        "",
        f"- Maximum active segment age: `{_cell(contract.file_logging.max_active_segment_age_seconds)}` seconds",
        f"- Compression enabled: `{_bool(contract.file_logging.compression_enabled)}`",
        "",
        "## Diagnostic bundle",
        "",
        f"- Name: `{_cell(bundle.name)}`",
        f"- Schema version: `{_cell(bundle.schema_version)}`",
        f"- Diagnostic report ID: `{_cell(bundle.diagnostic_report_id_type)}`, required: `{_bool(bundle.diagnostic_report_id_required)}`",
        f"- Safe to copy default: `{_bool(bundle.safe_to_copy_default)}` (field `{_cell(bundle.safe_to_copy_field)}`)",
        "",
        "### Limits",
        "",
        "| Limit | Value |",
        "| --- | --- |",
        f"| Maximum events | `{_cell(bundle.max_events)}` |",
        f"| Maximum event bytes | `{_cell(bundle.max_event_bytes)}` |",
        f"| Maximum total bytes | `{_cell(bundle.max_total_bytes)}` |",
        f"| Maximum metadata fields | `{_cell(bundle.max_metadata_fields)}` |",
        f"| Maximum correlation fields | `{_cell(bundle.max_correlation_fields)}` |",
        f"| Maximum redaction summary entries | `{_cell(bundle.max_redaction_summary_entries)}` |",
        "",
        "### Sections",
        "",
        "| Name | Required | Allowed fields |",
        "| --- | --- | --- |",
    ]
    sections = (bundle.metadata, bundle.correlation, bundle.redaction_summary)
    lines.extend(
        f"| {_cell(section.name)} | {_bool(section.required)} | {_list(tuple(sorted(section.allowed_fields)))} |"
        for section in sorted(sections, key=lambda item: item.name)
    )
    lines += [
        "",
        "### Events",
        "",
        f"- Required: `{_bool(bundle.events_required)}`",
        f"- Ordered by: `{_cell(bundle.events_ordered_by)}`",
        f"- Truncated when limit exceeded: `{_bool(bundle.truncated_when_limit_exceeded)}`",
        "",
        "| Allowed field | Type | Required |",
        "| --- | --- | --- |",
    ]
    lines.extend(
        f"| {_cell(field.name)} | {_cell(field.type)} | {_bool(field.required)} |"
        for field in sorted(bundle.allowed_event_fields, key=lambda item: item.name)
    )
    lines += [
        "",
        "### Forbidden content",
        "",
        f"- Behavior: `{_cell(bundle.forbidden_content_behavior)}`",
        f"- Raw value preserved: `{_bool(bundle.raw_value_preserved)}`",
        f"- Rejected event included: `{_bool(bundle.rejected_event_included)}`",
        f"- Rejected field included: `{_bool(bundle.rejected_field_included)}`",
        f"- Replacement marker: `{_cell(bundle.replacement_marker)}`",
        f"- Redaction summary counts rejected content: `{_bool(bundle.redaction_summary_must_count_rejected_content)}`",
        f"- Redaction failure behavior: `{_cell(bundle.redaction_failure_behavior)}`",
        f"- Unknown event field behavior: `{_cell(bundle.unknown_event_field_behavior)}`",
    ]
    return "\n".join(lines) + "\n"
