"""Go generator for the observability source-of-truth contract."""

from __future__ import annotations

import json
import re

from data_sync.model.observability import ObservabilityContract


_GO_KEYWORDS = {
    "break", "default", "func", "interface", "select", "case", "defer",
    "go", "map", "struct", "chan", "else", "goto", "package", "switch",
    "const", "fallthrough", "if", "range", "type", "continue", "for",
    "import", "return", "var",
}


def _q(value: object) -> str:
    return json.dumps(str(value), ensure_ascii=False)


def _b(value: bool) -> str:
    return "true" if value else "false"


def _identifier(value: str) -> str:
    """Convert a contract name to a stable exported Go identifier."""
    words = [word for word in re.split(r"[^A-Za-z0-9]+", value) if word]
    identifier = "".join(word[:1].upper() + word[1:] for word in words) or "Generated"
    if identifier[0].isdigit() or identifier in _GO_KEYWORDS:
        identifier = "Generated" + identifier
    return identifier


def _const_block(lines: list[str], entries: list[str]) -> None:
    lines.extend(["const (", *[f"\t{entry}" for entry in entries], ")", ""])


def generate_observability_go(contract: ObservabilityContract) -> str:
    """Return one deterministic, self-contained Go source file for observability."""
    schema = contract.schema
    envelope = schema.envelope
    limits = schema.limits
    fields = sorted(contract.fields, key=lambda item: item.name)
    events = sorted(contract.events, key=lambda item: item.name)
    services = sorted(contract.services, key=lambda item: item.key)
    tiers = sorted(contract.retention_tiers, key=lambda item: item.name)
    redaction = contract.redaction

    lines = [
        "// Code generated by tools/data_sync; DO NOT EDIT.",
        "",
        "package observabilityevent",
        "",
        f"const SchemaVersion = {schema.schema_version}",
        "",
        "type Level string",
        "",
    ]
    _const_block(
        lines,
        [f"Level{_identifier(level)} Level = {_q(level)}" for level in envelope.canonical_levels],
    )
    lines.extend(["type ServiceKey string", ""])
    _const_block(
        lines,
        [f"ServiceKey{_identifier(service.key)} ServiceKey = {_q(service.key)}" for service in services],
    )
    _const_block(
        lines,
        [f"ServiceName{_identifier(service.key)} = {_q(service.emitted_name)}" for service in services],
    )
    lines.extend(["type RetentionTier string", ""])
    _const_block(
        lines,
        [f"RetentionTier{_identifier(tier.name)} RetentionTier = {_q(tier.name)}" for tier in tiers],
    )
    _const_block(
        lines,
        [f"RetentionDefaultAge{_identifier(tier.name)}Seconds = {tier.default_age_seconds}" for tier in tiers]
        + [
            f"FileLoggingMaxActiveSegmentAgeSeconds = {contract.file_logging.max_active_segment_age_seconds}",
            f"FileLoggingCompressionEnabled = {_b(contract.file_logging.compression_enabled)}",
        ],
    )
    lines.extend(["type FieldName string", ""])
    _const_block(
        lines,
        [f"FieldName{_identifier(field.name)} FieldName = {_q(field.name)}" for field in fields],
    )
    lines.extend(["type EventName string", ""])
    _const_block(
        lines,
        [f"EventName{_identifier(event.name)} EventName = {_q(event.name)}" for event in events],
    )
    lines.extend(["type RejectionCode string", ""])
    _const_block(
        lines,
        [f"RejectionCode{_identifier(code)} RejectionCode = {_q(code)}" for code in schema.rejection_codes],
    )
    lines.extend(["type RedactionAction string", ""])
    _const_block(
        lines,
        [
            f"RedactionAction{_identifier(action.name)} RedactionAction = {_q(action.name)}"
            for action in sorted(redaction.actions, key=lambda item: item.name)
        ],
    )

    lines.extend([
        "// RequiredFields and CanonicalLevels are immutable by convention.",
        "var RequiredFields = []FieldName{",
        *[f"\tFieldName{_identifier(name)}," for name in envelope.required_fields],
        "}",
        "",
        "var CanonicalLevels = []Level{",
        *[f"\tLevel{_identifier(level)}," for level in envelope.canonical_levels],
        "}",
        "",
        "var FreeFormValueTypes = []string{",
        *[f"\t{_q(value_type)}," for value_type in schema.free_form_fields.value_types],
        "}",
        "",
        "type FieldDefinition struct {",
        "\tName FieldName",
        "\tType string",
        "\tRequired bool",
        "\tDescription string",
        "\tSensitivity string",
        "}",
        "",
        "type EventDefinition struct {",
        "\tName EventName",
        "\tCategory string",
        "\tDefaultLevel Level",
        "\tDescription string",
        "\tServices []ServiceKey",
        "\tTraceRequired bool",
        "\tAuditEligible bool",
        "\tRetentionTier RetentionTier",
        "\tBridgeOnly bool",
        "}",
        "",
        "type ServiceDefinition struct {",
        "\tKey ServiceKey",
        "\tEmittedName string",
        "}",
        "",
        "type RedactionRule struct {",
        "\tCategory string",
        "\tAction RedactionAction",
        "\tMatches []string",
        "}",
        "",
        "type RedactionActionDefinition struct {",
        "\tName RedactionAction",
        "\tDescription string",
        "\tValuePreserved bool",
        "\tReplacementUsed bool",
        "\tReplacementMarker string",
        "}",
        "",
        "// FieldDefinitions and EventDefinitions are immutable by convention.",
        "var FieldDefinitions = map[FieldName]FieldDefinition{",
    ])
    for field in fields:
        name = f"FieldName{_identifier(field.name)}"
        lines.append(
            f"\t{name}: {{Name: {name}, Type: {_q(field.type)}, Required: {_b(field.required)}, "
            f"Description: {_q(field.description)}, Sensitivity: {_q(field.sensitivity)}}},"
        )
    lines.extend(["}", "", "var ServiceDefinitions = map[ServiceKey]ServiceDefinition{"])
    for service in services:
        key = f"ServiceKey{_identifier(service.key)}"
        lines.append(f"\t{key}: {{Key: {key}, EmittedName: {_q(service.emitted_name)}}},")
    lines.extend(["}", "", "var EventDefinitions = map[EventName]EventDefinition{"])
    for event in events:
        name = f"EventName{_identifier(event.name)}"
        event_services = ", ".join(
            f"ServiceKey{_identifier(service)}" for service in sorted(event.services)
        )
        lines.append(
            f"\t{name}: {{Name: {name}, Category: {_q(event.category)}, "
            f"DefaultLevel: Level{_identifier(event.default_level)}, Description: {_q(event.description)}, "
            f"Services: []ServiceKey{{{event_services}}}, TraceRequired: {_b(event.trace_required)}, "
            f"AuditEligible: {_b(event.audit_eligible)}, RetentionTier: RetentionTier{_identifier(event.retention_tier)}, "
            f"BridgeOnly: {_b(event.bridge_only)}}},"
        )
    lines.extend(["}", "", "var RedactionActionDefinitions = map[RedactionAction]RedactionActionDefinition{"])
    for action in sorted(redaction.actions, key=lambda item: item.name):
        action_name = f"RedactionAction{_identifier(action.name)}"
        lines.append(
            f"\t{action_name}: {{Name: {action_name}, Description: {_q(action.description)}, "
            f"ValuePreserved: {_b(action.value_preserved)}, ReplacementUsed: {_b(action.replacement_used)}, "
            f"ReplacementMarker: {_q(action.replacement_marker or '')}}},"
        )
    replacement_marker = next(
        action.replacement_marker
        for action in redaction.actions
        if action.replacement_used and action.replacement_marker is not None
    )
    lines.extend([
        "}",
        "",
        f"const RedactionCaseSensitive = {_b(redaction.case_sensitive)}",
        f"const RedactionKeyMatching = {_q(redaction.key_matching)}",
        f"const RedactionMissingAction RedactionAction = RedactionAction{_identifier(redaction.missing_action)}",
        f"const RedactionAmbiguousMatchAction RedactionAction = RedactionAction{_identifier(redaction.ambiguous_match_action)}",
        f"const RedactionFailureAction RedactionAction = RedactionAction{_identifier(redaction.redaction_failure_action)}",
        f"const RejectedContentMustBeDiscarded = {_b(redaction.rejected_content_must_be_discarded)}",
        f"const RedactionReplacementMarker = {_q(replacement_marker)}",
        "",
        "var RedactionExactRules = []RedactionRule{",
    ])
    for rule in sorted(redaction.exact_rules, key=lambda item: item.category):
        matches = ", ".join(_q(key) for key in sorted(rule.keys))
        lines.append(
            f"\t{{Category: {_q(rule.category)}, Action: RedactionAction{_identifier(rule.action)}, Matches: []string{{{matches}}}}},"
        )
    lines.extend(["}", "", "var RedactionFragmentRules = []RedactionRule{"])
    for rule in sorted(redaction.fragment_rules, key=lambda item: item.category):
        matches = ", ".join(_q(fragment) for fragment in sorted(rule.fragments))
        lines.append(
            f"\t{{Category: {_q(rule.category)}, Action: RedactionAction{_identifier(rule.action)}, Matches: []string{{{matches}}}}},"
        )
    lines.extend([
        "}",
        "",
        "func IsCanonicalLevel(value Level) bool {",
        "\tswitch value {",
        f"\tcase {', '.join(f'Level{_identifier(level)}' for level in envelope.canonical_levels)}:",
        "\t\treturn true",
        "\tdefault:",
        "\t\treturn false",
        "\t}",
        "}",
        "",
        "func IsKnownField(value FieldName) bool {",
        "\t_, ok := FieldDefinitions[value]",
        "\treturn ok",
        "}",
        "",
        "func IsKnownEvent(value EventName) bool {",
        "\t_, ok := EventDefinitions[value]",
        "\treturn ok",
        "}",
        "",
        "func ServiceDefinitionFor(value ServiceKey) (ServiceDefinition, bool) {",
        "\tdefinition, ok := ServiceDefinitions[value]",
        "\treturn definition, ok",
        "}",
        "",
        "func IsRetentionTier(value RetentionTier) bool {",
        "\tswitch value {",
        f"\tcase {', '.join(f'RetentionTier{_identifier(tier.name)}' for tier in tiers)}:",
        "\t\treturn true",
        "\tdefault:",
        "\t\treturn false",
        "\t}",
        "}",
        "",
        "func FieldDefinitionFor(value FieldName) (FieldDefinition, bool) {",
        "\tdefinition, ok := FieldDefinitions[value]",
        "\treturn definition, ok",
        "}",
        "",
        "func EventDefinitionFor(value EventName) (EventDefinition, bool) {",
        "\tdefinition, ok := EventDefinitions[value]",
        "\treturn definition, ok",
        "}",
        "",
        f"const UUIDPattern = {_q(schema.identifiers.uuid_pattern)}",
        f"const EventNamePattern = {_q(envelope.event_name_pattern)}",
        f"const FreeFormKeyPattern = {_q(schema.free_form_fields.key_pattern)}",
        f"const NullValuesAllowed = {_b(schema.validation.null_values_allowed)}",
        f"const RejectUnknownTopLevelFields = {_b(envelope.reject_unknown_top_level_fields)}",
        "",
    ])

    limit_entries = [
        ("MaxBatchEvents", limits.max_batch_events),
        ("MaxEventBytes", limits.max_event_bytes),
        ("MaxEventFields", limits.max_event_fields),
        ("MaxStringBytes", limits.max_string_bytes),
        ("MaxCollectionItems", limits.max_collection_items),
        ("MaxFreeFormFields", limits.max_free_form_fields),
        ("MaxFreeFormValueBytes", limits.max_free_form_value_bytes),
        ("MaxDiagnosticBundleEvents", contract.diagnostic_bundle.max_events),
        ("MaxDiagnosticBundleEventBytes", contract.diagnostic_bundle.max_event_bytes),
        ("MaxDiagnosticBundleTotalBytes", contract.diagnostic_bundle.max_total_bytes),
        ("MaxDiagnosticBundleMetadataFields", contract.diagnostic_bundle.max_metadata_fields),
        ("MaxDiagnosticBundleCorrelationFields", contract.diagnostic_bundle.max_correlation_fields),
        ("MaxDiagnosticBundleRedactionSummaryEntries", contract.diagnostic_bundle.max_redaction_summary_entries),
    ]
    _const_block(lines, [f"{name} = {value}" for name, value in limit_entries])
    return "\n".join(lines).rstrip("\n") + "\n"
