from __future__ import annotations

import json
from collections import defaultdict

from data_sync.model.realtime_wire import RealtimeWireContract


def _literal(value: object) -> str:
    return json.dumps(value, sort_keys=True, separators=(",", ":"))


def generate_realtime_wire_gds(contract: RealtimeWireContract) -> str:
    data = contract.as_dict()
    key_forward: dict[str, str] = {}
    key_reverse: dict[str, str] = {}
    for alias in contract.key_aliases:
        key_forward[f"{alias.domain}.{alias.readable}"] = alias.compact
        key_reverse[f"{alias.domain}.{alias.compact}"] = alias.readable

    value_forward: dict[str, dict[str, str]] = {}
    value_reverse: dict[str, dict[str, str]] = {}
    for domain in contract.value_domains:
        value_forward[domain.id] = {entry.readable: entry.compact for entry in domain.entries}
        value_reverse[domain.id] = {entry.compact: entry.readable for entry in domain.entries}

    packet_lookup = {packet.compact: packet.id for packet in contract.packets}
    quantization_policies = {
        item.path: item.policy
        for item in sorted(contract.quantizations, key=lambda item: item.path)
    }
    bindings: dict[str, list[str]] = defaultdict(list)
    for binding in contract.packet_fields:
        bindings[f"{binding.packet_id}.{binding.readable_field}"].append(binding.record_id)
        bindings[f"{binding.packet_id}.{binding.readable_field}"].extend(binding.decode_record_ids)

    lines = [
        "# Code generated by data-sync; DO NOT EDIT.",
        "class_name RealtimeWireGenerated",
        "extends RefCounted",
        "",
        f"const CONTRACT_ID := {_literal(contract.id)}",
        f"const CONTRACT_VERSION := {contract.version}",
        f"const READABLE_KEYS := {_literal(contract.readable_keys)}",
        f"const EXPLICIT_METADATA := {_literal(contract.explicit_metadata)}",
        f"const UNKNOWN_KEY_PASSTHROUGH := {_literal(contract.unknown_key_passthrough)}",
        f"const UNKNOWN_EVENT_PASSTHROUGH := {_literal(contract.unknown_event_passthrough)}",
        f"const CONTRACT := {_literal(data)}",
        f"const KEY_COMPACT_BY_READABLE := {_literal(key_forward)}",
        f"const KEY_READABLE_BY_COMPACT := {_literal(key_reverse)}",
        f"const VALUE_COMPACT_BY_READABLE := {_literal(value_forward)}",
        f"const VALUE_READABLE_BY_COMPACT := {_literal(value_reverse)}",
        f"const PACKET_ID_BY_COMPACT := {_literal(packet_lookup)}",
        f"const QUANTIZATION_POLICY_BY_PATH := {_literal(quantization_policies)}",
        f"const PACKET_FIELD_RECORD_IDS := {_literal(dict(sorted(bindings.items())))}",
        f"const EVENTS_BY_READABLE := {_literal({item.readable: item.__dict__ for item in contract.events})}",
        f"const EVENTS_BY_COMPACT := {_literal({item.compact: item.__dict__ for item in contract.events})}",
        "",
    ]
    return "\n".join(lines)
