from __future__ import annotations

import json
from collections import defaultdict

from data_sync.model.realtime_wire import RealtimeWireContract


def _q(value: str) -> str:
    return json.dumps(value)


def _b(value: bool) -> str:
    return "true" if value else "false"


def generate_realtime_wire_go(contract: RealtimeWireContract) -> str:
    lines = [
        "// Code generated by data-sync; DO NOT EDIT.",
        "package realtimewire",
        "",
        "type RealtimeWireKeyAlias struct { Domain, Readable, Compact string }",
        "type RealtimeWireValueAlias struct { Domain, Readable, Compact string }",
        "type RealtimeWireIDCodec struct { ID, Prefix, Tag string; NumericSuffix, PreserveMalformed bool }",
        "type RealtimeWireSelectorMapping struct { Value, CodecID string }",
        "type RealtimeWireIDSelector struct { ID, Field string; FallbackTagged bool; Mappings []RealtimeWireSelectorMapping }",
        "type RealtimeWireQuantization struct { Path, Policy string }",
        "type RealtimeWirePacket struct { ID, Compact, Lane, SnapshotKind string; Runtime, InferLane, InferSnapshotKind, InferSnapshotID, InferBaselineID, UseBaselineSequence, OmitSingleChunkMetadata bool }",
        "type RealtimeWireField struct { Name, JSON, CompactKey, Quantization, IDCodec, IDCodecBy, ValueDomain string }",
        "type RealtimeWireRecord struct { ID, SourceStruct, Encoding, IdentityField, SparsePlaceholder string; SparseTrailing, PreserveUnknownFields bool; Fields []RealtimeWireField }",
        "type RealtimeWirePacketFieldBinding struct { PacketID, ReadableField string; RecordIDs []string }",
        "type RealtimeWireEvent struct { Readable, Compact, RecordID string }",
        "",
        f"const RealtimeWireContractID = {_q(contract.id)}",
        f"const RealtimeWireContractVersion = {contract.version}",
        f"const RealtimeWireReadableKeys = {_b(contract.readable_keys)}",
        f"const RealtimeWireExplicitMetadata = {_b(contract.explicit_metadata)}",
        f"const RealtimeWireUnknownKeyPassthrough = {_b(contract.unknown_key_passthrough)}",
        f"const RealtimeWireUnknownEventPassthrough = {_b(contract.unknown_event_passthrough)}",
        "",
    ]

    key_aliases = sorted(contract.key_aliases, key=lambda item: (item.domain, item.readable, item.compact))
    lines.append("var RealtimeWireKeyAliases = []RealtimeWireKeyAlias{")
    for item in key_aliases:
        lines.append(f"\t{{Domain: {_q(item.domain)}, Readable: {_q(item.readable)}, Compact: {_q(item.compact)}}},")
    lines.append("}")
    lines.append("var RealtimeWireKeyCompactByReadable = map[string]string{")
    for item in key_aliases:
        lines.append(f"\t{_q(item.domain + '.' + item.readable)}: {_q(item.compact)},")
    lines.append("}")
    lines.append("var RealtimeWireKeyReadableByCompact = map[string]string{")
    for item in key_aliases:
        lines.append(f"\t{_q(item.domain + '.' + item.compact)}: {_q(item.readable)},")
    lines.append("}")

    lines.append("var RealtimeWireValueDomains = map[string][]RealtimeWireValueAlias{")
    for domain in sorted(contract.value_domains, key=lambda item: item.id):
        entries = sorted(domain.entries, key=lambda item: (item.readable, item.compact))
        values = ", ".join(f"{{Domain: {_q(domain.id)}, Readable: {_q(entry.readable)}, Compact: {_q(entry.compact)}}}" for entry in entries)
        lines.append(f"\t{_q(domain.id)}: {{{values}}},")
    lines.append("}")
    lines.append("var RealtimeWireValueCompactByReadable = map[string]map[string]string{")
    for domain in sorted(contract.value_domains, key=lambda item: item.id):
        lines.append(f"\t{_q(domain.id)}: {{")
        for entry in sorted(domain.entries, key=lambda item: (item.readable, item.compact)):
            lines.append(f"\t\t{_q(entry.readable)}: {_q(entry.compact)},")
        lines.append("\t},")
    lines.append("}")
    lines.append("var RealtimeWireValueReadableByCompact = map[string]map[string]string{")
    for domain in sorted(contract.value_domains, key=lambda item: item.id):
        lines.append(f"\t{_q(domain.id)}: {{")
        for entry in sorted(domain.entries, key=lambda item: (item.readable, item.compact)):
            lines.append(f"\t\t{_q(entry.compact)}: {_q(entry.readable)},")
        lines.append("\t},")
    lines.append("}")

    lines.append("var RealtimeWireIDCodecs = []RealtimeWireIDCodec{")
    for item in sorted(contract.id_codecs, key=lambda item: item.id):
        lines.append(f"\t{{ID: {_q(item.id)}, Prefix: {_q(item.prefix)}, Tag: {_q(item.tag or '')}, NumericSuffix: {_b(item.numeric_suffix)}, PreserveMalformed: {_b(item.preserve_malformed)}}},")
    lines.append("}")
    lines.append("var RealtimeWireIDSelectors = []RealtimeWireIDSelector{")
    for selector in sorted(contract.id_selectors, key=lambda item: item.id):
        mappings = ", ".join(f"{{Value: {_q(item.value)}, CodecID: {_q(item.codec_id)}}}" for item in sorted(selector.mappings, key=lambda item: (item.value, item.codec_id)))
        lines.append(f"\t{{ID: {_q(selector.id)}, Field: {_q(selector.field)}, FallbackTagged: {_b(selector.fallback_tagged)}, Mappings: []RealtimeWireSelectorMapping{{{mappings}}}}},")
    lines.append("}")
    lines.append("var RealtimeWireQuantizations = map[string]string{")
    for item in sorted(contract.quantizations, key=lambda item: item.path):
        lines.append(f"\t{_q(item.path)}: {_q(item.policy)},")
    lines.append("}")

    lines.append("var RealtimeWirePackets = []RealtimeWirePacket{")
    for item in sorted(contract.packets, key=lambda item: item.id):
        lines.append(f"\t{{ID: {_q(item.id)}, Compact: {_q(item.compact)}, Lane: {_q(item.lane)}, SnapshotKind: {_q(item.snapshot_kind or '')}, Runtime: {_b(item.runtime)}, InferLane: {_b(item.infer_lane)}, InferSnapshotKind: {_b(item.infer_snapshot_kind)}, InferSnapshotID: {_b(item.infer_snapshot_id)}, InferBaselineID: {_b(item.infer_baseline_id)}, UseBaselineSequence: {_b(item.use_baseline_sequence)}, OmitSingleChunkMetadata: {_b(item.omit_single_chunk_metadata)}}},")
    lines.append("}")
    lines.append("var RealtimeWirePacketByCompact = map[string]string{")
    for item in sorted(contract.packets, key=lambda item: item.compact):
        lines.append(f"\t{_q(item.compact)}: {_q(item.id)},")
    lines.append("}")

    compact_keys = {item.readable: item.compact for item in key_aliases}
    lines.append("var RealtimeWireRecords = []RealtimeWireRecord{")
    for record in sorted(contract.records, key=lambda item: item.id):
        lines.append(f"\t{{ID: {_q(record.id)}, SourceStruct: {_q(record.source_struct or '')}, Encoding: {_q(record.encoding)}, IdentityField: {_q(record.identity_field or '')}, SparsePlaceholder: {_q(record.sparse_placeholder or '')}, SparseTrailing: {_b(record.sparse_trailing)}, PreserveUnknownFields: {_b(record.preserve_unknown_fields)}, Fields: []RealtimeWireField{{")
        for field in record.fields:
            lines.append(f"\t\t{{Name: {_q(field.name)}, JSON: {_q(field.json)}, CompactKey: {_q(compact_keys.get(field.json, field.json))}, Quantization: {_q(field.quantization or '')}, IDCodec: {_q(field.id_codec or '')}, IDCodecBy: {_q(field.id_codec_by or '')}, ValueDomain: {_q(field.value_domain or '')}}},")
        lines.append("\t}},")
    lines.append("}")

    bindings: dict[tuple[str, str], list[str]] = defaultdict(list)
    for item in contract.packet_fields:
        bindings[(item.packet_id, item.readable_field)].append(item.record_id)
    lines.append("var RealtimeWirePacketFieldBindings = []RealtimeWirePacketFieldBinding{")
    for (packet_id, field), record_ids in sorted(bindings.items()):
        ids = ", ".join(_q(value) for value in sorted(record_ids))
        lines.append(f"\t{{PacketID: {_q(packet_id)}, ReadableField: {_q(field)}, RecordIDs: []string{{{ids}}}}},")
    lines.append("}")
    lines.append("var RealtimeWireEventsByReadable = map[string]RealtimeWireEvent{")
    for item in sorted(contract.events, key=lambda item: item.readable):
        lines.append(f"\t{_q(item.readable)}: {{Readable: {_q(item.readable)}, Compact: {_q(item.compact)}, RecordID: {_q(item.record_id)}}},")
    lines.append("}")
    lines.append("var RealtimeWireEventsByCompact = map[string]RealtimeWireEvent{")
    for item in sorted(contract.events, key=lambda item: item.compact):
        lines.append(f"\t{_q(item.compact)}: {{Readable: {_q(item.readable)}, Compact: {_q(item.compact)}, RecordID: {_q(item.record_id)}}},")
    lines.append("}")
    return "\n".join(lines) + "\n"
