from __future__ import annotations

from data_sync.model.realtime_wire import RealtimeWireContract


def _cell(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\n", " ")


def generate_realtime_wire_docs(contract: RealtimeWireContract) -> str:
    lines = [
        "<!-- Code generated by data-sync; DO NOT EDIT. -->",
        "# Realtime Wire Contract",
        "",
        "Parent index: [Generated](./!INDEX.md)",
        "",
        f"- ID: `{contract.id}`",
        f"- Version: `{contract.version}`",
        f"- Readable keys: `{str(contract.readable_keys).lower()}`",
        f"- Explicit metadata: `{str(contract.explicit_metadata).lower()}`",
        f"- Unknown key passthrough: `{str(contract.unknown_key_passthrough).lower()}`",
        f"- Unknown event passthrough: `{str(contract.unknown_event_passthrough).lower()}`",
        "",
        "## Key aliases",
        "",
        "| Domain | Readable | Compact |",
        "| --- | --- | --- |",
    ]
    lines.extend(f"| {_cell(item.domain)} | `{_cell(item.readable)}` | `{_cell(item.compact)}` |" for item in sorted(contract.key_aliases, key=lambda item: (item.domain, item.readable)))
    lines += ["", "## Value domains", ""]
    for domain in sorted(contract.value_domains, key=lambda item: item.id):
        lines += [f"### `{domain.id}`", "", "| Readable | Compact |", "| --- | --- |"]
        lines.extend(f"| `{_cell(item.readable)}` | `{_cell(item.compact)}` |" for item in sorted(domain.entries, key=lambda item: (item.readable, item.compact)))
        lines.append("")

    lines += ["## ID codecs and selectors", "", "### Codecs", "", "| ID | Prefix | Tag | Numeric suffix | Preserve malformed |", "| --- | --- | --- | --- | --- |"]
    lines.extend(f"| `{item.id}` | `{_cell(item.prefix)}` | `{_cell(item.tag or '')}` | `{str(item.numeric_suffix).lower()}` | `{str(item.preserve_malformed).lower()}` |" for item in sorted(contract.id_codecs, key=lambda item: item.id))
    lines += ["", "### Selectors", "", "| ID | Field | Fallback tagged | Mappings |", "| --- | --- | --- | --- |"]
    lines.extend(f"| `{item.id}` | `{item.field}` | `{str(item.fallback_tagged).lower()}` | {_cell(', '.join(f'{mapping.value} → {mapping.codec_id}' for mapping in item.mappings))} |" for item in sorted(contract.id_selectors, key=lambda item: item.id))

    lines += ["", "## Quantization", "", "| Path | Policy |", "| --- | --- |"]
    lines.extend(f"| `{item.path}` | `{item.policy}` |" for item in sorted(contract.quantizations, key=lambda item: item.path))

    lines += ["", "## Packets", "", "| ID | Compact | Lane | Snapshot | Runtime |", "| --- | --- | --- | --- | --- |"]
    lines.extend(f"| `{item.id}` | `{item.compact}` | `{item.lane}` | `{item.snapshot_kind or ''}` | `{str(item.runtime).lower()}` |" for item in sorted(contract.packets, key=lambda item: item.id))

    lines += ["", "## Records", ""]
    for record in sorted(contract.records, key=lambda item: item.id):
        lines += [f"### `{record.id}`", "", f"- Encoding: `{record.encoding}`", f"- Source struct: `{record.source_struct or ''}`", f"- Identity field: `{record.identity_field or ''}`", f"- Sparse placeholder: `{record.sparse_placeholder or ''}`", f"- Sparse trailing: `{str(record.sparse_trailing).lower()}`", f"- Preserve unknown fields: `{str(record.preserve_unknown_fields).lower()}`", "", "| Name | JSON | Quantization | ID codec | Selector | Value domain |", "| --- | --- | --- | --- | --- | --- |"]
        lines.extend(f"| `{field.name}` | `{field.json}` | `{field.quantization or ''}` | `{field.id_codec or ''}` | `{field.id_codec_by or ''}` | `{field.value_domain or ''}` |" for field in record.fields)
        lines.append("")

    lines += ["## Packet bindings", "", "| Packet | Field | Primary encode record | Decode alternatives |", "| --- | --- | --- | --- |"]
    grouped: dict[tuple[str, str], tuple[str, list[str]]] = {}
    for binding in contract.packet_fields:
        grouped[(binding.packet_id, binding.readable_field)] = (binding.record_id, list(binding.decode_record_ids))
    lines.extend(f"| `{packet}` | `{field}` | `{primary}` | `{_cell(', '.join(alternatives))}` |" for (packet, field), (primary, alternatives) in sorted(grouped.items()))
    lines += ["", "## Events", "", "| Readable | Compact | Record |", "| --- | --- | --- |"]
    lines.extend(f"| `{item.readable}` | `{item.compact}` | `{item.record_id}` |" for item in sorted(contract.events, key=lambda item: item.readable))
    return "\n".join(lines) + "\n"
