"""TOML-backed Go packet schema generation."""

from __future__ import annotations

from data_sync.model.packets import PacketOutput, PacketSchema, PacketStruct, PacketType
from data_sync.packet_rendering import (
    PacketRenderingError,
    go_field_name,
    go_json_tag,
    go_type_for_field,
    snake_to_go_name,
)


GENERATED_HEADER = "Code generated by tools/data_sync/main.py; DO NOT EDIT."


class RichGoPacketGenerationError(Exception):
    """Raised when rich Go packet generation cannot complete."""


def render_go_output(schema: PacketSchema, output: PacketOutput) -> str:
    if output.language != "go":
        raise RichGoPacketGenerationError(f"output is not Go: {output.path}")
    if not output.package:
        raise RichGoPacketGenerationError(f"Go output missing package: {output.path}")

    lines = [
        f"// {GENERATED_HEADER}",
        f"package {output.package}",
    ]

    imports = output.imports or {}
    if imports:
        lines.append("")
        if len(imports) == 1:
            alias, path = next(iter(imports.items()))
            lines.append(f'import {alias} "{path}"')
        else:
            lines.append("import (")
            for alias, path in sorted(imports.items()):
                lines.append(f'\t{alias} "{path}"')
            lines.append(")")

    if output.packet_types or output.packet_type_ids:
        lines.append("")
        lines.extend(render_go_packet_type_constants(_selected_packet_types(schema, output)))

    for struct_id in output.structs:
        lines.append("")
        lines.extend(render_go_struct(schema.struct(struct_id)))

    return "\n".join(lines) + "\n"


def render_go_packet_type_constants(packet_types: tuple[PacketType, ...]) -> list[str]:
    constants = [
        (f"PacketType{snake_to_go_name(packet_type.id)}", packet_type.value)
        for packet_type in packet_types
    ]
    if not constants:
        return []

    lines = ["const ("]
    max_name_length = max(len(name) for name, _value in constants)
    for name, value in constants:
        lines.append(f'\t{name.ljust(max_name_length)} = "{escape_go_string(value)}"')
    lines.append(")")
    return lines


def _selected_packet_types(schema: PacketSchema, output: PacketOutput) -> tuple[PacketType, ...]:
    if not output.packet_type_ids:
        return schema.packet_types

    selected: list[PacketType] = []
    for packet_type_id in output.packet_type_ids:
        try:
            selected.append(schema.packet_type(packet_type_id))
        except KeyError as exc:
            raise RichGoPacketGenerationError(f"unknown packet_type_id for output {output.path}: {packet_type_id}") from exc
    return tuple(selected)


def render_go_struct(struct: PacketStruct) -> list[str]:
    lines = [f"type {struct.id} struct {{"]
    fields = [render_go_field(field) for field in struct.fields]
    if fields:
        max_name_length = max(len(field[0]) for field in fields)
        max_type_length = max(len(field[1]) for field in fields)
        for name, go_type, tag in fields:
            lines.append(f"\t{name.ljust(max_name_length)} {go_type.ljust(max_type_length)} `{tag}`")
    lines.append("}")
    return lines


def render_go_field(field) -> tuple[str, str, str]:
    try:
        return go_field_name(field), go_type_for_field(field), go_json_tag(field)
    except PacketRenderingError as exc:
        raise RichGoPacketGenerationError(str(exc)) from exc


def escape_go_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
