"""TOML-backed GDScript packet schema generation."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any

from data_sync.model.packets import PacketBuilder, PacketOutput, PacketSchema
from data_sync.packet_rendering import constant_name, gdscript_field_constant, gdscript_leaf


GENERATED_HEADER = "Code generated by tools/data_sync/main.py; DO NOT EDIT."


class RichGdsPacketGenerationError(Exception):
    """Raised when rich GDScript packet generation cannot complete."""


def render_gdscript_output(schema: PacketSchema, output: PacketOutput) -> str:
    if output.language != "gdscript":
        raise RichGdsPacketGenerationError(f"output is not GDScript: {output.path}")

    lines = [
        f"# {GENERATED_HEADER}",
        f"extends {output.base or 'RefCounted'}",
        "",
    ]

    lines.extend(render_packet_type_constants(schema))
    lines.append("")
    lines.extend(render_field_constants(schema))

    for builder_id in output.builders:
        lines.append("")
        lines.extend(render_builder(schema.builder(builder_id)))

    return "\n".join(lines) + "\n"


def render_packet_type_constants(schema: PacketSchema) -> list[str]:
    return [
        f'const TYPE_{constant_name(packet_type.id)} := "{_escape_gdscript_string(packet_type.value)}"'
        for packet_type in schema.packet_types
    ]


def render_field_constants(schema: PacketSchema) -> list[str]:
    fields = sorted({field.json for struct in schema.structs for field in struct.fields})
    return [
        f'const {gdscript_field_constant(field_name)} := "{_escape_gdscript_string(field_name)}"'
        for field_name in fields
    ]


def render_builder(builder: PacketBuilder) -> list[str]:
    args = ", ".join(builder.args)
    lines = [f"static func {builder.id}({args}) -> Dictionary:"]
    lines.extend(render_assignments("packet", builder.body, indent=1))
    lines.append("\treturn packet")
    return lines


def render_assignments(variable_name: str, value: Any, indent: int) -> list[str]:
    prefix = "\t" * indent
    if not isinstance(value, Mapping):
        raise RichGdsPacketGenerationError("top-level GDScript builder body must be a dictionary")

    lines = [f"{prefix}var {variable_name} := {{}}"]
    for key, item in value.items():
        key_expr = gdscript_field_constant(str(key))
        if isinstance(item, Mapping):
            child_name = f"{variable_name}_{key}"
            lines.extend(render_assignments(child_name, item, indent))
            lines.append(f"{prefix}{variable_name}[{key_expr}] = {child_name}")
        else:
            lines.append(f"{prefix}{variable_name}[{key_expr}] = {gdscript_leaf(item)}")
    return lines


def _escape_gdscript_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
