extends RefCounted
class_name RealtimeReceiveLimits

const MAX_PENDING_MATCH_BUCKETS := 4
const MAX_PACKETS_PER_MATCH := 128
const MAX_ESTIMATED_PACKET_BYTES_PER_MATCH := 256 * 1024
const PENDING_BUCKET_LIFETIME_MSEC := 5000
const MAX_WORLD_FULL_CHUNKS_PER_ASSEMBLY := 128
const MAX_WORLD_FULL_RECORDS_PER_ASSEMBLY := 16384
const MAX_WORLD_FULL_ESTIMATED_BYTES_PER_ASSEMBLY := 2 * 1024 * 1024
const WORLD_FULL_ASSEMBLY_LIFETIME_MSEC := 5000
const MAX_LIFECYCLE_CHUNKS_PER_ASSEMBLY := 128
const MAX_LIFECYCLE_RECORDS_PER_ASSEMBLY := 16384
const MAX_LIFECYCLE_ESTIMATED_BYTES_PER_ASSEMBLY := 2 * 1024 * 1024
const LIFECYCLE_ASSEMBLY_LIFETIME_MSEC := 5000
const MAX_HOT_DELTA_CHUNKS_PER_ASSEMBLY := 128
const MAX_HOT_DELTA_RECORDS_PER_ASSEMBLY := 16384
const MAX_HOT_DELTA_ESTIMATED_BYTES_PER_ASSEMBLY := 2 * 1024 * 1024
