// Code generated by tools/scripts/generate_constants.py; DO NOT EDIT.
package constants

const (
	ServerTickRate = 60

	PlayerRotationSpeed       = 4.0
	PlayerThrustForce         = 1000.0
	PlayerMaxSpeed            = 1500.0
	PlayerDamping             = 0.98
	PlayerStartingLives       = 1
	PlayerRespawnDelay        = 3.0
	PlayerRespawnSearchRadius = 240.0
	GameOverSoundDelay        = 0.35

	BaseScore = 120

	BackgroundParallax           = 0.25
	ForegroundBackgroundParallax = 0.45
	ForegroundBackgroundOffsetX  = 480.0
	ForegroundBackgroundOffsetY  = 270.0
	PlayerInterpolationSpeed     = 18.0
	WorldWidth                   = 1152.0
	WorldHeight                  = 640.0

	AsteroidSpawnInterval        = 3.0
	AsteroidSpawnBatchSize       = 3
	AsteroidSpawnMargin          = 160.0
	AsteroidDespawnMargin        = 320.0
	AsteroidMinSpeed             = 90.0
	AsteroidMaxSpeed             = 170.0
	AsteroidSizeScale            = 0.125
	AsteroidAimRandomnessDegrees = 30.0

	BulletSpeed           = 900.0
	BulletLifetime        = 1.25
	BulletCooldown        = 0.2
	BulletSpawnOffset     = 42.0
	CollisionDespawnDelay = 0.05
)
